/*
	Leader Badge Colours
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

-----------------------------------------------
-- PlayerColors
-----------------------------------------------
INSERT INTO PlayerColors (Type,	Usage,	PrimaryColor,	SecondaryColor	)
VALUES	(
		'CIVILIZATION_IPG_OFIR_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_SCIENCE_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_ZERRIKANIA_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_HAAKLAND_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_ZANGVEBAR_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_LANDS_ORDER_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_SASKIA_FREE_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_CULTURAL_SECONDARY'
		);