/*
	Core Leader Configuration
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/
-----------------------------------------------
-- City-State
-----------------------------------------------
INSERT INTO CityStates
		(Domain,					CivilizationType,						CityStateCategory,	Name,											Icon,										Bonus)
VALUES	('Expansion2CityStates',	'CIVILIZATION_IPG_OFIR_MINOR',			'SCIENTIFIC',		'LOC_CIVILIZATION_IPG_OFIR_MINOR_NAME',			'ICON_CIVILIZATION_IPG_OFIR_MINOR',			'LOC_MINOR_CIV_IPG_OFIR_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_ZERRIKANIA_MINOR',	'RELIGIOUS',		'LOC_CIVILIZATION_IPG_ZERRIKANIA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_ZERRIKANIA_MINOR',	'LOC_MINOR_CIV_IPG_ZERRIKANIA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_HAAKLAND_MINOR',		'MILITARISTIC',		'LOC_CIVILIZATION_IPG_HAAKLAND_MINOR_NAME',		'ICON_CIVILIZATION_IPG_HAAKLAND_MINOR',		'LOC_MINOR_CIV_IPG_HAAKLAND_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_ZANGVEBAR_MINOR',		'TRADE',			'LOC_CIVILIZATION_IPG_ZANGVEBAR_MINOR_NAME',	'ICON_CIVILIZATION_IPG_ZANGVEBAR_MINOR',	'LOC_MINOR_CIV_IPG_ZANGVEBAR_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_LANDS_ORDER_MINOR',	'RELIGIOUS',		'LOC_CIVILIZATION_IPG_LANDS_ORDER_MINOR_NAME',	'ICON_CIVILIZATION_IPG_LANDS_ORDER_MINOR',	'LOC_MINOR_CIV_IPG_LANDS_ORDER_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_SASKIA_FREE_MINOR',	'CULTURAL',			'LOC_CIVILIZATION_IPG_SASKIA_FREE_MINOR_NAME',	'ICON_CIVILIZATION_IPG_SASKIA_FREE_MINOR',	'LOC_MINOR_CIV_IPG_SASKIA_FREE_MINOR_TRAIT_DESCRIPTION');
