INSERT INTO IconTextureAtlases
		(Name,												IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			32,			1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_32.dds'),
		('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			38,			1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_38.dds'),
		('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			50,			1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_50.dds'),
		('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			80,			1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_80.dds'),
		('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			128,		1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_128.dds'),
		('ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			256,		1,				1,				'ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_256.dds'),

		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				256,		1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_256.dds'		),
		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				128,		1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_128.dds'		),
		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				80,			1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_80.dds'			),
		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				50,			1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_50.dds'			),
		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				38,			1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_38.dds'			),
		('ICON_ATLAS_PHANTA_TORII_GATE_ICON',				32,			1,				1,				'ICON_IMPROVEMENT_PHANTA_TORII_GATE_32.dds'			);
		

--------------------------------------------------------------
-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,												Atlas,												'Index')
VALUES	('ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA',		'ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			0),
		('ICON_BUILDING_PHANTA_FUSHIMI_INARI_TAISHA_FOW',	'ICON_ATLAS_PHANTA_FUSHIMI_INARI_TAISHA',			0),
		('ICON_IMPROVEMENT_PHANTA_TORII_GATE',				'ICON_ATLAS_PHANTA_TORII_GATE_ICON',				0);
--------------------------------------------------------------