/*
	Civilization Unique Ability
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO	Types
		(Type,																	Kind			)
VALUES	('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',							'KIND_TRAIT'	),
		('REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	'KIND_MODIFIER'	);
-----------------------------------------------
-- Traits
-----------------------------------------------
INSERT INTO	Traits	
		(TraitType,											Name,														Description														)
VALUES	('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'LOC_TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD_NAME',		'LOC_TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD_DESCRIPTION'	);

INSERT INTO	CivilizationTraits
		(CivilizationType,					TraitType									)
VALUES	('CIVILIZATION_IPG_REDANIA',		'TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD'	);

INSERT INTO	TraitModifiers	
		(TraitType,											ModifierId										)
VALUES	('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INTERNATIONAL_TRADE_COMMERCIAL_HUB'	),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INTERNATIONAL_TRADE_MARKET'			),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INTERNATIONAL_TRADE_BANK'				),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INTERNATIONAL_TRADE_STOCK_EXCHANGE'	),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INCOMING_TRADE_GAIN_GOLD'				),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_INCOMING_TRADE_GIVE_FOOD'				),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_ADJUST_BUILDER_EXTRA_CHARGE'			),
		('TRAIT_CIVILIZATION_MERCHANTS_OF_NOVIGRAD',		'REDANIA_ADJUST_BUILDER_PRODUCTION'				);
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT INTO DynamicModifiers
		(ModifierType,															CollectionType,				EffectType													)
VALUES	('REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	'COLLECTION_PLAYER_CITIES',	'EFFECT_ADJUST_CITY_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL'	);

INSERT INTO	Modifiers
		(ModifierId,									ModifierType,															SubjectRequirementSetId		)
VALUES	('REDANIA_INTERNATIONAL_TRADE_COMMERCIAL_HUB',	'REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'CITY_HAS_COMMERCIAL_HUB'	),
		('REDANIA_INTERNATIONAL_TRADE_MARKET',			'REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'BUILDING_IS_MARKET'		),
		('REDANIA_INTERNATIONAL_TRADE_BANK',			'REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'BUILDING_IS_BANK'			),
		('REDANIA_INTERNATIONAL_TRADE_STOCK_EXCHANGE',	'REDANIA_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'BUILDING_IS_STOCK_EXCHANGE'),
		('REDANIA_INCOMING_TRADE_GAIN_GOLD',			'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FROM_OTHERS',			null	),
		('REDANIA_INCOMING_TRADE_GIVE_FOOD',			'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',			null	),
		('REDANIA_ADJUST_BUILDER_EXTRA_CHARGE',			'MODIFIER_PLAYER_UNITS_ADJUST_BUILDER_CHARGES',							'UNIT_IS_BUILDER'	),
		('REDANIA_ADJUST_BUILDER_PRODUCTION',			'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_PRODUCTION',							null	);

INSERT INTO	ModifierArguments
		(ModifierId,								Name,					Value			)
VALUES	('REDANIA_INTERNATIONAL_TRADE_COMMERCIAL_HUB',	'YieldType',		'YIELD_GOLD'	),
		('REDANIA_INTERNATIONAL_TRADE_COMMERCIAL_HUB',	'Amount',			2				),
		('REDANIA_INTERNATIONAL_TRADE_MARKET',		'YieldType',			'YIELD_GOLD'	),
		('REDANIA_INTERNATIONAL_TRADE_MARKET',		'Amount',				2				),
		('REDANIA_INTERNATIONAL_TRADE_BANK',		'YieldType',			'YIELD_GOLD'	),
		('REDANIA_INTERNATIONAL_TRADE_BANK',		'Amount',				2				),
		('REDANIA_INTERNATIONAL_TRADE_STOCK_EXCHANGE',	'YieldType',		'YIELD_GOLD'	),
		('REDANIA_INTERNATIONAL_TRADE_STOCK_EXCHANGE',	'Amount',			2				),
		('REDANIA_INCOMING_TRADE_GAIN_GOLD',		'YieldType',			'YIELD_GOLD'	),
		('REDANIA_INCOMING_TRADE_GAIN_GOLD',		'Amount',				2				),
		('REDANIA_INCOMING_TRADE_GIVE_FOOD',		'YieldType',			'YIELD_FOOD'	),
		('REDANIA_INCOMING_TRADE_GIVE_FOOD',		'Amount',				2				),
		('REDANIA_ADJUST_BUILDER_EXTRA_CHARGE',		'Amount',				1				),
		('REDANIA_ADJUST_BUILDER_PRODUCTION',		'UnitType',				'UNIT_BUILDER'	),
		('REDANIA_ADJUST_BUILDER_PRODUCTION',		'Amount',				-20				);