-- UC_DIP_Text_CS_Ethiopia
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
UPDATE LocalizedText SET Text = REPLACE(Text, 'Consulate', 'Tier 1 Diplomatic Quarter building')
WHERE Tag IN	(
				'LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS_ALT',
				'LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_AGRICULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_CONSULAR_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_ENTERTAINMENT_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_BONUS'
				);

UPDATE LocalizedText SET Text = REPLACE(Text, 'building building', 'building')
WHERE Tag IN	(
				'LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS_ALT',
				'LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_AGRICULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_CONSULAR_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_ENTERTAINMENT_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_BONUS'
				);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Chancery', 'Tier 2 Diplomatic Quarter building')
WHERE Tag IN	(
				'LOC_CSE_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS_ALT',
				'LOC_CSE_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_AGRICULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_CONSULAR_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_ENTERTAINMENT_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_MARITIME_TRAIT_LARGE_INFLUENCE_BONUS'
				);

UPDATE LocalizedText SET Text = REPLACE(Text, 'building building', 'building')
WHERE Tag IN	(
				'LOC_CSE_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS_ALT',
				'LOC_CSE_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_AGRICULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_CONSULAR_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_ENTERTAINMENT_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_CSE_MARITIME_TRAIT_LARGE_INFLUENCE_BONUS'
				);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Chancery', 'Tier 2 Diplomatic Quarter')
WHERE Tag IN	(
				'LOC_CSE_SCIENTIFIC_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_BONUS_ALT',
				'LOC_CSE_CULTURAL_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_MILITARISTIC_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_INDUSTRIAL_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_AGRICULTURAL_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_CONSULAR_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_ENTERTAINMENT_TRAIT_LARGEST_INFLUENCE_BONUS',
				'LOC_CSE_MARITIME_TRAIT_LARGEST_INFLUENCE_BONUS'
				);
--------------------------------------------------------------