INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		32,			1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_32.dds'),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		38,			1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_38.dds'),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		50,			1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_50.dds'),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		80,			1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_80.dds'),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		128,		1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_128.dds'),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE',		256,		1,				1,				'ICON_BUILDING_PHANTA_NAGOYA_CASTLE_256.dds'),

		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',						256,	 	1,				1,				'ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_256.dds'	),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',						64,	 		1,				1,				'ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_64.dds'	),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',						50,	 		1,				1,				'ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_50.dds'	),
		('ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',						38,	 		1,				1,				'ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_38.dds'	);

INSERT INTO IconTextureAtlases
		(Name,										Baseline,	IconSize,	IconsPerRow,	IconsPerColumn,		Filename)
VALUES  ('ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',		6,			22,	 		1,				1,					'ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_22.dds');


--------------------------------------------------------------
-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,										Atlas,											'Index')
VALUES	('ICON_BUILDING_PHANTA_NAGOYA_CASTLE',		'ICON_ATLAS_PHANTA_NAGOYA_CASTLE',				0),
		('ICON_BUILDING_PHANTA_NAGOYA_CASTLE_FOW',	'ICON_ATLAS_PHANTA_NAGOYA_CASTLE',				0),
		('ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI',				'ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',			0),
		('ICON_RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_FOW',			'ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',			0),
		('RESOURCE_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI',						'ICON_ATLAS_PHANTA_NAGOYA_CASTLE_GOLDEN_SHACHI_RESOURCE',			0);
		
--------------------------------------------------------------