INSERT INTO IconTextureAtlases
		(Name,											IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		32,			1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_32.dds'),
		('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		38,			1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_38.dds'),
		('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		50,			1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_50.dds'),
		('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		80,			1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_80.dds'),
		('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		128,		1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_128.dds'),
		('ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',		256,		1,				1,				'ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,												Atlas,										'Index')
VALUES	('ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE',		'ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',	0),
		('ICON_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_FOW',	'ICON_ATLAS_PHANTA_BRONZE_BIRD_TERRACE',	0),
		('ICON_GREATWORK_PHANTA_CAO_ZHI_1',					'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_CAO_ZHI_2',					'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_CHEN_LIN_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_CHEN_LIN_2',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_WANG_CAN_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_WANG_CAN_2',				'ICON_ATLAS_GREATWORKS',					0);
--------------------------------------------------------------