/*
	Civilization Text Entries ko_KR
	Author: RapidGG
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
	
*/
INSERT OR REPLACE INTO LocalizedText
			(Language, Tag, Text)
VALUES

-----------------------------------------------
-- Civilization
-----------------------------------------------
	('ko_KR',	'LOC_CIVILIZATION_IPG_NILFGAARD_NAME',			'닐프가드'			),
	('ko_KR',	'LOC_CIVILIZATION_IPG_NILFGAARD_DESCRIPTION',	'닐프가드 제국'	),
	('ko_KR',	'LOC_CIVILIZATION_IPG_NILFGAARD_ADJECTIVE',  	'닐프가드의'			),
-----------------------------------------------
-- Civilization Unique Ability
-----------------------------------------------
	('ko_KR',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME',				'지방 행정'				),
	('ko_KR',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION',	
	'외국의 도시를 점령하면 해당 도시에 무료 건설자 유닛이 부여됩니다. 건설자는 건설 횟수를 소모하여 모든 특수지구의 건설에 필요한 [ICON_Production] 생산력 15%를 제공할 수 있습니다. 점령된 도시에 산출량 페널티가 없습니다. 스파이 유닛이 가능한 모든 진급 중에서 선택할 수 있습니다.'	),
-----------------------------------------------
-- Civilization Unique Infrastructure (District)
-----------------------------------------------
	('ko_KR',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',				'닐프가드 제국군 주둔지'								),
	('ko_KR',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',
	'주둔지 특수지구를 대체하는 닐프가드 군사 특수지구입니다. 건설 비용이 훨씬 저렴하고 해당 도시에 충성심 +2를 제공합니다. 닐프가드 제국군 주둔지에 배치된 시민마다 [ICON_Science] 과학 +1, [ICON_Culture] 문화 +1를 제공합니다. 해당 도시에서 훈련된 모든 지상 유닛이 얻는 전투 경험치가 25% 증가합니다.'	),

	('ko_KR',	'LOC_ABILITY_IMPERIAL_CAMP_TRAINED_UNIT_XP_DESCRIPTION',	'닐프가드 제국군 주둔지에서 경험치 +25% 획득'	),
-----------------------------------------------
-- Civilization Unique Unit
-----------------------------------------------
	('ko_KR',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',	'나우지카 여단'	),
	('ko_KR',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',	 
	'강력한 닐프가드의 고유 중세 시대 중기병 유닛입니다. 훈련과 유지 비용이 높지만 [ICON_Movement] 이동력이 충분히 남아있으면 공격 횟수 +1을 획득합니다.'	),

	('ko_KR',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_NAME',	'마그네 사단'	),
	('ko_KR',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_DESCRIPTION',
	'척후병을 대체하는 닐프가드 고유의 중세 시대 정찰 유닛으로 훈련 및 유지 비용이 매우 저렴합니다. 원거리 유닛이며 적의 통제 지역을 무시합니다. 우호적 영토에서 4타일 이상 떨어져 있을 때 [ICON_Strength] 전투력이 +10 증가하고 전투에서 승리 시 [ICON_Science] 과학 및 [ICON_CULTURE] 문화가 생성됩니다.'	),

	('ko_KR',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',	'화염중전갈'	),
	('ko_KR',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',	 
	'사석포를 대체하는 닐프가드의 고유 르네상스 시대 공성 유닛입니다. 화약 기술 개발 시 해금되며 훈련 비용이 저렴합니다.'	),

	('ko_KR',	'LOC_ABILITY_EMHYR_NAUZICAA_BRIGADE_EXTRA_ATTACK_DESCRIPTION',		'[ICON_Movement] 이동력이 남아있다면 공격 횟수 +1'	),
	('ko_KR',	'LOC_ABILITY_CALVEIT_MAGNE_DIVISION_DESCRIPTION',			'우호적 영토에서 4타일 이상 떨어져 있을 때 [ICON_Strength] 전투력이 +10 증가하고 전투에서 승리 시 [ICON_Science] 과학 및 [ICON_CULTURE] 문화를 생성'	),

	('ko_KR',	'LOC_CALVEIT_MAGNE_DIVISION_AWAY_STRENGTH',		'우호적인 영토 바깥에서 +{1_Amount}'	),
-----------------------------------------------
-- Mountains
-----------------------------------------------
	('ko_KR',	'LOC_NAMED_MOUNTAIN_TIR_TOCHAIR',		'티르토차이르산맥'	),
	('ko_KR',	'LOC_NAMED_MOUNTAIN_AMELL',				'아멜산맥'			),
	('ko_KR',	'LOC_NAMED_MOUNTAIN_FIERY',				'화염산맥'	),
-----------------------------------------------
-- Rivers
-----------------------------------------------
	('ko_KR',	'LOC_NAMED_RIVER_ALBA',				'알바강'				),
	('ko_KR',	'LOC_NAMED_RIVER_VELDA',			'벨다강'				),
	('ko_KR',	'LOC_NAMED_RIVER_SYLTE',			'실테강'				),
	('ko_KR',	'LOC_NAMED_RIVER_YELENA',			'옐레나강'			),
	('ko_KR',	'LOC_NAMED_RIVER_WAGTAIL',			'와그테일강'			),
	('ko_KR',	'LOC_NAMED_RIVER_BLESSURE',			'블레슈어강'			),
	('ko_KR',	'LOC_NAMED_RIVER_SANSRETOUR',		'산스레토르강'		),
-----------------------------------------------
-- Deserts
-----------------------------------------------
	('ko_KR',	'LOC_NAMED_DESERT_KORATH',				'코라스 사막'				),
	('ko_KR',	'LOC_NAMED_DESERT_ZERRIKANIAN',			'제리카니아 사막'		),
-----------------------------------------------
-- Lakes
-----------------------------------------------
	('ko_KR',	'LOC_NAMED_LAKE_MUREDACH',				'뮤레다흐 호수'				),
	('ko_KR',	'LOC_NAMED_LAKE_TARN_MIRA',				'타른미라 호수'				),
-----------------------------------------------
-- Cities
-----------------------------------------------
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_1',  '닐프가드'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_2',  '뷘네부르크'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_3',  '다른 루아흐'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_4',  '다른 로완'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_5',  '다른 임라크'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_6',  '비롤레다'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_7',  '파르티아'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_8',  '스티가'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_9',  '아마릴로'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_10',  '테르가노'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_11',  '다른 디프라'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_12',  '로크 그림'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_13',  '에이돈'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_14',  '라 포인테'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_15',  '바카와'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_16',  '카르키브'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_17',  '살름'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_18',  '클레르몬트'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_19',  '투른'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_20',  '네인로이스'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_21',  '코르보'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_22',  '유니코른'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_23',  '단 데르'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_24',  '말훈'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_25',  '파노'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_26',  '쟐루시'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_27',  '두드노'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_28',  '포르게암'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_29',  '티피'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_30',  '드루아이'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_31',  '글리스웬'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_32',  '뉴 포르지'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_33',  '로레도'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_34',  '사라비스타'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_35',  '베데트'),
	('ko_KR',	'LOC_CITY_NAME_IPG_NILFGAARD_36',  '단 데르'),
-----------------------------------------------
-- Citizens
-----------------------------------------------
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_1',	'페르구스'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_2',	'티보르'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_3',	'브렘데'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_4',	'스위이스'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_5',	'바티에르'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_6',	'모르타이젠'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_7',	'피슨'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_8',	'토레스'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_9',	'실라르드'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_10',	'스테판'	),

	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_1',	'카르티아'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_2',	'글리니스'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_3',	'올라'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_4',	'신티아'),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_5',	'이스벨'		),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_6',	'안나'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_7',	'프린질라'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_8',	'실비아 안나'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_9',	'비비엔'	),
	('ko_KR',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_10',	'아시리'	),
-----------------------------------------------
-- Info
-----------------------------------------------
	('ko_KR',	'LOC_CIVINFO_IPG_NILFGAARD_LOCATION',		'야루가강 이남 대륙 전 지역'		),
	('ko_KR',	'LOC_CIVINFO_IPG_NILFGAARD_SIZE',			'약 250만 km²'	),
	('ko_KR',	'LOC_CIVINFO_IPG_NILFGAARD_POPULATION',		'약 4500만 명'		),
	('ko_KR',	'LOC_CIVINFO_IPG_NILFGAARD_CAPITAL',		'닐프가드, 황금탑의 도시'		),
-----------------------------------------------
-- Civilopedia
-----------------------------------------------
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_1',		
	'닐프가드 제국 (제국어로 Ceas''raet)는 세계 역사상 가장 강력한 제국입니다. 제국은 대륙 남부에 위치하고 있으며 번영하는 경제와, 유능한 지휘관과 함께 강력하고 잘 훈련된 군대를 자랑합니다. 제국은 주로 지금은 속주가 된 외국의 정복을 통해 국경을 확장하였습니다. 제국의 주민들은 "진정한" 닐프가드인은 수도에서 태어난 사람들일 뿐이며 정복된 지역에서 태어난 사람은 아니라고 믿습니다.'),	
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_2',		
	'속주는 섭정 또는 왕에 의해 다스려집니다(왕이 자발적으로 항복하는 경우, 해당 지역 왕위는 유지하나 황제에게 종속되거나 가신임). 제국은 에미르 바 엠레이스 황제의 통치 기간 수년에 걸쳐 북쪽 야루가강까지 영토를 뻗어 확장되었습니다.'),	
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_3',	
	'북부 왕국에서 제국은 압도적인 적수로 묘사되며, 북부의 많은 자유인들은 제국에 대한 증오를 노골적으로 표현합니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_4',	
	'국가 상징'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_5',	
	'태양빛과 뜨거운 열을 상징하는 위대한 태양(Great Sun)은 닐프가드 사람들의 주요 상징입니다. 제국 문장, 주화, 군대의 깃발, 비롤레단 도공의 표식 등에 나타납니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_6',	
	'역사'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_7',	
	'닐프가드인들은 제국의 역사가 2세기까지 거슬러 올라간다고 믿습니다. 최초의 정착민들은 검은 쉐이드(Black Seidhe)라 불리우는 아엔 쉐이드 엘프의 한 지파와 혼합되어 엘프 언어, 신념, 관습과 문화로 주로 구성된 국가를 만들었습니다. 한편, 알바 지방의 흩어진 정착지에 거주하는 용감한 목자들은 주변 국가들을 천천히 통합하여 문화, 기술 및 군사 전략과 같은 그들의 장점을 활용, 안전과 질서를 제공했습니다. 이 두 집단은 이웃 국가의 정복과 자유 기간 동안 병함되어 엘프, 비코바로인, 에톨리아인 및 여러 알바인 부족의 특성을 혼합한 독특한 유산을 일궈냈습니다. 이러한 역사의 흐름 속 어느 시점에, 닐프가드 왕국이 세워졌습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_8',	
	'군주는 상원으로 알려지게 된 고문 위원회의 조언을 받았습니다. 시간이 흐르자 상원은 점점 더 많은 권한을 획득하여 입법 기관이 되었습니다. 이 기간 동안 닐프가드의 영향력이 확대되기 시작했고 이웃 땅은 서서히 닐프가드화되었으며 제국의 지배 아래에 들어간 사람들은 "강철의 외교"를 통해 공식 언어를 배우고 제국 문화를 받아들이게 되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_9',	
	'결국, 저지 알바 외부의 두 영역이 자발적으로 또는 강제로 제국에 통합되었습니다. 임페라토르(황제 폐하)라는 칭호는 처음에 군대의 총사령관을 지칭하는 단어로 등장했습니다. 해당 기간동안 병합된 땅은 로완과 임라크, 루아흐, 데를란, 마그네, 뷘네부르크가 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_10',	
	'12세기 초 황제 토레스 바 엠레이스가 상원을 타도하고 절대 권력을 장악했습니다. 처음에 그는 닐프가드의 영역을 "왕국"이라고만 불렀지만 그의 후기 통치 기간 동안 "제국"이라는 용어가 만들어졌고 황제라는 칭호가 쓰이기 시작했습니다. 토레스는 3월 8일 칙령을 통해 위대한 태양(Ard Feainn)교를 제국의 국교이자 문장으로 채택했습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_11',	
	'토레스가 사망한 후 1200년대 초반에, 퍼거스 바 엠레이스가 즉위했습니다. 그러나, 많은 사람들은 그를 유약한 황제로 여겼습니다. 1216년, 퍼거스 바 엠레이스는 에톨리아 왕국을 제국의 적에 대한 처분의 본보기로 삼고자 했습니다. 닐프가드 군대는 에톨리아 왕국을 공격하고 압도하여 권력 구조를 붕괴시키고 에톨리아인의 삶을 정의하는 가치를 무참히 파괴했습니다. 동일한 해에 퍼거스는 게메라 왕국도 복종시켰습니다. 비코바로 왕국의 귀족들은 왕권에 압력을 행사하여 닐프가드에 자발적으로 병합될 것을 요청했습니다. 그러나 1233년, 찬탈자(Usurper)에 의해 쿠데타가 일어나 왕권이 전복됐습니다. 쿠데타 동안 퍼거스는 찬탈자에게 살해되었고 그의 아들이자 상속자인 에미르는 찬탈자의 부하 마법사 브레덴스의 저주를 받아 인간형 고슴도치로 변했습니다. 그를 감시하는 사냥개들을 피해 에미르는 탈출에 성공했고 지인들의 도움으로 제국을 떠났습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_12',	
	'찬탈자의 통치 기간 동안 그는 국가 사면 기간을 선언하고, 위대한 태양교의 권한을 축소시켰으며, 1239년 에빙을 합병했습니다. 이 긴 전쟁 동안 메티나, 나자이르, 그리고 메흐트까지 1250년대 중반 제국에 흡수되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_13',	
	'1257년 아르달 아엡 다히, 빌제포츠와 에미르의 지지자들의 황궁 습격으로 찬탈자가 살해되었습니다. 조국에서 도망쳤던 적통 왕위 계승자인 에미르 바 엠레이스는 닐프가드 황궁에 입성하여 새로운 황제가 되었습니다. 그는 "적들의 무덤 위에서 춤추는 하얀 불꽃", 닐프가드어로 "Deithwen Addan yn Carn aep Morvudd"라는 별명을 얻게 되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_14',	
	'사회'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_15',	
	'제국은 여러 다른 문화와 국가로 구성되어 있지만 당국은 소수 민족들의 점진적 "닐프가드화"에 초점을 맞추고 있습니다. 이것은 지역 가치와 관습을 저지 알바인들의 유산인 "닐프가드인의 덕목"의 가치와 관습으로 대체하는 것입니다. 제국 국경 지역 주민의 내륙 이주를 권장합니다: 문제가 많은 지방에 저지 알바인 정착민들의 식민지가 설립되는 반면, 제국에 충성하는 닐프가드인이 아닌 농민들은 매력적인 제안을 통해 새로 정복된 지역에 정착하도록 권장합니다; 제국에 반기를 드는 지역은 "문제가 있는" 것으로 간주되어 노예화 또는 인종 청소를 통해 정화합니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_16',	
	'반면에 닐프가드 제국은 일반적으로 비인간 종족에게 있어 대부분의 북부 왕국보다 안전한 곳으로 인식됩니다. 우드엘프와 같은 종족을 제외한 제국에 살고 있는 비인간 종족은 제국 시스템을 가혹하지만 정의로운 것으로 간주합니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_17',	
	'비고'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_18',	
	'닐프가드는 역사 속 로마 제국과 많은 유사점을 지니고 있습니다: 규율있는 군대를 통한 정복을 통해 다른 "야만인" 문화를 동화시키는 강력한 제국입니다. 또한 (자신들이 모두 고대혈통(Lara Dorren)의 후손이라고 믿고 싶어하는) 귀족들과 가신들 사이에 우월감을 느끼는 것도 비슷합니다. 닐프가드인들의 위대한 태양교 숭배는 로마 제국의 Sol Invictus(무적의 태양신) 숭배와 유사합니다. 게다가 위쳐 2의 1장 퀘스트 설명 중 단델라이온의 "닐프가드에서는 닐프가드의 법을 따르라"는 문구는 흔히 인용되는 "로마에서는 로마법을 따르라"와 구조적으로 똑같은 형식을 갖고 있어 강한 암시를 하고 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_19',	
	'수도의 이름과 제국의 이름에 대한 기원은 불분명합니다. "닐프(Nilf)"는 아이슬란드어 "nifl(안개, 어둠, "Niflheim"에서와 같이)"에서 기원을 찾을 수 있는 반면 "가드(gaard)"는 네덜란드어 "gaard(마당, 정원)", 덴마크어 "gaard/gård(농장)", 고대 노르웨이어 "garðr(마당, 울타리)"에서 기원을 짐작할 수 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_20',	
	'닐프가드 군대의 갑옷 디자인은 색 구성과 디자인은 신성로마제국의 특정 부분, 특히 왕실 기사단의 갑옷을 연상시킵니다.'),
-----------------------------------------------
-- Unique Unit Civilopedia Entry
-----------------------------------------------
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_1',  	
	'나우지카는 "Skullhead(해골 머리)" 또는 "Death''s Head(망자의 머리)"로도 알려져 있으며 마르쿠스 브라이번트 소장이 지휘하는 닐프가드 기마 부대인 제4기병군의 여단이었습니다. 여단 자체는 키이스 반 로가 지휘했습니다. 기병대는 전쟁망치와 3.5피트 길이의 검을 갖췄습니다.'	),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_2',
	'나우지카는 데어라니언 제7기병여단과 함께 브레나 전투에 투입된 마지막 부대였습니다. 야전사령관 메노 코에훈이 이끄는 이 부대는 북부군을 꿰뚫고 적진 후방에서 공격해야 했습니다. 이러한 노력은 북부의 브로니보르 사령관 하의 경험없는 보병이 막대한 사상자를 내며 닐프가드 기병대를 저지하는 데 성공하여 무위로 돌아갔습니다. 이때부터 닐프가드의 패배는 불가피하고 신속했습니다.'),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_3',
	'비고'),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_4',
	'나우지카라는 이름은 호메로스의 오디세이아에 등장하는 스케리아 섬의 왕 알키노오스의 딸에서 유래했을 것입니다.'),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_5',
	'나우지카 여단의 별칭인 "Skullhead(해골 머리)"는 제2차 세계 대전 당시 독일군의 제3SS기갑사단 토텐코프의 해골단과 명칭이 유사합니다.'),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_6',
	'그들의 또다른 별칭인 "Death''s Heads(망자의 머리)"는 비슷한 색상의 제복과 휘장을 착용한 프로이센 제2호위경기병 토텐코프 후사르를 참조했을 가능성이 있습니다.'),
	
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_1',
	'마그네 사단은 마그네 출신의 사단으로, 마르쿠스 브라이반트 소장이 지휘하는 닐프가드 제4기병군 소속 사단입니다.'),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_2',
	'닐프가드 기병 장교가 전열에서 벗어날 경우 코라스 사막으로 배치될 가능성이 높습니다. 이 "프라이팬"의 끝없는 모래를 몇 달 동안 순찰하다 보면 그는 어떠한 기미의 불복종도 보이지 않을 것이며, 그 마음은 곧 코라스 사막으로 재배치되지 않도록 무엇이든 하겠다는 광적인 의지로 변모할 것입니다.'),

	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_1',  	
	'제리카니아의 화염중전갈은 닐프가드 제국의 주력 공성 병기입니다. 북부 왕국의 발리스타와 생김새는 유사하나 투창이 아닌 녹색 불덩어리를 쏜다는 점에서 차이가 있습니다.'	),
	('ko_KR',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_2',  	
	'이름에 오해의 소지가 있어 정교하게 설계된 파괴 병기보단 뚱뚱한 붉은 거미류(전갈이 거미강에 속합니다.)가 연상이 됩니다... 도시를 점령하는 목적보다 완전히 함락시키는 데에 적합합니다.'	),
-----------------------------------------------
-- Unique Infrastructure
-----------------------------------------------
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_1',
	'닐프가드 "중앙군" 주둔지는 위쳐 3의 벨렌 지역에 있는 닐프가드 군대의 본부입니다. 불과 2주 만에 건설된 "중앙군" 주둔지는 닐프가드의 우수한 공병 기술을 자랑합니다.'),
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_2',
	'닐프가드군'),
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_3',
	'닐프가드 제국의 제국군은 의심할 여지 없이 대륙에서 가장 잘 훈련된 전투 부대 중 하나입니다. 군대 내의 병졸에서 고위 장교에 이르기까지 특징인 검은 갑옷을 입은 병사들은 전투 기술에 능통합니다. 닐프가드 황제의 완전한 통제 아래 야전 원수 휘하의 고위 장교들은 작전을 수행합니다.'),
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_4',
	'북부 전쟁과 같은 큰 정복 전쟁과 침략 전쟁 동안 군대는 중앙군, 동부군 및 베르덴 작전군 등으로 분할되었습니다. 2차 북부 전쟁 동안 병력의 숫자는 약 32만 명이었습니다. 그 중 30만 병력은 침략 전쟁에 참전하고, 2만 병력은 제국 평화유지군으로서 핵심 지방을 방어했습니다.'),
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_5',
	'다른 많은 군대와 마찬가지로 제국군도 망고넬, 투석기, 화염중전갈 및 썩은 시체 투기병을 포함한 공성 병기를 보유하고 있습니다.'),
	('ko_KR',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_6',
	'북부 왕국과 달리 노예 제도는 닐프가드인들에게 익숙합니다; 일반적으로 전쟁 포로인 노예는 육체 노동뿐만 아니라 자유를 얻기 위해 주인에 의해 전쟁에 참전하기도 합니다.'),
-----------------------------------------------
-- City State
-----------------------------------------------
	-- METINNA
	('ko_KR',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',			'메티나'),
	('ko_KR',	'LOC_CITY_NAME_IPG_METINNA_MINOR',					'메티나'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_DESCRIPTION',	'메티나 도시 국가'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_ADJECTIVE',		'메티나의'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_NAME',		'메티나 종주국 보너스'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION',	'메티나 도시 국가의 종주국인 동안 훈련된 경기병 유닛은 "메티나 기병대" 능력을 영구적으로 부여받아 [ICON_Strength] 전투력 +4를 얻습니다. 또한 [ICON_RESOURCE_Wine] 와인 사치 자원의 무료 견본을 제공합니다.'),

	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_1',
	'메티나는 아멜 남쪽의 왕국 중 하나로, 현재는 닐프가드 제국의 속국이자 메티나 주의 일부에 속해있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_2',
	'역사'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_3',
	'이 땅의 원래 주민은 웨어버브족으로, 현재 메티나, 나자이르, 마그 투르가로 불리우는 지역을 고향으로 하는 세련된 인종이었습니다. 이주의 시대에 자신들만의 문명을 건설하기 시작한 엘프들에 의해 쫓겨났습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_4',
	'그들의 조상은 주로 백개의호수 또는 센틀로흐의 땅에 거주했습니다. 오늘날까지도 그들의 왕궁 유적에는 과거 엘프 유령이 출몰합니다. 가장 잘 알려진 건축물 중 하나는 13세기에는 흔적만이 남은 타른 미라의 북쪽 해안에 있는 토르 지라엘의 현무암탑입니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_5',
	'영토'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_6',
	'역사의 한 시점에서 인류가 이 땅에 정착했습니다. 두 개의 주요 무역 대도시인 메티나와 노인로이트가 설립되었습니다. 마침내 그들을 포함한 왕국이 건립됐고, 그 이름은 첫 번째 대도시에서 유래했습니다. 가장 유명한 메티나의 군주 중 하나는 지벨리나 여왕이였습니다. 그녀는 정령 룸플레스테의 도움으로 왕위를 얻었지만 의외성의 법칙을 거부당하여 왕관을 잃었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_7',
	'맥 데이라 평원은 벨다 삼각주에서 기원한 유목민 기병 마키족의 고향이 되었습니다. 그들은 이곳에 방대한 목장을 세우고 소와 유명한 메티나 조랑말을 기르기 시작했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_8',
	'닐프가드 전쟁'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_9',
	'12세기 후반에 메티나는 닐프가드의 동맹으로 전쟁에 참여하지만 북부 전쟁 중 13세기에 찬탈자의 통치가 있을 때까지 메티나와 이웃 국가는 닐프가드의 정복 아래 있지 않았습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_10',
	'소든 언덕 전투에서 닐프가드가 패한 뒤 얼마 후, 메티나인들은 반란을 일으켰습니다. 그러나 반란은 같은 해에 에미르 바 엠레이스가 소든 전투 이후 교체된 닐프가드군 하급 지휘관들에 의해서 진압당했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_11',
	'고용된 메티나 보병은 알데스버그의 첫 전투와 벤거버그 전투 때 닐프가드군으로 참전했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_12',
	'지형과 기후'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_13',
	'서쪽으로는 에빙(대해), 동쪽으로는 게소, 북쪽으로는 나자이르, 남쪽으로는 메티나 주를 형성하는 메흐트와 접합니다. 이 지역의 1/3이 맥 데이라 평야로 구성되어 있으며 북쪽은 옐레나, 남쪽은 실테강과 접해 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_14',
	'사회와 문화'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_15',
	'혹자는 찬탈자에 의해 정복된 국가들 사이에서 메티나인들은 저지 알바인들과 가장 유사하다고 말합니다. 그들은 숙련된 상인이자 거친 기병대입니다; 마키족의 영향으로, 마티네인들은 말의 안장 위에서 태어난다는 전설이 있습니다. 평원의 거주자들은 도시민들보다 거친 성격을 갖고 있습니다; 맥 데이라 출신 레슬러들은 종종 메티나의 다소 비위생적인 경기장에서 볼 수 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_16',
	'경제'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_17',
	'메티나의 수입 대부분은 대도시를 중심으로 한 무역에서 나옵니다. 내력의 맥 데이라 평원에는 소와 메티나 조랑말을 기르는 광대한 목장이 있습니다. 메티나 조랑말은 희고 강건하며 튼실한 하체를 갖고 있고 지능적입니다 - 당연하지만 말을 묘사하는 겁니다. 메티나 조랑말은 벨다 삼각주의 마키족에 의해 들어왔다는 설이 유력합니다. 메티나의 왕이 닐프가드에게 바치는 공물은 주로 말과 기병입니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_18',
	'메티나는 메티나 로제로 알려진 와인으로 유명합니다. 감정가들에게 훌륭하다고 묘사되는 이 와인은 풍부한 부케를 가진 테이블 와인입니다. 마키족과 마찬가지로 벨다 삼각주의 와이너리에서 유래했으나 메티나로 옮겨져 메티나인들이 자랑스러워하는 국민 음료가 되어 투생인들과 결투를 벌이는 이유가 되곤 했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_19',
	'메티나는 대륙에서 만들어진 가장 가볍고 날카로운 기병 검인 에스보다 칼을 생산합니다.'),

	('ko_KR',	'LOC_ABILITY_METINNA_CAVALRYMEN_NAME',			'메티나 기병대'),
	('ko_KR',	'LOC_ABILITY_METINNA_CAVALRYMEN_DESCRIPTION',	'영구적 [ICON_Strength] 전투력 +4'),
	
	-- MAECHT
	('ko_KR',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',			'메흐트'),
	('ko_KR',	'LOC_CITY_NAME_IPG_MAECHT_MINOR',					'메흐트'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_DESCRIPTION',	'메흐트 도시 국가'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_ADJECTIVE',		'메흐트의'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_NAME',		'메흐트 종주국 보너스'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION',	'Spies executing the "Fabricate Scandal" espionage mission function 3 levels higher.'),

	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_1',
	'메흐트는 대륙의 남쪽에 있는 왕국으로 북쪽으로는 메티나, 동쪽으로는 게소, 남쪽으로는 에빙과 접해있습니다. 1250년대에 닐프가드에게 합병되었고 찬탈자의 재위 기간 동안 메티나 지방의 일부가 되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_2',
	'메흐트는 선거가 사실상 닐프가드 황제의 결정에 달려 있음에도 불구하고 시민들이 왕을 선출하는 자치권을 유지합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_3',
	'역사'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_4',
	'아케르스파크 왕은 1258년 암살자의 칼에 찔린 후 급성 폐렴으로 사망할 때까지 메흐트가 닐프가드에게 정복된 후에도 계속 통치했습니다. 즉위한지 1년이 된 에미르 황제에게 코드링게르가 메흐트 왕좌에 대한 투표를 제안하지만 결과는 호에트의 승리로 끝났습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_5',
	'권력의 불안정함을 감지한 뤼디거 공작과 메흐트 귀족들은 투른에서 반란군을 모집했지만 곧 징벌 원정에서 게메라 평화 유지군에 의해 진압되었습니다. 1267년까지 메흐트는 제국에 완전히 귀속되었고 메흐트의 용병들은 제2차 북부 전쟁에 참여했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_6',
	'NOTES'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_7',
	'듀니는 메흐트 사람들이 매우 미신적이라고 주장했지만, 파베타와 결혼한 직후 고향으로 돌아가고 싶지 않은 이유를 설명하기 위한 임기응변일 가능성이 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_8',
	'Time of Contempt의 폴란드 본편에는 메흐트 왕국의 문장에 대해 모호한 설명이 쓰여있으며 "방패에 은색 물고기와 왕관이 4등분되어 파란색과 빨간색으로 구분됨"이라고 설명해놓았습니다. 더 자세한 설명은 영문 번역판 번역가인 David French가 제공했습니다.'),
	
	-- TOUSSAINT
	('ko_KR',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME',			'투생'),
	('ko_KR',	'LOC_CITY_NAME_IPG_TOUSSAINT_MINOR',					'보끌레흐'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_DESCRIPTION',	'투생 도시 국가'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_ADJECTIVE',		'투생의'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_NAME',		'투생 종주국 보너스'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION',	'사치 자원 위의 재배지에 [ICON_Culture] 문화 +3을 부여합니다. [ICON_RESOURCE_Wine] 와인 사치 자원 위의 재배지에 [ICON_Culture] 문화 +5를 부여합니다.'),

	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_1',
	'투생은 닐프가드 제국 아래 작은 자치 공국으로서, 화산토와 적절한 일조량, 강수량의 조합으로 생산되는 와인 특산품으로 유명합니다. 투생은 대규모 상비군을 유지하지 않고, 공국 경비대와 투생 기사단에 치안을 의존합니다. 투생은 대륙에 몇 안 되는 첩보기관이 없는 나라 중 하나입니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_2',
	'투생은 닐프가드의 속국임에도 불구하고 높은 수준의 자치권을 유지하고 있으며, 제국도 투생의 내정에 대해 간섭하거나 군사적 행동을 하는 경향은 거의 없습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_3',
	'투생 공국은 표면상 동화에 나올 법한 나라라고 보일 수 있지만 와인 저장고 아래에 있는 고대 광산 입구, 광산과 지하 감옥, 용암류로 발생한 동굴과 터널로 연결되는 거대한 지하 통로들이 숨겨져 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_4',
	'선사 시대와 고대 시대'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_5',
	'오랜 세월 동안 투생의 지하에는 코르드, 킬물리제, 프리스키르닉과 같은 지능적인 생명체가 서식했으며, 그 중 일부는 13세기까지 위쳐 교본에도 알려지지 않았습니다. BR(부활 이전) 8세기 아엔 쉐이드 엘프족들이 보끌레흐를 수도로 하여 흰 대리석과 상아로 이루어진 아름다운 왕국을 건설했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_6',
	'인류 출현'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_7',
	'개척 후 20년 후, 엘프 왕 디베타프 재위 기간 중 북부인들의 족장 루도비크가 이끄는 침공에 직면했습니다. 781년 엘프들은 결국 도시를 버리고 아멜산맥으로 떠났고 짐을 제외한 모든 것들을 불태웠고, 그렇지 못한 것에게는 저주를 퍼부었습니다. 루도비크의 군대는 산기슭으로 진군하여 디베타프의 항복과 루도비크를 왕으로 추대할 것을 요구했습니다. 요구가 거절되자 치열한 전투가 계속되었지만 아엔 쉐이드 엘프가 패했으며, 디베타프는 항복을 선언했습니다. 이듬해 인간은 고르곤 산기슭에서의 학살과 승리에 대한 기념일을 지정하기로 했습니다. 인간의 손길이 닿지 않은 마지막 엘프의 흔적은 티르 나 비 아라인의 숨겨진 묘지였으며 이후 시대에도 아엔 세브헤른의 보호를 받아 유지되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_8',
	'이어진 역사에서, 초기 투생의 주요 산업은 광업이었고, 많은 광산을 일궈냈습니다. 이 시기에 정적들을 구금하기 위한 지하 감옥들도 건설되었습니다. - 투생의 영토는 여러 영주와 공작들에게 분배되었습니다. 영주들 중 한 명인 에피체아는 디베타프가 패했던 고르곤 산기슭 주위 영지를 받았습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_9',
	'이 기간 가장 중요한 지형적 변화로는 나자이리 출신 아담 공작이 상레투르강의 흐름을 바꾸려다 예기치 않게 발생한 상레투르 습지가 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_10',
	'개혁'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_11',
	'12세기에 헨리 3세 공작은 투생 최초의 개혁을 시작했습니다. 그는 머나먼 저지 알바의 문명에 감탄하여 형법 개정을 통해 왕국을 문명화하려고 시도했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_12',
	'동세기 중반에 왕권은 아델라 마르타 공작 부인에 의해 크게 강화되었습니다. 그녀는 엘프 양식의 수도 궁전의 개조를 명령하고 왕궁을 그곳으로 옮겨 보끌레흐 도시를 건립했습니다. 그녀는 공국의 기사도 전통을 싹을 틔우게 한 수많은 구혼자들 중 적합한 이를 가리는 토너먼트를 조직하여, 그녀가 남성의 덕목에서 높게 평가하는 자질인 힘, 용기, 지혜를 시험했습니다. 남쪽으로 여행하던 공작 부인은 닐프가드의 황제 토레스의 막내 아들을 만나 결혼하여 투생과 닐프가드 제국 사이에 유대감을 형성했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_13',
	'아델라 마르타의 딸인 캐롤리나 로베르타는 개혁을 지속했습니다. 그녀는 투생의 축제 기간 동안 뾰족한 칼을 이용하여 이빨을 뽑는 관습이 야만적이라 생각하여 금지시켰습니다. 그녀는 또한 생 플레그문드가 들여온 레비오다 숭배를 공식적으로 인정한 사람이기도 합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_14',
	'13세기'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_15',
	'투생 공국은 카로베르타의 손녀 안나 헨리에타(별칭 아나리에타)가 라문트 공작과 결혼한 1258년부터 라문트 공작의 통치 아래 있었습니다. 원래 그녀의 남편이 통치자였음에도 불구하고 가신들은 그녀에게 높은 충성심을 보였습니다. 1265년 라문트 공작이 사망한 이후 아나리에타는 감정적 불안정을 이유로 참모들에 의해 세상과 단절되었으며, 1267년 후기에 되어서야 게롤트의 한자동맹(시리의 수색 및 구출을 목적으로 결성한 집단 - 게롤트, 단델라이온, 밀바, 카히르, 레지스, 앙굴렘이 포함됨)의 정보로 제2차 북부전쟁의 발발을 알게 되었고, 분노한 아나리에타는 장관 트렘블레이에게 반역죄를 적용, 탑에 구금했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_16',
	'지형과 기후'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_17',
	'투생은 아멜산맥, 티르 토차이르산맥 및 화염산맥 세 산맥 사이에 위치해 있습니다. 과거 재해로 남겨진 화산토는 포도나무 재배지를 건설하기에 적합했습니다. 화산폭발로 인한 용얌류에 의해 형성된 동굴로 공국은 지하 감옥과 통로 시스템을 형성했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_18',
	'사회'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_19',
	'공국의 고지대에는 주로 북부 민족 출신의 사람들이 거주합니다. 저지대는 13세기까지 거주자의 신원파악이 이뤄지지 않았으며, 그렘린, 킬물리제, 코르드, 프리스키르닉, 뱀파이어 및 아직 과학적으로 규명되지 않은 여러 종들이 거주하고 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_20',
	'문화'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_21',
	'전통은 투생에서 신성시됩니다. 특히 공휴일인 와인 통(Wine Vat)절은 그들에게 있어서 가장 중요한 날입니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_22',
	'경제'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_23',
	'과거에 투생은 광업이 주산업이었습니다. 그러나 12세기 중반 이후로, 공국 경제는 와인 산업이 중추가 되었고 폐쇄된 광산은 괴물들의 서식지가 되어가고 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_24',
	'비고'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_25',
	'투생은 "All Saints'' Day"의 프랑스어입니다. 프랑스 북부 오트노르망디의에 위치한 코뮌의 이름이기도 합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_26',
	'위쳐 3 블러드 앤 와인 확장팩에서 투생의 주민들이 때때로 프랑스어를 사용하는 것을 볼 수 있습니다. 문법에도 프랑스어가 포함됩니다; 이탈리아산 와인인 에스트에스트("is is-이다 이다"의 라틴어)를 "Était Était"라고 희화화시켜 말합니다. 프랑스어로 "was was-이었다 이었다"라는 뜻입니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_27',
	'보끌레흐의 건축양식은 폴란드의 도시 자모스크(Zamość)의 매너리즘 건축양식에서 비롯됐습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_28',
	'투생의 문화는 이탈리아, 스페인, 남부 프랑스와 같은 지중해 지역의 문화에서 참고했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_29',
	'공국 경비대가 착용하는 투구는 스페인의 모리온 투구와 형태가 같습니다.'),
	
	-- GEMMERA
	('ko_KR',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',			'게메라'),
	('ko_KR',	'LOC_CITY_NAME_IPG_GEMMERA_MINOR',					'게메라'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_DESCRIPTION',	'게메라 도시 국가'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_ADJECTIVE',		'게메라의'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_NAME',		'게메라 종주국 보너스'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION',	'자유 도시 유닛을 상대로 [ICON_Strength] 전투력 +5를 제공합니다. 주둔군이 있는 도시에 턴당 충성심 +2를 부여합니다.'),

	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_1',
	'게메라 또는 게메리아는 과거 왕국이었으나 닐프가드의 속주로 편입되었습니다. 게메라 평화 유지군과 같은 용맹한 전사들로 유명했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_2',
	'오랜 세월에 걸쳐, 북부의 지도 제작자들은 게메라가 대륙의 최남단 지역이고 그 아래의 땅은 다른 대륙에 속한다고 주장했지만, 대부분의 사람들은 게메라가 아닌 에빙을 최남단 지역이라고 믿었습니다. 그러나 2차 북부 전쟁 당시 이러한 믿음은 버려졌습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_3',
	'고대 역사'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_4',
	'오래 전, 게메라의 해안지역에는 바람의 탑을 근거로 엘프족이 살았다는 것을 알 수 있습니다. 언덕 지역에는 고대 대장간, 주조소와 함께 적어도 하나의 드워프 광산이 존재했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_5',
	'사납고 야만적인 주민들이 살던 게메라 왕국은 오랜 세월 동안 이웃 국가들에게 골칫거리였습니다. 토레스 황제 재위 기간 동안 닐프가드 제국에 대한 게메라인들의 침공이 적어도 한 번은 있었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_6',
	'12세기 후반에 게메라는 닐프가드 제국의 막강한 영향력에 직면했습니다. 게메라의 폰데릭 공작은 닐프가드군을 만에 몰아넣는데까지 성공했으나, 그가 살해한 전 공작인 형 워데릭의 아들과 살쾡이 교단 위쳐 드래곤플라이에 의해 폐위되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_7',
	'닐프가드의 속주'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_8',
	'게메라는 마침내 1226년 황제 퍼거스 바 엠레이스에 의해 정복당했습니다. 게메라의 풍부한 디메리티움 광산지에 현혹된 황제는 에돌리아와 비코바로의 군대와 함께 침략하여 자원을 독차지하는데 성공하고, 게메라의 염소를 기르는 몇몇 방랑자들을 제외하고는 광산지에 있는 대부분의 인구를 뿌리 뽑았습니다. 게메라 정복 후 용맹한 게메라 전사들은 전리품과 싸움을 위해 제국 군대에 합류했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_9',
	'게메라인 마법사들은 황실에 본인들을 등록하기를 꺼려했습니다. 이 문제로 찬탈자와 이사이아 코에후른은 마법사 사냥꾼이라는 조직을 만들었습니다. 그들은 등록되지 않은 마법사를 색출해 수도로 압송하여 재판을 받게 했습니다. 마법사 사냥꾼 조직에 필요한 장비를 갖추기 위해 황제는 제국의 거물 광산 소유자들을 불러모아 가장 큰 디메리티움 광산을 발견하는 자에게 독점 계약을 할 것을 제안했습니다. - 그리고 그러한 광산들은 게메라에서만 찾을 수 있었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_10',
	'지형과 기후'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_11',
	'게메라는 해안 지역, 숲, 초언 및 건조하고 바위가 많은 언덕 지역으로 나뉘어집니다. 대도시나 큰 도로는 없지만, 잘 정비된 비포장도로를 통해 연결된 일련의 마을이 존재합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_12',
	'사회'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_13',
	'야만적인 습성에도 불구하고, 게메라는 왕과 공작으로 구성된 군주제를 채택했으며, 마법사와 드루이드가 고문으로 있는 법원도 있었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_14',
	'주민들은 친절하고 성실하지만 동시에 폭력적이고 잔인합니다. 그들은 열정과 사랑으로 종마를 타고 질주하는 위대한 기수들입니다. 희생자의 가족 앞에서 벌이는 잔혹한 집단 강간 행위를 "게메라인 방식으로 노는 것"이라고 부르는 잔혹한 속담도 존재합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_15',
	'경제'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_16',
	'게메라는 감자, 그레이비, 단단한 치즈 생산지로 유명합니다. 풍부한 디메리티움 매장지가 발견된 언덕 지역에는 제국 광산들이 설립되었습니다.'),

	('ko_KR',	'LOC_GEMMERIAN_PACIFIERS_NAME',			'게메라 평화 유지군'),
	
	-- VICOVARO
	('ko_KR',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',			'비코바로'),
	('ko_KR',	'LOC_CITY_NAME_IPG_VICOVARO_MINOR',					'비코바로'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_DESCRIPTION',	'비코바로 도시 국가'),
	('ko_KR',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_ADJECTIVE',		'비코바로의'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_NAME',		'비코바로 종주국 보너스'),
	('ko_KR',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION',	'모든 대학교 건물마다 [ICON_Science] 과학 +2와 [ICON_GreatScientist] 위대한 과학자 점수 +1을 부여합니다. 대학교가 있는 캠퍼스(교정) 특수지구에 인접한 유닛은 한 턴만에 체력을 전부 회복할 수 있습니다.'),

	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_1',
	'비코바로는 닐프가드 제국의 최남단 속국 중 하나입니다. 자체 마법 교육기관과 얀 칼베이트 황제에 의해 건설된 수도의 의료 아카데미로 유명합니다. 비코바로인들은 닐프가드 문화에 잠식된 후에도 여전히 조국의 유산을 자랑스럽게 생각합니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_2',
	'역사'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_3',
	'이 나라의 역사는 저지 알바 부족이 비코바로의 문화에 영향을 받았던 고대로 거슬러 올라갑니다. 초기 비코바로인들의 업적은 닐프가드 유산의 일부가 되었습니다. 수세기 동안 비코바로는 닐프가드 제국의 문화를 천천히 받아들였습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_4',
	'12세기 후반에 비코바로는 토레스 황제의 군대에게 점령되었지만 곧 닐프가드군은 퇴각할 수밖에 없었습니다. 그러나 퍼거스 황제의 성공적인 에톨리아 정복을 목도한 비코바로의 귀족들은 통치자에게 영향력을 행사하여, 비코바로는 자발적으로 닐프가드 제국에게 합병을 요청하게 되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_5',
	'비코바로의 베테랑 방패병들은 에톨리아 군대와 함께 제2차 북부 전쟁에 참전했습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_6',
	'지형과 기후'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_7',
	'비코바로의 국경은 로완 공국과 임라크 공국과 같은 닐프가드 제국의 핵심 지역과 접하고 있습니다. 온난한 구릉 지역이며 맨드레이크 재배가 가능한 기후를 갖고 있습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_8',
	'사회와 문화'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_9',
	'비코바로의 닐프가드 제국과 귀족에게 충성하는 시민들은 풍부하고 안정된 삶을 살고 있습니다. 많은 귀족들은 산에 위치해 방어에 용이한 거대한 성을 소유하고 있습니다. 그들은 자녀를 교육하여 사회적으로 인정받는 교육기관인 카스텔 그라우피엔에 위치한 제국 아카데미로 입학을 시킵니다. 입학생들은 닐프가드의 예의범절에 대한 교육을 받고 닐프가드 귀족과 교류하게 됩니다. 이 전략을 통해 비코바로는 닐프가드 제국의 지방 정부뿐만 아니라 중앙 정부에도 그들의 자손을 배치시켜 영향력을 행사할 수 있게 되었습니다.'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_10',
	'비고'),
	('ko_KR',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_11',
	'비코바로라는 이름은 같은 이름의 이탈리아 도시의 이름에서 참고했을 가능성이 있습니다.'),
-----------------------------------------------
-- Religion
-----------------------------------------------
	('ko_KR',	'LOC_RELIGION_IPG_ARD_FEAINN',	'위대한 태양교'	),

	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_1',
	'위대한 태양교(닐프가드 언어로 Ard Feainn)는 토레스 황제의 통치 이래로 제국의 국교였습니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_2',
	'북부 왕국의 주민들은 위대한 태양교의 교리에 대해 거의 알지 못합니다. 위대한 태양교의 수장인 대제사장은 곧 닐프가드 황제입니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_3',
	'위대한 태양교는 제국의 다양한 종교 중 하나였으며 핵심 지역에서만 명성이 있었습니다. 이러한 상황은 약 100년 전 일련의 주요 개혁을 실시한 퍼거스 황제의 재위 기간에 바뀌었습니다. 황제는 왕조를 이루는 것보다 지역 통합에 강력하고 영구적인 영향력을 끼칠 상징을 찾고 있었습니다. 능숙한 재정 관리와 사제들에게 호의를 베품으로써 제국 전체에 새로운 위대한 태양교 추종자들을 확보했습니다. 그 대가로 황제는 사제들에게 정책에 대한 절대적 지원을 요구하며 사실상 사제들이 공무원을 겸임하게 했습니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_4',
	'"3월 8일 칙령"으로 위대한 태양교는 닐프가드 제국의 국교가 되었고, 찬탈자의 통치 기간 동안 영향력이 축소되었지만 에미르 바 엠레이스가 재집권한 뒤로 영향력은 다시 높아졌습니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_5',
	'위대한 태양교는 엘프의 자연 숭배에 뿌리를 갖고 있습니다. 믿음의 대상은 따뜻함과 생명을 주고 인류를 수호하는 역할을 하지만 잔인하고 파괴적일 수도 있는 태양입니다. "3월 8일 칙령" 이후로 지배 왕조의 수호신이기도 합니다. 가장 중요한 공휴일은 춘분과 현 황제의 생일(현재 7월 26일)입니다. 중앙 의식은 수도에서 거행되며, 종교의 수장인 대제사장 역할은 황제가 수행합니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_6',
	'해당 공휴일은 엄숙한 음악 속에 모든 주요 관리, 지휘관 및 귀족이 참석하는 가운데 성대하게 거행됩니다. 공식 행사가 끝나면 음식과 음료를 곁들인 민속 놀이를 즐기게 됩니다. 이 공휴일과 관련된 많은 관습들이 엘프 전통에서 직접 파생되었다는 점은 주목할 만합니다. 위대한 태양교의 사제들은 봉헌, 축하, 공휴일 동안 금과 은으로 수놓은 흰색 의복을 착용합니다. 사제의 평상복은 검은색 민간복입니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_7',
	'위대한 태양교의 사제가 되는 것은 제국의 흔한 직업 경로 중 하나입니다. 신학대학을 졸업하고 시험에 합격하면 "사제"라는 공식 칭호를 얻게 됩니다. 그 후, 교육에 따라 신입 사제는 지역 사원 또는 지역 총독 사무실에 파견됩니다. 그 후엔 사제의 정치적 감각 또는 종교 관련 임무 수행 능력에 모든 것이 달려 있습니다.'),
	('ko_KR',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_8',
	'흥미롭게도 위대한 태양교의 사제 중에는 마법이나 특별한 능력을 가진 사람이 없습니다. 혹시라도 그러한 능력이 발현된 자는 즉시 로크 그림에 있는 제국 마법 아카데미로 보내지게 됩니다.');