/*
	Civilization Text Entries zh_Hans_CN
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

INSERT OR REPLACE INTO LocalizedText
			(Language, Tag, Text)
VALUES

-----------------------------------------------
-- Civilization
-----------------------------------------------
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_NILFGAARD_NAME',			'尼弗迦德'			),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_NILFGAARD_DESCRIPTION',	'尼弗迦德帝国'	),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_NILFGAARD_ADJECTIVE',  	'尼弗迦德的'			),
-----------------------------------------------
-- Civilization Unique Ability
-----------------------------------------------
	('zh_Hans_CN',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME',				'行省管理者'				),
	('zh_Hans_CN',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION',	
	'攻占一个外国城市立即在城市中免费获得一个建造者。建造者可以使用一次劳动力来完成区域建设所需的15% [ICON_Production] 生产力。被占领的城市没有生产力减益。间谍可以从所有可能的晋升中选择升级。'	),
-----------------------------------------------
-- Civilization Unique Infrastructure (District)
-----------------------------------------------
	('zh_Hans_CN',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',				'尼弗迦德帝国军营'								),
	('zh_Hans_CN',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',
	'尼弗迦德特色军事区域，取代军营。建造费用大大降低，建成后城市忠诚度每回合+2。尼弗迦德帝国军营中工作的每个公民额外产出+1 [ICON_Science] 科技值和+1 [ICON_Culture] 文化值。所有在此城市中训练的陆地单位+25%战斗经验。'	),

	('zh_Hans_CN',	'LOC_ABILITY_IMPERIAL_CAMP_TRAINED_UNIT_XP_DESCRIPTION',	'从尼弗迦德帝国军营+25%战斗经验。'	),
-----------------------------------------------
-- Civilization Unique Unit
-----------------------------------------------
	('zh_Hans_CN',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',	'那乌西卡师'	),
	('zh_Hans_CN',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',	 
	'尼弗迦德中世纪时期特色重骑兵单位。建造费用和维护费用十分昂贵，但在 [ICON_Movement] 移动力允许的情况下可以攻击两次。'	),

	('zh_Hans_CN',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_NAME',	'马格尼师'	),
	('zh_Hans_CN',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_DESCRIPTION',
	'尼弗迦德中世纪时期特色侦察单位，替代散兵，建造费和维护费十分便宜。近战攻击且无视区域控制。当远离友方领土4个单元格时获得+10 [ICON_Strength] 战斗力，并在击败敌人时获得 [ICON_Science] 科技值和 [ICON_Culture] 文化值。'	),

	('zh_Hans_CN',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',	'瑟瑞卡尼亚火蝎'	),
	('zh_Hans_CN',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',	 
	'尼弗迦德文艺复兴时期特色攻城单位，取代射石炮。在火药科技时更早解锁，并且建造费用更便宜。'	),

	('zh_Hans_CN',	'LOC_ABILITY_EMHYR_NAUZICAA_BRIGADE_EXTRA_ATTACK_DESCRIPTION',		'如果 [ICON_Movement] 移动力允许，每回合额外+1次攻击次数。'	),
	('zh_Hans_CN',	'LOC_ABILITY_CALVEIT_MAGNE_DIVISION_DESCRIPTION',			'处于友方领土4格以外：+10 [ICON_Strength] 战斗力，击败敌人提供 [ICON_Science] 科技值和 [ICON_Culture] 文化值。'	),

	('zh_Hans_CN',	'LOC_CALVEIT_MAGNE_DIVISION_AWAY_STRENGTH',		'+{1_Amount} Away from friendly territory.'	),
-----------------------------------------------
-- Mountains
-----------------------------------------------
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_TIR_TOCHAIR',		'提尔.托夏山脉'	),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_AMELL',				'阿梅尔山脉'			),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_FIERY',				'法尔瑞山脉'	),
-----------------------------------------------
-- Rivers
-----------------------------------------------
	('zh_Hans_CN',	'LOC_NAMED_RIVER_ALBA',				'阿尔巴河'				),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_VELDA',			'维尔达河'				),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_SYLTE',			'西尔特河'				),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_YELENA',			'叶连娜河'			),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_WAGTAIL',			'瓦格泰尔河'			),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_BLESSURE',			'布列薛河'			),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_SANSRETOUR',		'杉斯雷托河'		),
-----------------------------------------------
-- Deserts
-----------------------------------------------
	('zh_Hans_CN',	'LOC_NAMED_DESERT_KORATH',				'科拉兹沙漠'				),
	('zh_Hans_CN',	'LOC_NAMED_DESERT_ZERRIKANIAN',			'瑟瑞卡尼亚沙漠'		),
-----------------------------------------------
-- Lakes
-----------------------------------------------
	('zh_Hans_CN',	'LOC_NAMED_LAKE_MUREDACH',				'穆雷达湖'				),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_TARN_MIRA',				'塔恩.米拉湖'				),
-----------------------------------------------
-- Cities
-----------------------------------------------
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_1',  '尼弗迦德城'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_2',  '温尼伯格'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_3',  '达恩.鲁阿克'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_4',  '达恩.罗万'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_5',  '达恩.亚穆拉克'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_6',  '维罗勒达'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_7',  '帕特亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_8',  '斯提加'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_9',  '阿玛瑞罗'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_10',  '特加诺'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_11',  '达恩.迪弗拉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_12',  '洛克.格瑞姆'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_13',  '艾登'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_14',  '拉.坡因特'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_15',  '巴卡拉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_16',  '哈尔科夫'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_17',  '萨尔姆'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_18',  '克拉蒙特'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_19',  '瑟恩'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_20',  '内文雷乌什'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_21',  '科沃'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_22',  '独角兽村'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_23',  '顿.戴尔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_24',  '马尔霍恩'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_25',  '法诺'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_26',  '嫉妒村'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_27',  '杜德诺'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_28',  '弗扎姆'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_29',  '泰菲'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_30',  '杜鲁格'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_31',  '格莱斯文'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_32',  '纽弗吉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_33',  '罗列多'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_34',  '卡拉维斯塔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_35',  '维戴特'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_NILFGAARD_36',  '瓦格泰尔'),
-----------------------------------------------
-- Citizens
-----------------------------------------------
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_1',	'费格斯'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_2',	'蒂博尔.艾格布拉杰'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_3',	'弗林姆德'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_4',	'斯维尔'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_5',	'瓦提尔.德.李道克斯'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_6',	'莫坦森'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_7',	'菲翁'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_8',	'托雷斯'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_9',	'希拉德'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_10',	'史提芬.史凯伦'	),

	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_1',	'卡席雅'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_2',	'葛琳尼斯'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_3',	'奥拉'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_4',	'辛西亚'),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_5',	'伊斯贝尔'		),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_6',	'安娜'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_7',	'芙琳吉拉.薇歌'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_8',	'席薇雅.安娜'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_9',	'薇薇恩'	),
	('zh_Hans_CN',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_10',	'艾希蕾.阿纳兴'	),
-----------------------------------------------
-- Info
-----------------------------------------------
	('zh_Hans_CN',	'LOC_CIVINFO_IPG_NILFGAARD_LOCATION',		'大陆上，雅鲁加河以南一切土地'		),
	('zh_Hans_CN',	'LOC_CIVINFO_IPG_NILFGAARD_SIZE',			'约250万平方千米'	),
	('zh_Hans_CN',	'LOC_CIVINFO_IPG_NILFGAARD_POPULATION',		'约4500万'		),
	('zh_Hans_CN',	'LOC_CIVINFO_IPG_NILFGAARD_CAPITAL',		'尼弗迦德，金塔之城'		),
-----------------------------------------------
-- Civilopedia
-----------------------------------------------
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_1',		
	'尼弗迦德帝国（尼弗迦德语Ceas''raet）是已知世界历史上最强大的帝国。它位于大陆的南部，拥有繁荣的经济，一支训练有素的强大军队和才华横溢的指挥官。她的扩张主要是通过征服外国，然后这些国家变成了帝国的行省。帝国的居民相信“真正的”尼弗迦德人只是出生在帝国中心的人，而不是出生在被征服省份的人。'),	
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_2',		
	'省份由管家或国王统治（在国王自愿投降的情况下，他保留王位但受制于皇帝或只是一个封臣）。多年来，帝国不断扩张，征服了新的土地，并在恩希尔·瓦尔·恩瑞斯皇帝统治期间向北延伸至雅鲁加河。'),	
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_3',	
	'在北方王国中，帝国被描绘成一个包罗万象的对手，北方的许多自由人民对它充满了仇恨。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_4',	
	'国徽'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_5',	
	'大太阳象征着太阳的光辉和太阳的热量，是尼弗迦德人的主要象征。它出现在帝国纹章、硬币、武装部队旗帜以及维罗莱丹剑匠的印记上。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_6',	
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_7',	
	'尼弗迦德人相信他们的历史可以追溯到第2世纪。第一批定居者与黑精灵混血，创造了一个主要由精灵语言、信仰、习俗和文化组成的国家。 与此同时，居住在阿尔巴河上分散定居点的勇敢的牧羊人慢慢地融入了周围的国家，国家的人吸纳了他们最好的特征，如文化、技术和军事战略，并为他们提供安全和秩序作为回报。这两个群体最终在邻国的各种征服和自由时期合并，创造了一个独特的，融合了精灵、维可瓦罗人、爱托里亚人和几个阿尔巴部落成就的遗产。在他们历史的某个时刻，尼弗迦德王国出现了。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_8',	
	'君主们得到顾问委员会的协助，该委员会后来被称为参议院。 随着时间的推移，参议院的权力越来越大，成为立法机构。在此期间，尼弗迦德的影响力开始扩大，邻近的地区慢慢被尼弗迦德化，人民被置于帝国的统治之下，通过“钢铁外交”，人们被期望学习其官方语言并吸收胜利者文化的元素。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_9',	
	'最终，下阿尔巴以外的几个领域自愿或被迫并入该领域。元首（大将军）的头衔出现了，起初只是作为军队中的职位。那个时期加入的已知土地是罗万和亚穆拉克，还有鲁阿克、戴尔兰、马格尼和温尼伯格。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_10',	
	'12世纪初，托雷斯·恩瑞斯推翻了参议院并取得了绝对权力。起初他只称他的国家为“王国”，但在他后来的统治期间，“帝国”一词被创造出来——皇帝也随之而来。 托雷斯的统治也见证了通过3月8日的法令将大太阳 改变(伟大日轮) 为国教和帝国徽章。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_11',	
	'托雷斯死后的某个日子，可能是在1200年代初期，费格斯·恩瑞斯登上了王位。然而，他被许多人认为是一个软弱的皇帝。1216 年，皇帝费格斯决定以爱托里亚作为帝国所有敌人的未来的例子。尼弗迦德军队进攻并打垮了爱托里亚，摧毁了它的权力结构并抹杀了定义埃托利亚生活的价值观。费格斯在那一年也使吉米瑞亚服从于帝国。维可瓦罗的贵族开始影响他们的统治者，随后维可瓦罗自愿且主动地要求加入尼弗迦德。费格斯最终在1233年被篡位者推翻。在政变期间，费格斯被篡位者杀死，而他的儿子和继承人恩希尔则被法师布拉森斯诅咒，后者将他变成了一只人形刺猬。尽管有狗袭击他，恩希尔还是设法逃脱了，并在熟人的帮助下离开了帝国。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_12',	
	'篡位者在统治期间宣布了全国大赦，削弱了对大太阳的崇拜，并于1239年吞并了艾宾。在这场漫长的冲突中，麦提那、那赛尔甚至梅契特都在1250年代中期被帝国征服。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_13',	
	'1257 年，由阿达尔.爱普.达西、威戈佛特兹和其他恩希尔的支持者领导了一场起义，他们袭击了皇宫并杀死了篡位者。恩希尔·瓦·恩瑞斯，被驱逐出境的王位继承人，再次进入尼弗迦德成为新皇帝，并获得了“在敌人坟墓上舞动的白色火焰”的绰号，在尼弗迦德语里，则是“Deithwen Addan yn Carn aep Morvudd”。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_14',	
	'社会'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_15',	
	'虽然“帝国”的人口包含多种不同的文化和民族，当局热衷于让少数民族缓慢地“尼弗迦德化”，即用“正统的尼弗迦德人”、下阿尔巴遗产取代当地的价值观和习俗。当局鼓励帝国边界内的内部移民：在动荡的省份建立下阿尔巴定居者的殖民地，同时通过有吸引力的提议鼓励忠于帝国的非尼弗迦德农民在新征服的领地定居；叛乱地区会通过奴役或对有问题的群体进行种族清洗来得到净化。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_16',	
	'另一方面，对于许多非人类种族而言，尼弗迦德帝国总体上被认为是比大多数北方领域更安全的家园。除了像树精这样的群体，生活在帝国中的非人类认为帝国制度严酷，但公正。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_17',	
	'琐事'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_18',	
	'尼弗迦德与现实世界的罗马帝国有许多相似之处：一个强大的帝国，使用纪律严明的军队，通过艰苦的征服将其他“野蛮”文化同化。同样相似的是它的代表和臣民之间的优越感（他们喜欢相信他们都是上古之血 - 劳拉.朵伦的后裔）。尼弗迦德人对大太阳的崇拜可以关联到罗马帝国对 Sol Invictus（“无敌太阳”）的崇拜。此外，《巫师 2》清楚地阐明了这一想法。 在第1章的一个任务描述中，丹德里恩使用谚语“在尼弗迦德时，做尼弗迦德人做的事”，这与我们使用“在罗马时，做罗马人做的事”的谚语完全相同。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_19',	
	'首都的起源以及帝国名称的起源尚不清楚。“Nilf”似乎是冰岛语“nifl”（雾、黑暗、薄雾；如“Niflheim”中的意思）的损坏版本，而“gaard”可能是荷兰语“gaard”（院子、花园）、丹麦语“gaard/gård” （农场）或古挪威语“garðr”（庭院、围栏）。'),
	('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_20',	
	'在配色方案和盔甲设计方面，尼弗迦德军队让人想起神圣罗马帝国军队的某些特征（不要与早期的罗马帝国混淆），特别是他们的皇家盔甲。'),
-----------------------------------------------
-- Unique Unit Civilopedia Entry
-----------------------------------------------
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_1',  	
	'那乌西卡，也被称为“骷髅头”、“死者的头颅”，是尼弗迦德骑兵第4军的一个旅，由马库斯.布莱班特少将指挥。该旅本身由基斯.凡.洛指挥。他们配备了战锤和三尺半长的剑。'	),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_2',
	'那乌西卡连同戴尔兰第七骑兵旅是布伦纳战役中最后投入战斗的部队。 由陆军元帅门诺·库霍恩亲自率领，这些部队本计划撕裂北方军队，最终进入敌人后方，然后从后方攻击他们。这种努力最终被证明是徒劳的，因为缺乏经验的可怜的该死的步兵，在布洛尼伯的领导下，出人意料地在遭受重大伤亡的情况下阻止了尼弗迦德骑兵的前进并坚守阵地。 从这一刻开始，尼弗迦德的失败是不可避免且迅速的。'),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_3',
	'琐事'),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_4',
	'这个名字可能参考了《奥德赛》中的女性角色娜乌西卡。'),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_5',
	'他们的别名“骷髅头”可能是指 SS-Totenkopfverbände。'),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_6',
	'他们的别名“死者的头颅”可能参考了普鲁士军队的Totenkopf Hussars，他们穿着类似颜色的制服和徽章。'),

	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_1',
	'马格尼师是来自马格尼的一个师，隶属于弗迦德骑兵部队的第4骑兵军，由马库斯·布莱班特少将指挥。'),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_2',
	'当一名尼弗迦德骑兵军官行为越界时，他很可能会被重新分配到科拉兹沙漠。在这个“煎锅”里无尽的沙滩上巡逻几个月将清除他任何不服从的迹象，取而代之的是疯狂地愿意做任何事情以避免被遣返。'),

	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_1',  	
	'瑟瑞卡尼亚火蝎是尼弗迦德帝国在攻城期间经常使用的瑟瑞卡尼亚攻城武器。它与北方弩炮非常相似，但它发射的不是飞镖，而是一种类似于绿色火球的未知物质。'	),
	('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_2',  	
	'“它的名字太容易误导了，让它听起来像是一些肥胖的淡红蜘蛛，而不是一种设计精巧的大规模杀伤性武器……它不是占领城市的最佳选择，但非常适合将城市夷为平地。”'	),
-----------------------------------------------
-- Unique Infrastructure
-----------------------------------------------
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_1',
	'尼弗迦德集团军“中央”营地是《巫师 3》中尼弗迦德军队在威伦地区的总部。在短短两周内搭建完毕，集团军“中央”营地构成了尼弗迦德军事建筑的精髓。'),
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_2',
	'尼弗迦德军队'),
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_3',
	'毫无疑问，尼弗迦德帝国的帝国军队是大陆上最训练有素的战斗部队之一。 从低级阶层到高级贵族都参与了军队，其士兵，被称为黑衣人，精通战斗艺术。 尼弗迦德皇帝对帝国军队处于完全控制下，他通过元帅领导下的一组高级军官指挥军队。'),
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_4',
	'在更大的征服和入侵期间，例如北方战争，军队被分成多个集团，例如中央集团军、东方集团军和维尔登作战集团。在第二次北方战争期间，军队数量约为32万。其中30万用于进攻北方王国，约2万留在帝国以维持和平并保卫核心省份，以防战争出现意外转折。'),
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_5',
	'与许多其他军队一样，帝国军也拥有攻城武器，包括石弩、投石车、瑟瑞卡尼亚火蝎和腐物投掷器。'),
	('zh_Hans_CN',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_6',
	'与北方王国不同，奴隶制在尼弗迦德人中司空见惯。奴隶，通常是战俘，不仅被用来从事体力劳动，甚至在战斗中也被用来为他们的自由而战，至少他们的主人是这样说的。'),
-----------------------------------------------
-- City State
-----------------------------------------------
	-- METINNA
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',			'麦提那'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_METINNA_MINOR',					'麦提那'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_DESCRIPTION',	'麦提那城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_ADJECTIVE',		'麦提那的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_NAME',		'麦提那宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION',	'作为麦提那宗主国时训练的轻骑兵单位永久获得“麦提那骑兵”能力：+4 [ICON_Strength] 战斗力。免费复制一份 [ICON_RESOURCE_Wine] 葡萄酒资源。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_1',
	'麦提那是阿梅尔南部的王国之一，目前是尼弗迦德帝国的附庸国和麦提那行省的一部分。由马格.德拉平原的大部分组成，多年来它一直是技艺高超的骑兵和著名的马匹饲养员的家园。它也是南北贸易的重要枢纽。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_2',
	'远古历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_3',
	'这些土地上的原始居民是狸怪，他们是复杂种族成员，他们的家园包括现代的麦提那、那赛尔和马格.图加。在移民时代，他们被开始建立自己文明的精灵驱逐。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_4',
	'上古种族主要居住在百湖之地，或Centloch。直到今天，他们宫殿的遗迹仍被过去的精灵鬼魂所困扰。最著名的建筑之一可能是塔恩.米拉北岸传说中的托尔.吉薇艾儿玄武岩塔（雨燕之塔），但到13世纪，它只剩下几块石头了。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_5',
	'人类领域'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_6',
	'人类在历史的某个时刻定居在这些土地上。至少建立了两个主要的贸易大都市，麦提那和内文雷乌什。一个王国最终在他们周围兴起，它的名字来源于第一座城市。最著名的麦提那君主之一是泽维莱娜女王，她是一位魔法使用者，在地精伦普雷斯提尔特的帮助下获得了王冠，但在拒绝意外律后失去了王冠。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_7',
	'马格.德拉平原成为了马尔基人的家园，马尔基人是起源于维尔达河三角洲的游牧骑士。他们在这里建立了广阔的牧场，开始饲养牛和著名的麦提那小马。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_8',
	'尼弗迦德战争'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_9',
	'在12世纪后期，马提纳卷入了与尼弗迦德人的战争，但直到13世纪北方战争期间篡位者统治时，它或它的邻国都没有被征服。地方王国被允许以相对自治的方式进行统治，而拥有自己的军官团的行省则以王国命名。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_10',
	'在尼弗迦德人在索登山战役中战败后的一段时间，麦提那人在所谓的马提纳叛乱中起义。然而，起义在同年被军队的年轻指挥官镇压，这些指挥官就是恩希尔·恩瑞斯打算用来取代那些在索登山之战中失败者的人。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_11',
	'麦提那雇佣步兵在第一次艾德斯伯格战役和温格堡战役中服役于尼弗迦德军队。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_12',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_13',
	'她西接艾宾（可能还有大洋），东接吉索，北接那赛尔省，南接与麦提那形成麦提那省的梅契特。该地区的三分之一由马格.德拉平原组成，北接叶连娜河，南接西尔特河。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_14',
	'社会和文化'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_15',
	'在被篡位者征服的国家中，麦提那人有时被描述为与下阿尔巴人最相似的群体。他们是熟练的商人和强悍的骑兵；由于马基文化的影响，据说麦提那人是在马鞍上出生的。平原的居民被认为比城市居民更野蛮；来自马格.德拉的摔跤手经常出现在麦提那相当不卫生的竞技场中。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_16',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_17',
	'麦提那的大部分收入来自以大都市为中心的贸易。在内陆，在马格.德拉平原上，有广阔的牧场饲养牛群和所谓的麦提那小马。麦提那小马是白马，非常耐寒，脚踏实地，而且聪明——当然，是就马而言。据信，原始种群是由马尔基人从维尔达河三角洲带到这里的。马提纳国王向尼弗迦德进贡的贡品通常以马匹和骑兵的形式出现。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_18',
	'麦提那以其名为麦提那玫瑰的葡萄酒而闻名。它经常被鉴赏家描述为美妙绝伦的酒，是一款酒香浓郁的佐餐酒。与马尔基人一样，它起源于 维尔达河三角洲的酿酒厂，但被带到了麦提那并成为一种全国性的饮品，麦提那人以其为荣，以至于人们可以与陶森特人进行一场关于酒的讨论的呐喊比赛甚至决斗。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_19',
	'麦提那生产esboda剑，它被认为是大陆上制造的最轻、最锋利的骑兵刀。'),

	('zh_Hans_CN',	'LOC_ABILITY_METINNA_CAVALRYMEN_NAME',			'麦提那骑兵'),
	('zh_Hans_CN',	'LOC_ABILITY_METINNA_CAVALRYMEN_DESCRIPTION',	'永久+4 [ICON_Strength] 战斗力。'),
	
	-- MAECHT
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',			'梅契特'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_MAECHT_MINOR',					'梅契特'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_DESCRIPTION',	'梅契特城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_ADJECTIVE',		'梅契特的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_NAME',		'梅契特宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION',	'间谍在执行“捏造丑闻”间谍任务时提高3级行动等级。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_1',
	'梅契特是大陆南部的一个王国，北接麦提那，东接吉索，南接艾宾。然而，在1250年代，它最终落入尼弗迦德手中，并在篡位者统治期间成为麦提那省的一部分。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_2',
	'梅契特实行伪自治状态，表面上公民选举他们的国王，但选举实际上取决于尼弗迦德皇帝的决定。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_3',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_4',
	'埃克斯帕克国王在被征服后继续统治，直到 1258 年被杀手刺伤后死于急性肺炎。随后王国举行了选举并由并豪耶特获胜，尽管柯德林格建议一年前夺回尼弗迦德王位的恩希尔拥有决定性的一票。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_5',
	'感觉到了不稳定后，梅契特贵族，如鲁迪格公爵，在瑟恩组建了反叛力量，但很快在一次苛刻的远征中被吉米瑞亚维稳队镇压。到1267年，梅契特与帝国牢牢绑定，其雇佣军参加了第二次北方战争。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_6',
	'小记'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_7',
	'多尼声称梅契特的人非常迷信，尽管这可能是一个用来解释为什么他不想在与帕薇塔结婚后立即回家的诡计。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_8',
	'波兰原版的《轻蔑的时代》仅包含对王国纹章的模棱两可的描述，提到了“银色的鱼和盾牌上分为四分之一的蓝色和红色的王冠”。将这些书翻译成英文的 David French 提供了更详细的描述。'),
	
	-- TOUSSAINT
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME',			'陶森特'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_TOUSSAINT_MINOR',					'鲍克兰'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_DESCRIPTION',	'陶森特城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_ADJECTIVE',		'陶森特的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_NAME',		'陶森特宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION',	'为奢侈品的种植园改良设施+3 [ICON_Culture] 文化值。如果放置于 [ICON_RESOURCE_Wine] 葡萄酒上，额外+2 [ICON_Culture] 文化值。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_1',
	'陶森特是尼弗迦德帝国旗帜下的一个小型自治公国，得益于该地区的火山土壤和晴天和雨天天气的理想结合，以其葡萄酒而闻名。陶森特并没有保存一支自己的庞大常备军，而是依靠几个骑士团，配合公国卫队守卫边界。 陶森特也是大陆上为数不多的没有特务局的国家之一。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_2',
	'尽管是尼弗迦德的附庸国，陶森特仍保持高度自治，尼弗迦德帝国不倾向于将帝国权威强加于其内部事务或在很大程度上侵犯其边界。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_3',
	'虽然公国的表面可能是童话般的和宁静的，但在酒窖下面隐藏着一个庞大的地下系统，该系统连接着古老的坑道、矿山和地牢，以及被熔岩镂空的天然洞穴和隧道，据称与地球的中心相连。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_4',
	'史前和远古时期'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_5',
	'多年来，现在的陶森特地下居住着如 korreds、kilmulises、pryskirniks 和许多其他生物的智慧生物，其中一些甚至在13世纪之前在猎魔人的典籍中都不被知道。在8世纪 BR（复活之前），一群艾恩.希迪精灵以如今的鲍克兰为首都，在这里建立了他们的王国。他们用白色大理石和象牙建造了美丽的城市。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_6',
	'人类征服'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_7',
	'第一次登陆后的几十年，精灵王帝芙索夫的王国面临着由北方人首领卢多维克领导的入侵。781年，精灵们放弃了他们的象牙城，前往阿梅尔山脉，带走了他们能带走的一切，并摧毁了其他一切。凡是他们拿不走，又没能拆除或焚烧的，他们就咒骂。卢多维克带着他的军队进军山麓，要求帝芙索夫投降并宣布他为国王。精灵拒绝要求后发生了一场战斗，艾恩.希德军队被屠戮。在为损失而哭泣时，帝芙索夫同意投降。 第二年，人类决定用大屠杀来庆祝胜利周年纪念日，对高贡山坡上的所有残余生物进行种族灭绝。最后一批未被人类触及的精灵遗迹是提尔.纳.丽亚.艾林尼的隐藏墓地，在随后的时代中继续被使用，并受到艾恩.萨维尼的保护。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_8',
	'在接下来的几个世纪里，早期陶森特的主要职业显然是采矿，他们也挖空了许多坑道和矿山。当时还建造了几个地牢，可能是为了关押政治敌人——这片土地被分成几个小领主和公爵。高贡山麓的埃皮塞亚就是这样的领地之一，该领地就在帝芙索夫被击败的地方附近。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_9',
	'这一时期最重要的地貌改变事件之一是那赛尔公爵亚当试图按照他的风格调节 杉斯雷托河的流量——并且在这个过程中不情愿地创造了杉斯雷托沼泽。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_10',
	'改革'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_11',
	'12 世纪，该地区见证了亨利三世公爵发起的第一次改革。欣赏遥远的下阿尔巴土地后，他试图使这个领域文明化。例如，通过修改惩罚性法律。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_12',
	'在本世纪中叶，该国中的权力由公爵夫人阿黛拉·玛塔巩固。她下令整修精灵首都宫殿，将自己的座位移到那里，并建立了鲍克兰城。她为她的追求者组织了一场马上比武大会，以奖励她最看重的男人的品质——力量、勇气和狡猾，从而在公国播下了骑士传统的种子。在她南下的旅程中，她遇到了尼弗迦德皇帝托雷斯的小儿子并与他成婚，从而在陶森特和尼弗迦德帝国之间建立了纽带。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_13',
	'阿黛拉.玛塔的女儿卡罗琳娜.罗伯塔继续改革。她禁止在宴会期间使用尖刀，因为她发现用尖刀剔牙的习俗很野蛮。她也是认可圣普雷格蒙带来的雷比欧达教派的人。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_14',
	'13世纪'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_15',
	'公国由卡罗伯塔的孙女安娜.亨利叶塔统治，统治期至少从1258年她嫁给雷蒙德公爵开始。尽管有丈夫，但她在她的臣民中享有更多的爱慕。 然而，自从雷蒙德于1265 年去世后，安娜.亨利叶塔一直被她的顾问隐瞒了世界上发生的事件，因为她被认为情绪不稳定，直到1267年末才从杰洛特小队得知第二次北方战争开始了。因为这次叛国罪，她将特伦伯莱部长关进了塔楼。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_16',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_17',
	'陶森特位于阿梅尔、提尔.托夏和法尔瑞三座山脉之间。该地区由温暖的过去留下的火山土壤允许人们种植葡萄藤。另一个昔日的遗迹是现在已经干涸的熔岩管，它们与洞穴和人形地牢一起构成了公国的地下系统。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_18',
	'社会'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_19',
	'该地区的地上部分主要居住着北方人。地下部分至少在13世纪仍未被探索，并且居住着小精灵、kilmulises、korreds、pryskirniks、吸血鬼和许多科学上未知的物种。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_20',
	'文化'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_21',
	'在陶森特，传统是一件神圣的事情。在假期中最重要的是酒桶，这能被敏锐地观察到。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_22',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_23',
	'在古代，该地区有采矿业。然而，自 12 世纪中叶以来，公国经济的主要领域一直是葡萄酒业，封闭的坑道和竖井正慢慢被怪物占据。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_24',
	'琐事'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_25',
	'陶森特是万圣节的法语名称。它也是法国北部上诺曼底的一个公社的名称。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_26',
	'在血与酒扩展包中，许多居民有时会说法语。这包括语法；一封嘲讽地称意大利葡萄酒Est est（东之东，拉丁语为“is is”）为“Était Était”的信，该法语意思为“过去，过去”或“过去常常”。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_27',
	'鲍克兰的建筑以波兰扎莫希奇的风格主义建筑为基础。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_28',
	'公国的文化是基于中世纪的意大利，西班牙，以及法国南部地区设计的。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_29',
	'公国卫队戴着莫里昂，这是一种起源于西班牙的头盔。'),
	
	-- GEMMERA
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',			'吉米瑞亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_GEMMERA_MINOR',					'吉米瑞亚'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_DESCRIPTION',	'吉米瑞亚城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_ADJECTIVE',		'吉米瑞亚的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_NAME',		'吉米瑞亚宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION',	'对自由城市单位+5 [ICON_Strength] 战斗力。城市有驻扎单位时每回合忠诚度+2。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_1',
	'吉米瑞亚是一个前王国，后来成为尼弗迦德帝国的一个行省。它以其凶猛的战士而闻名，例如吉米瑞亚维稳队。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_2',
	'多年来，一些北方制图师声称吉米瑞亚是大陆的最南端，下面的土地属于另一个大陆，但其他大多数人认为艾宾是南部边界。然而，到第二次北方战争时，这些信念显然已被抛弃。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_3',
	'远古历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_4',
	'很久以前，风之塔证明了吉米瑞亚的海岸线地区有精灵存在。在山上至少有一座矮人矿山，以及一座古老的锻造厂和玻璃厂。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_5',
	'长期以来，吉米瑞亚王国居住着凶猛而粗暴的野蛮人，一直是邻国的麻烦。众所周知，在托雷斯皇帝统治期间，至少有一次吉米瑞亚的入侵行动是针对尼弗迦德帝国的。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_6',
	'在12世纪下半叶，吉米瑞亚面临着越来越多的帝国影响。他们被篡位者庞德里克公爵挡在了海湾，直到他被斯提加的猎魔人蜻蜓和他被谋杀的兄弟沃德里克的儿子废黜。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_7',
	'尼弗迦德行省'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_8',
	'吉米瑞亚最终于1226年被皇帝费格斯.恩瑞斯征服。渴望大量的抑魔金，他收集了资源，并与爱托里亚和维可瓦罗的军队一起入侵了这个国家，几乎铲除了岩石地区的所有人口，在某些地区只留下比流浪的山羊多一点的居民。在这场征服之后，最凶猛的吉米瑞亚战士加入了帝国军队以掠夺和制造混乱。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_9',
	'吉米瑞亚法师不愿意为帝国效力。这个问题导致篡位者和以赛亚·科霍恩成立了一个名为法师猎手的组织，该组织的成员将寻找未收编的魔法使用者并将他们带到首都接受审判。 为了武装这个组织，皇帝召集了帝国中最成功的矿主，并向能够发现最大的抑魔金矿层的人提供了一份独家合同——而唯一那些矿层就是在吉米瑞亚发现的。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_10',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_11',
	'吉米瑞亚可分为沿海地区、森林、草原和干旱的岩石山丘。这里没有大都市，也没有快速通道，但可以找到一些通过完善的土路相互连接的城镇和村庄链。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_12',
	'社会'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_13',
	'即使野蛮且最遵守部落法规，吉米瑞亚人也拥有君主制，由拥有显着权力的国王和公爵组成，以及由法师和德鲁伊顾问组成的法庭。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_14',
	'人们非常亲切和真诚，但同样也很暴力和残忍。他们是伟大的骑手，带着激情和爱骑着他们的种马驰骋。不幸的是，他们怀着这样的爱心进行了抢劫与挪用他人的财产的恶行。甚至还有一句残忍的谚语“用吉米瑞亚的方式玩耍。”，意思是在受害者家属面前进行残忍的轮奸。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_15',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_16',
	'该地区以生产土豆、肉汁和硬奶酪而闻名。在发现了丰富的 抑魔金矿床的山丘上，已经建立了皇家矿山。'),

	('zh_Hans_CN',	'LOC_GEMMERIAN_PACIFIERS_NAME',			'吉米瑞亚维稳队'),
	
	-- VICOVARO
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',			'维可瓦罗'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_VICOVARO_MINOR',					'维可瓦罗'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_DESCRIPTION',	'维可瓦罗城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_ADJECTIVE',		'维可瓦罗的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_NAME',		'维可瓦罗宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION',	'所有大学+2 [ICON_Science] 科技值，+1 [ICON_GreatScientist] 大科学家点数。与学院相邻的驻扎单位可在一回合恢复全部生命值。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_1',
	'维可瓦罗是尼弗迦德帝国最南端的附庸国之一。她以其自己的魔法学院以及詹·卡尔维特皇帝在该地区首府建立的医学院而闻名。维可瓦罗人虽然已经尼弗迦德化了，但仍然为祖国的传统感到自豪。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_2',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_3',
	'这个国家的历史可以追溯到远古时代，当时下阿尔巴部落被其文化影响。 维可瓦罗的早期成就成为了未来尼弗迦德遗产的一部分。几个世纪以来，维可瓦罗也慢慢接受了尼弗迦德共和国的文化元素。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_4',
	'12世纪下半叶，维可瓦罗被托雷斯皇帝的军队占领，但入侵者被迫撤退。 然而，在目睹了被费格斯皇帝征服的爱托里亚的命运后，维可瓦罗贵族影响了他们的统治者，维可瓦罗则主动要求加入尼弗迦德。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_5',
	'在第二次北方战争期间，来自维可瓦罗的盾牌卫士老兵与爱托里亚军队并肩作战。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_6',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_7',
	'维可瓦罗与帝国的核心区域接壤，很可能与罗万公国和亚穆拉克公国接壤。土地温暖多山，气候适合种植曼德拉草。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_8',
	'社会和文化'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_9',
	'维可瓦罗的人民过着富裕、稳定的生活，只要他们尊重贵族和尼弗迦德。许多贵族在山区拥有大型、防御性强的城堡。他们教育自己的孩子，并将最聪明、最善于社交的孩子送到古劳皮安堡的皇家学院。毫无疑问，这些年轻人带着扎实的尼弗迦德礼仪知识和与尼弗迦德贵族的交往回到家乡。这一策略让维可瓦罗不仅在行省政府而且在尼弗迦德政府中都“朝中有人”。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_10',
	'琐事'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_11',
	'公国的名字可能是参照一个意大利的同名城市。'),
-----------------------------------------------
-- Religion
-----------------------------------------------
	('zh_Hans_CN',	'LOC_RELIGION_IPG_ARD_FEAINN',	'伟大日轮'	),

	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_1',
	'自托雷斯皇帝统治以来，大太阳（或尼弗迦德语 Ard Feainn，伟大日轮）一直是尼弗迦德帝国的主要宗教。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_2',
	'北方王国的居民对大太阳教派知之甚少。这个宗教的领袖是一位大祭司，也可能是尼弗迦德皇帝。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_3',
	'对大太阳的崇拜原本只是帝国众多宗教之一，只在核心地区流行。这种情况在大约一百年前费格斯皇帝前任的统治时期发生了变化，他发起了一系列重大改革。这位统治者正在寻找一个比仅仅统治王朝更好、更持久地团结王国的象征。通过巧妙地管理现金并给予祭司君主般的恩宠，他使该教派开始在整个帝国获得一批新的追随者。作为交换，皇帝要求神职人员绝对支持他的政策，这使祭司实际上成为另一种形式的文官。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_4',
	'随后，君主颁布了一项名为“三月八日诏书”的特别法令，授予该教派正式国教地位。虽然在篡位者统治期间它的权利被削弱，但在恩希尔·瓦·恩瑞斯和他的军队推翻了篡位者之后它的地位重新得到了提升。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_5',
	'该教派起源于精灵对自然的崇拜。主神是太阳，它是温暖和生命的赐予者，是人类的保护者，但也可能残忍和具有破坏性。自“三月八日诏书”起，它也成为了执政王朝的守护神。最重要的节日是春分和现任皇帝的生日，目前是 7 月 26 日。中央仪式在首都举行，由作为宗教领袖的大祭司执行。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_6',
	'在所有主要官员、指挥官和贵族都在场的情况下，在庄严的音乐的伴奏下，所有的节日都会隆重庆祝。正式仪式结束后，进行带有饮食的民间游戏。值得注意的是，许多与节日相关的习俗直接源自精灵传统。该教派的祭司在祈祷、庆典和节日期间穿着绣有金银的白色长袍；至于他们的便服，则是黑色文官服装。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_7',
	'成为伟大日轮的祭司只是帝国的另一条职业道路。完成神学院并通过考试也能保证获得“祭司”的正式头衔。随后，根据教育情况，初出茅庐的祭司可以进入其中一个小寺庙或直接进入当地政府的办公室。然后一切就取决于他履行职责的参与度……以及他的政治嗅觉。'),
	('zh_Hans_CN',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_8',
	'奇怪的是，在伟大日轮的祭司中没有任何人具有魔法或灵能能力——所有拥有这种能力的行家都会立即被引导到洛克格瑞姆的帝国魔法学院。');
