/*
	Civilization Text Entries en_US
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

INSERT OR REPLACE INTO LocalizedText
			(Language, Tag, Text)
VALUES

-----------------------------------------------
-- Civilization
-----------------------------------------------
	('en_US',	'LOC_CIVILIZATION_IPG_NILFGAARD_NAME',			'Nilfgaard'			),
	('en_US',	'LOC_CIVILIZATION_IPG_NILFGAARD_DESCRIPTION',	'Empire of Nilfgaard'	),
	('en_US',	'LOC_CIVILIZATION_IPG_NILFGAARD_ADJECTIVE',  	'Nilfgaardian'			),
-----------------------------------------------
-- Civilization Unique Ability
-----------------------------------------------
	('en_US',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME',				'Administration of the Provinces'				),
	('en_US',	'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION',	
	'Capturing a foreign city grants a free Builder in that city. Builders can spend charges to complete 15% of the [ICON_Production] Production cost of all Districts. Occupied cities have no yields penalty. Spies can choose from all possible promotions.'	),
-----------------------------------------------
-- Civilization Unique Infrastructure (District)
-----------------------------------------------
	('en_US',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',				'Nilfgaardian Imperial Camp'								),
	('en_US',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',
	'A military district unique to Nilfgaard that replaces the Encampment. It is much cheaper to build and grants +2 Loyalty. Each citizen in the Nilfgaardian Imperial Camp also yields +1 [ICON_Science] Science and +1 [ICON_Culture] Culture. All land units trained in this city gain +25% more combat experience.'	),

	('en_US',	'LOC_ABILITY_IMPERIAL_CAMP_TRAINED_UNIT_XP_DESCRIPTION',	'+25% Earned experience from Nilfgaardian Imperial Camp'	),
-----------------------------------------------
-- Civilization Unique Unit
-----------------------------------------------
	('en_US',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',	'Nauzicaa Brigade'	),
	('en_US',	'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',	 
	'Hard-hitting Nilfgaardian unique Medieval era heavy cavalry unit. It is very expensive to train and maintain, but can attack twice if [ICON_Movement] Movement allows.'	),

	('en_US',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_NAME',	'Magne Division'	),
	('en_US',	'LOC_UNIT_CALVEIT_MAGNE_DIVISION_DESCRIPTION',
	'Nilfgaardian unique Medieval era recon unit that replaces the Skirmisher, very cheap to train and maintain. Attacks melee and ignores enemy Zone of Control. When more than 4 tiles away from friendly territory gains +10 [ICON_Strength] Combat Strength and generates [ICON_Science] Science and [ICON_Culture] Culture from victories.'	),

	('en_US',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',	'Fire Scorpion'	),
	('en_US',	'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',	 
	'Nilfgaardian unique Renaissance era siege unit that replaces the Bombard. Unlocks earlier at Gunpowder and is cheaper to train.'	),

	('en_US',	'LOC_ABILITY_EMHYR_NAUZICAA_BRIGADE_EXTRA_ATTACK_DESCRIPTION',		'+1 additional attack per turn if [ICON_Movement] Movement allows.'	),
	('en_US',	'LOC_ABILITY_CALVEIT_MAGNE_DIVISION_DESCRIPTION',			'When more than 4 tiles away from friendly territory: +10 [ICON_Strength] Combat Strength and victories provide [ICON_Science] Science and [ICON_Culture] Culture.'	),

	('en_US',	'LOC_CALVEIT_MAGNE_DIVISION_AWAY_STRENGTH',		'+{1_Amount} Away from friendly territory.'	),
-----------------------------------------------
-- Mountains
-----------------------------------------------
	('en_US',	'LOC_NAMED_MOUNTAIN_TIR_TOCHAIR',		'Tir Tochair'	),
	('en_US',	'LOC_NAMED_MOUNTAIN_AMELL',				'Amell Mountains'			),
	('en_US',	'LOC_NAMED_MOUNTAIN_FIERY',				'Fiery Mountains'	),
-----------------------------------------------
-- Rivers
-----------------------------------------------
	('en_US',	'LOC_NAMED_RIVER_ALBA',				'Alba'				),
	('en_US',	'LOC_NAMED_RIVER_VELDA',			'Velda'				),
	('en_US',	'LOC_NAMED_RIVER_SYLTE',			'Sylte'				),
	('en_US',	'LOC_NAMED_RIVER_YELENA',			'Yelena'			),
	('en_US',	'LOC_NAMED_RIVER_WAGTAIL',			'Wagtail'			),
	('en_US',	'LOC_NAMED_RIVER_BLESSURE',			'Blessure'			),
	('en_US',	'LOC_NAMED_RIVER_SANSRETOUR',		'Sansretour'		),
-----------------------------------------------
-- Deserts
-----------------------------------------------
	('en_US',	'LOC_NAMED_DESERT_KORATH',				'Korath Desert'				),
	('en_US',	'LOC_NAMED_DESERT_ZERRIKANIAN',			'Zerrikanian Desert'		),
-----------------------------------------------
-- Lakes
-----------------------------------------------
	('en_US',	'LOC_NAMED_LAKE_MUREDACH',				'Muredach'				),
	('en_US',	'LOC_NAMED_LAKE_TARN_MIRA',				'Tarn Mira'				),
-----------------------------------------------
-- Cities
-----------------------------------------------
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_1',  'Nilfgaard'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_2',  'Winneburg'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_3',  'Darn Ruach'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_4',  'Darn Rowan'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_5',  'Darn Ymlac'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_6',  'Viroleda'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_7',  'Partya'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_8',  'Stygga'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_9',  'Amarillo'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_10',  'Tergano'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_11',  'Darn Dyffra'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_12',  'Loc Grim'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_13',  'Eiddon'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_14',  'La Pointe'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_15',  'Baccalà'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_16',  'Kharkiv'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_17',  'Salm'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_18',  'Claremont'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_19',  'Thurn'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_20',  'Neunreuth'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_21',  'Corvo'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_22',  'Unicorn'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_23',  'Dun Dâre'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_24',  'Malhoun'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_25',  'Fano'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_26',  'Jealousy'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_27',  'Dudno'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_28',  'Forgeham'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_29',  'Tyffi'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_30',  'Druigh'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_31',  'Glyswen'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_32',  'New Forge'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_33',  'Loredo'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_34',  'Caravista'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_35',  'Vedette'),
	('en_US',	'LOC_CITY_NAME_IPG_NILFGAARD_36',  'Dun Dâre'),
-----------------------------------------------
-- Citizens
-----------------------------------------------
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_1',	'Fergus'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_2',	'Tibor'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_3',	'Vreemde'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_4',	'Sweers'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_5',	'Vattier'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_6',	'Morteisen'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_7',	'Ffion'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_8',	'Torres'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_9',	'Shilard'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_MALE_10',	'Stefan'	),

	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_1',	'Carthia'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_2',	'Glynnis'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_3',	'Ola'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_4',	'Cynthia'),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_5',	'Isbel'		),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_6',	'Anna'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_7',	'Fringilla'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_8',	'Sylvia Anna'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_9',	'Vivienne'	),
	('en_US',	'LOC_CITIZEN_IPG_NILFGAARD_FEMALE_10',	'Assire'	),
-----------------------------------------------
-- Info
-----------------------------------------------
	('en_US',	'LOC_CIVINFO_IPG_NILFGAARD_LOCATION',		'The Continent, everything south of the Yaruga river'		),
	('en_US',	'LOC_CIVINFO_IPG_NILFGAARD_SIZE',			'Approx. 2.5 million km²'	),
	('en_US',	'LOC_CIVINFO_IPG_NILFGAARD_POPULATION',		'Circa 45 million'		),
	('en_US',	'LOC_CIVINFO_IPG_NILFGAARD_CAPITAL',		'Nilfgaard, City of Golden Towers'		),
-----------------------------------------------
-- Civilopedia
-----------------------------------------------
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_1',		
	'The Nilfgaardian Empire (Ceas''raet in Nilfgaardian language) is the most powerful empire in the history of the known world. It is located in the southern part of the Continent and boasts both a thriving economy and a strong, well-trained army with talented commanders. It has expanded mostly through the conquest of foreign countries, which were then turned into provinces of the Empire. The Empire''s inhabitants believe that "real" Nilfgaardians are only those born in the heart of the Empire, and not those born in the conquered provinces.'),	
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_2',		
	'The provinces are ruled by either stewards or kings (in cases in which a king willingly surrenders, he retains his throne but is subject to the Emperor or just a vassal). The empire has expanded throughout the years, conquering new lands and going as far to the north as the Yaruga River during the reign of Emperor Emhyr var Emreis.'),	
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_3',	
	'In the Northern Kingdoms, the Empire is portrayed as an overarching antagonist, with many free people of the North expressing hatred towards it with passion.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_4',	
	'NATIONAL EMBLEMS'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_5',	
	'The Great Sun, symbolizing solar radiance and solar heat, is the primary symbol of the Nilfgaardian people. It appears in imperial heraldry, on coins, banners of armed forces as well as the mark of the Viroledan swordsmiths.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_6',	
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_7',	
	'Nilfgaardians believe their history reaches back to the 2nd century. The first settlers mixed with the Black Seidhe, creating a nation consisting mostly of elven language, beliefs, customs and culture. Meanwhile, the valiant sheperds inhabiting scattered settlements on the Alba slowly incorporated the surrounding nations, appropriating their best traits like the culture, technology and military strategies, offering them safety and order in return. The two groups eventually merged during various conquests by neighbouring nations and periods of freedom, creating a unique heritage mixing the achievements of elves, Vicovarians, Etolians and several Alban tribes. At some point of their history, the Kingdom of Nilfgaard emerged.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_8',	
	'The monarchs were aided by a council of advisors, which became known as the Senate. Over time, the Senate has gained more and more power, becoming a legislative body. During this period Nilfgaardian influences started to expand and neighbouring lands were slowly Nilfgaardized and the peoples brought under the dominion of the empire, through the "diplomacy of steel", were expected to learn its official language and adopt elements of the victors'' culture.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_9',	
	'Eventually, a couple of realms outside the Lower Alba were incorporated into the realm, either willingly or by force. The title of Imperator appeared, at first only as position in the army. Known lands that were joined in that period were Rowan and Ymlac, apparently also Ruach, Daerlan, Magne and Winneburg.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_10',	
	'In the early 12th century Imperator Torres var Emreis overthrew the Senate and took absolute power. At first he referred to his realm only as a "kingdom" but during his later reign term "empire" was coined – and the Emperor with it. Torres'' reign also saw the adaptation, via the March 8th Edict, of the Great Sun (Ard Feainn) as the state religion and coat of arms of the Empire.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_11',	
	'Sometime after Torres'' death, likely in the early 1200s, Fergus var Emreis ascended the throne. However, he was considered by many to be a weak emperor. In 1216, Emperor Fergus var Emreis decided to use Etolia as an example of the future that awaits all enemies of the Empire. Nilfgaardian Army attacked and overwhelmed Etolia, annihilated its power structures and decimated the values defining Etolian life. Fergus subjected Gemmera in that year as well. Vicovarian nobles influenced their ruler and Vicovaro asked to join Nilfgaard willingly, on its own initiative. Fergus was ultimately overthrown by Usurper in 1233. During the coup, Fergus was killed by the Usurper while his son and heir, Emhyr, was cursed by the mage Braathens, who turned him into a humanoid hedgehog. Despite having dogs set on him, Emhyr managed to escape and, with help from his own acquaintances, left the Empire.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_12',	
	'During the Usurper''s reign, he proclaimed a national amnesty, diminished the cult of the Great Sun''s rights, and, in 1239, he annexed Ebbing. During this long conflict, Metinna, Nazair, and even Maecht were conquered by the Empire by the mid-1250s.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_13',	
	'In 1257 a uprising led by Ardal aep Dahy, Vilgefortz and other Emhyr''s supporters stormed the Imperial Palace and killed the Usurper. Emhyr var Emreis, the right heir to the throne who was banished from his country, entered once again in Nilfgaard and became the new Emperor, gaining the nickname "the White Flame Dancing on the Barrows of his Enemies" or in Nilfgaardian language, "Deithwen Addan yn Carn aep Morvudd".'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_14',	
	'SOCIETY'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_15',	
	'While the Empire''s population comprises several different cultures and nations, the authorities are keen on slow "Nilfgaardization" of minorities, that is replacing local values and customs with those of "proper Nilfgaardian", Lower Alban heritage. Internal migration within imperial borders are encouraged: colonies of Lower Alban settlers are established within troubled provinces, while non-Nilfgaardian peasants loyal to the Empire are encouraged to settle in newly-conquered realms through attractive offerts; rebellious regions are cleansed through enslavement or ethnic cleansing of groups deemed "problematic".'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_16',	
	'On the other hand, Nilfgaardian Empire in general is considered a safer home than most Northern Realms for many nonhuman races. Save for groups like Wood Elves, nonhumans living in the Empire consider imperial system harsh, but just.'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_17',	
	'TRIVIA'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_18',	
	'Nilfgaard draws many parallels with the Roman Empire of the real world: a vastly powerful empire that, with the use of disciplined armies, assimilates other "barbarian" cultures into itself through hard conquest. Also similar is the feeling of superiority among its delegates and subjects (who like to believe they are all of the Elder Blood - descendants of Lara Dorren). The cult of the Great Sun amongst Nilfgaardians can be related to the cult of Sol Invictus ("Invincible Sun") within the Roman Empire. Furthermore, the Witcher 2 clearly lampshades this idea. In one of the quest descriptions in chapter 1, Dandelion uses the phrase "When in Nilfgaard, do as the Nilfgaardians do" in exactly the same manner as we would use "When in Rome, do as the Romans do".'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_19',	
	'Origins of the capital''s and therefore the empire''s name are unclear. "Nilf" seems to be corrupted version of Icelandic "nifl" (fog, darkness, mist; like in "Niflheim"), while "gaard" could be either Dutch "gaard" (yard, garden), Danish "gaard/gård" (farm) or Old Norse "garðr" (yard, enclosure).'),
	('en_US',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_IPG_NILFGAARD_CHAPTER_HISTORY_PARA_20',	
	'In terms of color scheme and armor design, the Nilfgaardian military is very reminiscent of certain parts of the military of the Holy Roman Empire (not to be confused with the earlier Roman Empire), specifically their royal armor.'),
-----------------------------------------------
-- Unique Unit Civilopedia Entry
-----------------------------------------------
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_1',  	
	'Nauzicaa (or Nausicaa), also known as the "Skullheads" or "Death''s Heads", was a brigade of the 4th Cavalry Army, Nilfgaardian mounted troops commanded by Major general Markus Braibant. The brigade itself was commanded by Kees van Lo. They were equipped with war hammers and three and half feet long swords.'	),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_2',
	'The Nauzicaa, together with the 7th Daerlan Brigade, were the last troops sent into battle in the battle of Brenna. Lead by the Field Marshal Menno Coehoorn himself, these forces were supposed to rip through the Northerner armies, end up behind enemy lines and then attack them from the rear. This effort proved ultimately futile as the inexperienced Poor Fucking Infantry, under the voivode Bronibor, was surprisingly able to thwart the Nilfgaardian cavalry''s advance and stand their ground despite the heavy casualties suffered. From this point on, Nilfgaard''s defeat was inevitable and swift.'),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_3',
	'TRIVIA'),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_4',
	'The name may be a reference to Nausicaa, a female character in Odyssey.'),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_5',
	'Their "Skullheads" alias may be a reference to the SS-Totenkopfverbände.'),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_EMHYR_NAUZICAA_BRIGADE_CHAPTER_HISTORY_PARA_6',
	'Their "Death''s Heads" alias may be a reference to the Totenkopf Hussars from the Prussian Military, who wore similarly colored uniforms and insignia.'),

	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_1',
	'Magne Division was a division hailing from Magne, within the 4th Cavalry Army, Nilfgaardian mounted troops, commanded by Major General Markus Braibant.'),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_CALVEIT_MAGNE_DIVISION_CHAPTER_HISTORY_PARA_2',
	'When a Nilfgaardian cavalry officer steps out of line, he''s likely to get reassigned to the Korath Desert. A few months patrolling the endless sands of this "frying pan" will purge him of any hint of insubordination, and replace it with frantic willingness to do absolutely anything to avoid being sent back.'),

	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_1',  	
	'Zerrikanian fire scorpion is a Zerrikanian siege weapon often used by the empire of Nilfgaard during sieges. It''s pretty similar to a northern Ballista but instead of darts it shoots an unknown substance similar to a green fireball.'	),
	('en_US',	'LOC_PEDIA_UNITS_PAGE_UNIT_NILFGAARD_FIRE_SCORPION_CHAPTER_HISTORY_PARA_2',  	
	'"Name''s terribly misleading, makes it sound like some corpulent reddish arachnid, not an exquisitely engineered weapon of mass destruction... Not the best for taking the cities, but great for razing them down to the ground."'	),
-----------------------------------------------
-- Unique Infrastructure
-----------------------------------------------
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_1',
	'Nilfgaardian Army Group ''Center'' Camp is the headquarters of the Nilfgaardian Army in the Velen region in The Witcher 3. Pitched in a mere two weeks, the Army Group ''Center'' camp constitutes the quintessence of Nilfgaardian martial architecture.'),
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_2',
	'NILFGAARDIAN ARMY'),
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_3',
	'The Imperial Army of the Nilfgaardian Empire is, without a doubt, one of the best-trained fighting forces on the Continent. Boasting from the lower ranks to the higher nobles involved within the military, its soldiers, known as the black-clads, are well-versed in the art of combat. Under the complete control of the Nilfgaardian Imperator who leads it through a set of high-ranking officers under a Field marshal.'),
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_4',
	'During greater conquests and invasions, such as the Northern Wars, the army was divided into groups, such as Center Army Group, East Army Group and Verden Operations Group. During the second of the Northern Wars, the army count was ca. 320,000, with 300,000 attacking the kingdoms and about 20,000 remaining in the Empire to keep the peace and defend core provinces in case of an unexpected turn in war.'),
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_5',
	'Like many other armies, The Imperial Army is also in possession of siege weapons, including mangonels, Trebuchets, Zerrikanian fire scorpions, and rot tossers.'),
	('en_US',	'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_CHAPTER_HISTORY_PARA_6',
	'Unlike the Northern Kingdoms, slavery is commonplace among the Nilfgaardians; slaves, usually prisoners of war, are used not only for manual work, but even during combat, fighting for their freedom, at least according to their masters.'),
-----------------------------------------------
-- City State
-----------------------------------------------
	-- METINNA
	('en_US',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',			'Metinna'),
	('en_US',	'LOC_CITY_NAME_IPG_METINNA_MINOR',					'Metinna'),
	('en_US',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_DESCRIPTION',	'Metinna city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_ADJECTIVE',		'Metinnese'),
	('en_US',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_NAME',		'Metinna Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION',	'Light Cavalry units trained while suzerain of Metinna gain the "Metinna cavalrymen" ability permanently, which grants them +4 [ICON_Strength] Combat strength. Provides a free copy of [ICON_RESOURCE_Wine] Wine resource.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_1',
	'Metinna is one of the kingdoms to the south of Amell, currently a vassal to Nilfgaardian Empire and part of the Metinna Province. Comprised in large part of Mag Deira plains, for ages it has been a homeland for skilled cavalrymen and famous horse breeders. It is also a major trade hub between the north and the south.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_2',
	'ANCIENT HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_3',
	'The original inhabitants of these lands were werebbubbs, members of sophisticated race whose homelands comprised of modern-day Metinna, Nazair and Mag Turga. During the Age of Migration, they were driven out by elves who began to built their own civilization.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_4',
	'The Elder Folk inhabited primarily the Land of a Hundred Lakes, or Centloch. To this day the ruins of their palaces are haunted by elven ghosts of the past. One of the most well-known structures was probably the legendary basalt tower of Tor Zireael on the north shore of Tarn Mira, but by the 13th century all that remained of it were only few stones.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_5',
	'HUMAN REALM'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_6',
	'Humans settled in these lands at some point of the history. At least two major trade metropolises, Metinna and Neunreuth were established. A kingdom eventually arose around them, stemming its name from the first city. One of the most famous Metinnese monarchs was Queen Zivelina, a magic user who obtained the crown with the help of gnome Rumplestelt but lost it when denied the Law of Surprise.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_7',
	'The plains of Mag Deira became a home of the Markee people, the nomad horsemen who originated from the Velda delta. They founded expansive ranches here and started to raise cattle and the famous Metinnese ponies.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_8',
	'NILFGAARDIAN WARS'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_9',
	'In the late 12th century, Metinna was involved in a war with Nilfgaardians but neither it or its neighbour countries were conquered until the Usurper''s rule in the 13th century, during the Northern Wars. The local dynasty was allowed to govern with relative autonomy, and the province with its own officer corps was named after the kingdom.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_10',
	'Some time after the Nilfgaardian defeat at the Battle of Sodden Hill, the Metinnese rebelled during the so called Metinna rebellion. The uprising was however suppressed the same year by the junior commanders of the army, who were intended by Emhyr var Emreis to replace those who failed him at Sodden.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_11',
	'Hired Metinnese foot soldiers served in the Nilfgaardian Army at the First battle of Aldersberg and Sack of Vengerberg.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_12',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_13',
	'It is bordered by the Ebbing (and possibly the Great Sea) in the west, Geso to the east, the province of Nazair to the north, and Maecht, with which it forms the Province of Metinna, to the south. The region, one third of which is comprised of the plains of Mag Deira, is bounded to the north by the Yelena and to the south by the Sylte river.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_14',
	'SOCIETY AND CULTURE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_15',
	'Among the nations conquered by the Usurper the Metinnese are sometimes described as the most similar Lower Albans. They are skilled traders and tough cavalrymen; due to the Markee influences, it is said the Metinnese are born in the saddle. The population of the plains is considered wilder than the city dwellers; wrestlers from Mag Deira are often seen in Metinna''s rather unsanitary arenas.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_16',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_17',
	'The majority of Metinna''s income comes from the trade, centered around the metropolises. In the interior, on the plains of Mag Deira, there are expansive ranches raising cattle and so called Metinnese ponies. The Mettinese pony is white, extremely hardy, sure-footed, and intelligent - for a horse, of course. It is believed that the original stock was brought here by the Markee from the Velda delta. The tribute paid to Nilfgaard by the king of Metinna often takes a form of horses and horsemen.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_18',
	'Metinna is renowned for its wine, known as Metinna Rosé. Often described by connoisseurs as marvelous, it is a table wine with a rich bouquet. Like the Markee, it originated in wineries of the Velda delta, but was brought to Metinna and became a national drink of which the Metinnese are so proud so that one can engage in a shouting match or even a duel with a Toussaintois as a result of a wine discussion.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_METINNA_MINOR_CHAPTER_HISTORY_PARA_19',
	'Metinna produces esboda swords, considered to be amongst the lightest and sharpest cavalry blades made on the Continent.'),

	('en_US',	'LOC_ABILITY_METINNA_CAVALRYMEN_NAME',			'Metinna cavalrymen'),
	('en_US',	'LOC_ABILITY_METINNA_CAVALRYMEN_DESCRIPTION',	'+4 [ICON_Strength] permanent Combat strength.'),
	
	-- MAECHT
	('en_US',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',			'Maecht'),
	('en_US',	'LOC_CITY_NAME_IPG_MAECHT_MINOR',					'Maecht'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_DESCRIPTION',	'Maecht city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_ADJECTIVE',		'Maechtian'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_NAME',		'Maecht Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION',	'Spies executing the "Fabricate Scandal" espionage mission function 3 levels higher.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_1',
	'Maecht was a kingdom in the southern part of the continent, bordered by Metinna to the north, Geso to the east, and Ebbing to the south. However, in the 1250s it eventually fell to Nilfgaard and became part of the Province of Metinna during the Usurper''s reign.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_2',
	'Maecht maintains a pretense of autonomy where the citizens elect their king, even if the elections depend in fact rather on the Emperor''s decision.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_3',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_4',
	'King Akerspaark continued to rule after it was subjugated until 1258 when he died of acute pneumonia after being stabbed by hit men. An election took place and was won by Hoët, though Codringher suggested that Imperator Emhyr, who took back the Nilfgaardian throne just one year prior, have a deciding vote.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_5',
	'Sensing instability, Maechtian nobles, like Duke Rudiger, formed insurrection forces in Thurn but were soon put down by the Gemmerian Pacifiers in a punitive expedition. By 1267 Maecht was firmly bound to the Empire and its mercenaries partook in the Second Northern War.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_6',
	'NOTES'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_7',
	'Duny claimed the people of Maecht were very superstitious, though this could have been a ruse to explain why he didn''t want to go back home immediately after marrying Pavetta.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAECHT_MINOR_CHAPTER_HISTORY_PARA_8',
	'The original Polish edition of Time of Contempt contains only ambiguous description of the kingdom''s coat of arms, mentioning "silver fishes and crowns in shield divided quarterly blue and red". The more detailed description was provided by David French who translated the books to English.'),
	
	-- TOUSSAINT
	('en_US',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME',			'Toussaint'),
	('en_US',	'LOC_CITY_NAME_IPG_TOUSSAINT_MINOR',					'Beauclair'),
	('en_US',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_DESCRIPTION',	'Toussaint city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_ADJECTIVE',		'Toussaintois'),
	('en_US',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_NAME',		'Toussaint Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION',	'+3 [ICON_Culture] Culture to Plantations on a Luxury resource. +2 [ICON_Culture] extra Culture if placed on [ICON_RESOURCE_Wine] Wine.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_1',
	'Toussaint is a small autonomous duchy under the banner of the Empire of Nilfgaard, famous for its wines, enabled by the region''s volcanic soil and ideal combination of sunny and rainy days. Toussaint does not maintain a large standing army of its own, instead relying on a few regiments of knights-errant, watching the borders and roads in conjunction with Ducal Guard. Toussaint is also one of the few countries in the Continent which doesn''t have a Secret Service.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_2',
	'Despite being a vassal state of Nilfgaard, Toussaint maintains high level of autonomy and the Nilfgaardian Empire does not tend to impose imperial authority on its internal affair or violate its borders for the most part.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_3',
	'While the duchy''s surface may be fairy and serene, beneath the wine cellars it hides a gargantuan underground system of interconnecting ancient adits, mines and dungeons, as well as natural caverns and tunnels hollowed by lava, allegedly connected with the center of the earth.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_4',
	'PREHYSTORY AND ANCIENT TIMES'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_5',
	'For ages the undergrounds of modern-day Toussaint were inhabited by intelligent creatures like korreds, kilmulises, pryskirniks and many others, some of them unknown in witcher tomes even till the 13th century. In the 8th century BR (Before Resurrection) a group of Aen Seidhe elves founded their kingdom here with modern-day Beauclair as its capital. They built beautiful cities made of white marble and ivory.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_6',
	'HUMAN CONQUEST'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_7',
	'A couple of decades after the First Landing, elven king Divethaf''s realm faced a invasion led by Nordling chieftain Ludovic. In 781 the elves abandoned their ivory cities and left for the Amell mountains, taking with them all that they could and destroying everything else. Whatever they could not take and did not manage to demolish or burn, they cursed. Ludovic marched into the foothills with his army, demanding Divethaf to surrender and proclaim him as king. A battle ensued after the elf refused and Aen Seidhe army was slain. Weeping over the loss, Divethaf agreed to pay the homage. Next year humans decided to celebrate the anniversary of the victory with a pogrom, genociding all the remnants at the Mount Gorgon slopes. The last untouched by humans elven trace was the hidden necropoly of Tir ná Béa Arainne which continued to be used over the course of subsequent ages, protected by Aen Saevherne.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_8',
	'In the following centuries the main occupation of early Toussantois was apparently mining, as they hollowed many adits and mines. Several dungeons were also constructed then, probably to imprison political enemies – the land was parcellated among several petty lords and dukes. One of such lordships was Epicéa on Gorgon Foothils, near the very place of Divethaf''s defeat.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_9',
	'One of the most important and landscape-changing events of this period was Nazairi Duke Adam''s attempt to regulate the flow of the Sansretour River to his likeness – and unwilling creation of the Sansretour Marsh in the process.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_10',
	'REFORMS'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_11',
	'In the 12th century the region witnessed its first reforms, initiated by Duke Henri III. Admiring distant lands at Lower Alba he tried to civilize the realm, e.g. by changes in the punitive law.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_12',
	'At the middle point of the century the power in the country was consolidated by Duchess Adela Marta. She ordered the renovation of the elven capital palace and moved her seat there, establishing the city of Beauclair. She planted the seeds of chivalric traditions in the Duchy by organising a tourney for her suitors, rewarding the qualities she valued most in men – Strength, Valor and Cunning. On her journey south she met the youngest son of Nilfgaardian Emperor Torres and wed him, creating a bond between Toussaint and the Nilfgaardian Empire.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_13',
	'Carolina Roberta, Ademarta''s daughter, continued the reforms. She forbade the use of pointed knives during the feasts, as she found the custom of using them to pick one''s teeth barbarous. She was also the one who recognized the cult of Lebioda, brought here by Saint Plegmund.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_14',
	'13TH CENTURY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_15',
	'The duchy was ruled by Caroberta''s granddaughter Anna Henrietta at least since the 1258 when she married duke Raymund. Despite having a husband it was she who held the greater estime of her subjects. However, since Raymund''s death in 1265 Anarietta had been kept unaware of the world''s events by her councelors due to her supposed emotional instability and learnt that the Northern War II had broken up only in late 1267 when informed of it by Geralt''s hanza. For this treason she imprisoned minister Tremblay in the tower.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_16',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_17',
	'Toussaint is located between three mountain ranges: Amell, Tir Tochair and Fiery Mountains. The volcanic soil left here by the region''s warm past allowed the cultivation of grapevine. Another relicts of the yore are now-dry lava tubes which, joint with caves and humanoid-made dungeons, form the duchy''s underground system.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_18',
	'SOCIETY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_19',
	'The above-ground part of the region is inhabited predominantly by humans of Nordling origin. Underground parts remained unsearched to at least 13th century and are inhabited by gremlins, kilmulises, korreds, pryskirniks, vampires and a number of species yet unknown to science.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_20',
	'CULTURE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_21',
	'Tradition is a holy thing in Toussaint. Holidays, the most important of them being Wine Vat, are keenly observed.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_22',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_23',
	'In the ancient times the region had a mining industry. Since the middle point of the 12th century however, the major area of the duchy''s economy has been wine industry and the closed adits and shafts are being slowly colonized by monsters.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_24',
	'TRIVIA'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_25',
	'Toussaint is the French name for the All Saints'' Day. It is also the name of a commune in Upper Normandy in the northern part of France.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_26',
	'In the Blood and Wine expansion, many of its inhabitants will speak French at times. This includes grammar; one letter mockingly calls the Italian wine Est est (Latin for "is is") "Était Était," French for "was was" or "used to be used to be".'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_27',
	'Beauclair''s architecture is based on the mannerist architecture of Zamość, Poland.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_28',
	'The culture is based on the mediterranean regions in Italy, Spain, and southern France.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_TOUSSAINT_MINOR_CHAPTER_HISTORY_PARA_29',
	'The Ducal Guard wears morions, helmets of Spanish origin.'),
	
	-- GEMMERA
	('en_US',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',			'Gemmera'),
	('en_US',	'LOC_CITY_NAME_IPG_GEMMERA_MINOR',					'Gemmera'),
	('en_US',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_DESCRIPTION',	'Gemmera city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_ADJECTIVE',		'Gemmerian'),
	('en_US',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_NAME',		'Gemmera Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION',	'+5 [ICON_Strength] Combat strength to all units against Free Cities. +2 Loyalty per turn in cities with a garrisoned unit.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_1',
	'Gemmera or Gemmeria was a former kingdom and later one of the provinces in the Nilfgaardian Empire. It was known for its fierce warriors, like Gemmerian Pacifiers.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_2',
	'Through ages, some Nordling cartographers claimed that Gemmera was the southernmost part of the Continent and that the lands below belonged to another landmass, but most of the others considered Ebbing to be the southern boundary. By the time of the Northern War II however these beliefs were apparently abandoned.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_3',
	'ANCIENT HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_4',
	'Ages ago, the coastline region of Gemmera had an elven presence, as evidenced by the Tower of the Winds. In the hills there was at least one dwarven mine, along with an ancient forge and foundry.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_5',
	'Inhabited by fierce and harsh barbarious folk, for ages had the Kingdom of Gemmera been a nuisance for neighbouring countries. It is known that at least one Gemmeran invasion was aimed at the Nilfgaardian Empire during the reign of Emperor Torres.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_6',
	'In the second half of 12th century, Gemmera was facing increasing influences of the Empire. They were held at bay by the usurper Duke Ponderic until he was dethroned by the witcher Dragonfly of Stygga and the son of his murdered brother Woderic.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_7',
	'NILFGAARDIAN PROVINCE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_8',
	'Gemmera was finally subjugated in 1226 by Emperor Fergus var Emreis. Thirsty of its large seams of dimeritium, he gathered resources and, joined by forces of Etolia and Vicovaro, invaded the country and rooted out nearly the whole population of the rocky regions, leaving little more than wandering goat herders in some areas. After the conquest, the fiercest of Gemmeran warriors joined the imperial armies for loot and mayhem.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_9',
	'Gemmeran mages were unwilling to register themselves at the imperial service. This problem led the Usurper and Isaiah Coehoorn to found an organization known as the Mage Hunters, members of which were to find the unregistered Magic users and take them to the capital for trial. In order to equip the organization the Emperor called together the most successful mine owners in the Empire and offered an exclusive contract to the one who could discover the largest seam of dimeritium – and the only ones were found in Gemmera.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_10',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_11',
	'Gemmera can be divided between coastal region, forests, steppelands and arid, rocky hills. There are no large metropolises nor highways, but a few towns and chains of villages interconnected via well-established dirt roads can be found.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_12',
	'SOCIETY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_13',
	'Even if barbarous and following club law the most, Gemmerans had a monarchy consisting of kings and dukes with notable power, as well as courts with mage and druid advisors.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_14',
	'People are very cordial and sincere, but likewise violent and cruel. They are great riders, galloping on their stallions with passion and love. Unfortunately, with such love they engage in brigandage and appropriation of other people''s property. There is even a cruel saying "to play in a Gemmerian way", which means brutal gang rape in front of the victim''s family.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_15',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GEMMERA_MINOR_CHAPTER_HISTORY_PARA_16',
	'The region is famous for the production of potatoes, gravy and hard cheese. In the hills, where rich dimeritium deposits were found, imperial mines were established.'),

	('en_US',	'LOC_GEMMERIAN_PACIFIERS_NAME',			'Gemmerian Pacifiers'),
	
	-- VICOVARO
	('en_US',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',			'Vicovaro'),
	('en_US',	'LOC_CITY_NAME_IPG_VICOVARO_MINOR',					'Vicovaro'),
	('en_US',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_DESCRIPTION',	'Vicovaro city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_ADJECTIVE',		'Vicovarian'),
	('en_US',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_NAME',		'Vicovaro Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION',	'+2 [ICON_Science] Science and +1 [ICON_GreatScientist] Great Scientist point from all Universities. Units adjacent to a Campus district with a University heal fully in one turn.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_1',
	'Vicovaro is one of the southernmost vassal states in the Nilfgaardian Empire. It is famous for its own Academy of Magic, as well as the medical academy founded by Emperor Jan Calveit in the region''s capital. Vicovarians, while Nilfgaardized, are still proud of their motherland''s heritage.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_2',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_3',
	'The country''s history goes back to ancient times, when Lower Alban tribes were influenced by its culture. The early Vicovarian achievements became a part of the future Nilfgaardian heritage. Over the course of centuries, Vicovaro had slowly embraced elements of the Nilfgaardian Republic''s culture as well.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_4',
	'In the second half of 12th century Vicovaro was seized by Emperor Torres''s armies, but the invader was forced to retreat. However, after witnessing the fate of Etolia conquered by Emperor Fergus, Vicovarian nobles influenced their ruler and Vicovaro asked to join Nilfgaard willingly, on its own initiative.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_5',
	'Veteran shieldbearers from Vicovaro marched alongside Etolian troops during the Northern War II.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_6',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_7',
	'Vicovaro borders the core region of the Empire and likely the duchies of Rowan and Ymlac. The land is warm and hilly and the climate allows the cultivation of the mandrake.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_8',
	'SOCIETY AND CULTURE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_9',
	'People of Vicovaro live plentiful, stable lives, as long as they pay due respect to the nobles and to Nilfgaard. Many nobles have large, defensible castles in the mountains. They educate their children and send the smartest and most socially adept to the Imperial Academy at Castel Graupian. It is no mistake that these young people return home with a solid knowledge of Nilfgaardian etiquette and contacts in the Nilfgaardian nobility. This strategy allows Vicovaro to place many Vicovarians in not only the provincial government but the Nilfgaardian government as well.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_10',
	'TRIVIA'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_VICOVARO_MINOR_CHAPTER_HISTORY_PARA_11',
	'The name of the duchy could be a reference to an Italian city with the same name.'),
-----------------------------------------------
-- Religion
-----------------------------------------------
	('en_US',	'LOC_RELIGION_IPG_ARD_FEAINN',	'Ard Feainn'	),

	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_1',
	'The Great Sun (or in the Nilfgaardian language, Ard Feainn) has been the major religion in the Nilfgaardian Empire since the rule of Emperor Torres.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_2',
	'The inhabitants of the Northern Kingdoms know very little about the cult of the Great Sun. The head of this religion is a high priest, which may also be the Nilfgaardian Emperor.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_3',
	'The cult of the Great Sun was formerly only one of various religions in the Empire, popular only in its core regions. This situation changed during reign of the predecessor of Emperor Fergus, about a hundred years ago, who initiated a series of major reforms. The ruler was looking for a symbol which would unite the realm better and more permanently than only the ruling dynasty. By skillfully managing with cash and giving priests his monarchic favor, he made the cult begin to gain a new crowd of followers throughout the whole Empire. In exchange, the Emperor demanded absolute support for his policies from the clergy, practically making priesthood another form of civil service.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_4',
	'Then the monarch issued a special decree called "March 8th Edict" which granted the cult the status of official state religion. Though during reign of the Usurper its rights were diminished, its position increased after Emhyr var Emreis and his army overthrew the usurper.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_5',
	'The cult has its roots in the Elven cult of nature. The primary deity is the Sun, giver of warmth and life, protector of humankind, but also capable of being cruel and destructive. Since the "March 8th Edict" it has also been the patron of the ruling dynasty. The most important holidays are the Equinoxes and birthday of the current Imperator, currently July 26. The central ceremonies are held in the capital, performed by the Imperator acting as the High Priest, head of the religion.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_6',
	'All holidays are celebrated with great pomp, to the accompaniment of solemn music and in the presence of all major officials, commanders, and aristocrats. After official ceremonies, folk games with food and beverage take place. It is noteworthy that a number of customs related with the holidays are derived directly from Elven tradition. Priests of the cult wear white raiments embroidered in gold and silver during devotions, celebrations, and holidays; as casual clothes they wear black civilian dress.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_7',
	'Being a priest of the Great Sun is just another career path in the Empire. Finishing a theological college and passing the exams guarantees gaining an official title of "priest". Subsequently, depending on education, the fledgling priest can get to one of the minor temples or directly to the local Governor''s bureau. Then everything depends on his involvement in fulfilling the duties... and his political sense.'),
	('en_US',	'LOC_PEDIA_RELIGIONS_PAGE_RELIGION_IPG_ARD_FEAINN_CHAPTER_HISTORY_PARA_8',
	'Curiously, there is no persons with magic or psionic abilities among the Great Sun'' priests - all adepts possessing such abilities are immediately directed to the Imperial Magical Academy in Loc Grim.');
