--==========================================================================================================================
-- ICONS
--==========================================================================================================================
-- IconTextureAtlases
	
INSERT INTO IconTextureAtlases	
		(Name,											IconSize,	IconsPerRow,	IconsPerColumn,		Filename)
		-- UNIT
VALUES  ('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	256,		5,				3,					'MonopolyPlus_Portraits_256.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	200,		5,				3,					'MonopolyPlus_Portraits_200.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	95,			5,				3,					'MonopolyPlus_Portraits_95.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	70,			5,				3,					'MonopolyPlus_Portraits_70.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	50,			5,				3,					'MonopolyPlus_Portraits_50.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	38,			5,				3,					'MonopolyPlus_Portraits_38.dds'),
		-- UNIT FLAG
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		256,		2,				1,					'MonpolyPlus_UnitFlags_256.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		80,			2,				1,					'MonpolyPlus_UnitFlags_80.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		50,			2,				1,					'MonpolyPlus_UnitFlags_50.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		38,			2,				1,					'MonpolyPlus_UnitFlags_38.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		32,		 	2,				1,					'MonpolyPlus_UnitFlags_32.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		22,		 	2,				1,					'MonpolyPlus_UnitFlags_22.dds'),
		--Improvement
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		256,	 	3,				2,					'MonopolyPlus_Improvements_256.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		80,	 		3,				2,					'MonopolyPlus_Improvements_80.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		70,	 		3,				2,					'MonopolyPlus_Improvements_70.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		55,	 		3,				2,					'MonopolyPlus_Improvements_55.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		50,	 		3,				2,					'MonopolyPlus_Improvements_50.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		48,	 		3,				2,					'MonopolyPlus_Improvements_48.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		45,	 		3,				2,					'MonopolyPlus_Improvements_45.dds'),
		('ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		38,	 		3,				2,					'MonopolyPlus_Improvements_38.dds');
		
-- IconDefinitions	
INSERT OR REPLACE INTO IconDefinitions	
		(Name,														Atlas, 											'Index')
		--INVESTOR PORTRAIT
VALUES	('ICON_UNIT_LEU_INVESTOR_PORTRAIT',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	0),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_INVESTOR_PORTRAIT',		'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	1),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_INVESTOR_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	2),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_INVESTOR_PORTRAIT',		'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	3),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_INVESTOR_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	4),
		--TYCOON PORTRAIT
		('ICON_UNIT_LEU_TYCOON_PORTRAIT',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	10),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	11),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	12),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	13),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	14),
		--TYCOON PORTRAIT RENAISSANCE
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_RENAISSANCE',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	10),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_RENAISSANCE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	11),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_RENAISSANCE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	12),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_RENAISSANCE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	13),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_RENAISSANCE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	14),
		--TYCOON PORTRAIT INDUSTRIAL
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_INDUSTRIAL',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_INDUSTRIAL',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_INDUSTRIAL',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	7),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_INDUSTRIAL',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	8),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_INDUSTRIAL',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	9),
		--TYCOON PORTRAIT ATOMIC
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_ATOMIC',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_ATOMIC',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_ATOMIC',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	7),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_ATOMIC',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	8),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_ATOMIC',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	9),
		--TYCOON PORTRAIT MODERN
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_MODERN',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	7),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	8),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	9),
		---TYCOON PORTRAIT INFORMATION
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_INFORMATION',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_INFORMATION',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_INFORMATION',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	7),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_INFORMATION',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	8),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_INFORMATION',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	9),
		---TYCOON PORTRAIT INFORMATION
		('ICON_UNIT_LEU_TYCOON_PORTRAIT_ERA_FUTURE',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_FUTURE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_LEU_TYCOON_PORTRAIT_ERA_FUTURE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	7),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LEU_TYCOON_PORTRAIT_ERA_FUTURE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	8),
		('ICON_ETHNICITY_ASIAN_UNIT_LEU_TYCOON_PORTRAIT_ERA_FUTURE',			'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_PORTRAITS',	9),
		-- INVESTOR FLAG
		('ICON_UNIT_LEU_INVESTOR',									'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		0),
		('ICON_UNIT_LEU_INVESTOR_WHITE',							'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		0),
		-- TYCOON FLAG
		('ICON_UNIT_LEU_TYCOON',									'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		1),
		('ICON_UNIT_LEU_TYCOON_WHITE',								'ICON_ATLAS_LEU_MONPOLYPLUS_UNIT_FLAGS',		1),
		--IMPROVEMENTS
		('ICON_IMPROVEMENT_LEU_WAREHOUSE',							'ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		0),
		('ICON_IMPROVEMENT_LEU_CONTAINER_PORT',						'ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		1),
		('ICON_IMPROVEMENT_LEU_STATION',							'ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		3),
		('ICON_IMPROVEMENT_LEU_TRANSNATIONAL',						'ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		4),
		('ICON_IMPROVEMENT_LEU_TRANSNATIONAL_SEA',					'ICON_ATLAS_LEU_MONPOLYPLUS_IMPROVEMENTS',		2);
		

--==========================================================================================================================
--==========================================================================================================================