-- UC_Light_Config
-- Author: JNR
--------------------------------------------------------------

-- PlayerItems
--------------------------------------------------------------
UPDATE PlayerItems SET Description='LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR_LIGHT'				WHERE Type='BUILDING_MADRASA';
UPDATE PlayerItems SET Description='LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION_UC_JNR_LIGHT'			WHERE Type='BUILDING_GRAND_BAZAAR';
UPDATE PlayerItems SET Description='LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR_LIGHT'				WHERE Type='BUILDING_TLACHTLI';
UPDATE PlayerItems SET Description='LOC_BUILDING_ELECTRONICS_FACTORY_DESCRIPTION_UC_JNR_LIGHT'	WHERE Type='BUILDING_ELECTRONICS_FACTORY';
UPDATE PlayerItems SET Description='LOC_BUILDING_STAVE_CHURCH_DESCRIPTION_UC_JNR_LIGHT'			WHERE Type='BUILDING_STAVE_CHURCH';
UPDATE PlayerItems SET Description='LOC_BUILDING_PRASAT_DESCRIPTION_UC_JNR_LIGHT'				WHERE Type='BUILDING_PRASAT';
UPDATE PlayerItems SET Description='LOC_BUILDING_FILM_STUDIO_DESCRIPTION_UC_JNR_LIGHT'			WHERE Type='BUILDING_FILM_STUDIO';
--------------------------------------------------------------