
UPDATE Buildings
SET PrereqCivic = 'CIVIC_NATURAL_HISTORY' WHERE BuildingType = 'BUILDING_SANCTUARY';

UPDATE Buildings
SET PrereqCivic = 'CIVIC_CIVIL_ENGINEERING' WHERE BuildingType = 'BUILDING_FERRIS_WHEEL';

UPDATE Districts
SET PrereqCivic = 'CIVIC_CIVIL_ENGINEERING' WHERE DistrictType = 'DISTRICT_WATER_ENTERTAINMENT_COMPLEX';


