INSERT INTO IconTextureAtlases
		(Name,												IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		32,			1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_32.dds'),
		('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		38,			1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_38.dds'),
		('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		50,			1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_50.dds'),
		('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		80,			1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_80.dds'),
		('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		128,		1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_128.dds'),
		('ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',		256,		1,				1,				'ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_256.dds'),

		
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			256,		1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_256.dds'			),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			80,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_80.dds'			),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			50,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_50.dds'			),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			38,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_38.dds'			),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			32,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_32.dds'			),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',			22,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_22.dds'			),
		
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		256,		1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_256.dds'		),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		200,		1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_200.dds'		),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		95,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_95.dds'		),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		70,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_70.dds'		),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		50,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_50.dds'		),
		('ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',		38,			1,				1,				'ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT_38.dds'		);


		
--------------------------------------------------------------
-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,														Atlas,													'Index')
VALUES	('ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA',			'ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',			0),
		('ICON_BUILDING_PHANTA_GREAT_WILD_GOOSE_PAGODA_FOW',		'ICON_ATLAS_PHANTA_GREAT_WILD_GOOSE_PAGODA',			0),
		('ICON_UNIT_PHANTA_TRIPITAKA_MASTER',						'ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_FLAG',				0),
		('ICON_UNIT_PHANTA_TRIPITAKA_MASTER_PORTRAIT',				'ICON_ATLAS_PHANTA_TRIPITAKA_MASTER_PORTRAIT',			0);

--------------------------------------------------------------