INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		32,			1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_32.dds'),
		('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		38,			1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_38.dds'),
		('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		50,			1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_50.dds'),
		('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		80,			1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_80.dds'),
		('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		128,		1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_128.dds'),
		('ICON_ATLAS_PHANTA_OSAKA_CASTLE',		256,		1,				1,				'ICON_BUILDING_PHANTA_OSAKA_CASTLE_256.dds'),

		('ICON_ATLAS_PHANTA_RONIN_FLAG',		256,		1,				1,				'ICON_UNIT_PHANTA_RONIN_256.dds'			),
		('ICON_ATLAS_PHANTA_RONIN_FLAG',		80,			1,				1,				'ICON_UNIT_PHANTA_RONIN_80.dds'			),
		('ICON_ATLAS_PHANTA_RONIN_FLAG',		50,			1,				1,				'ICON_UNIT_PHANTA_RONIN_50.dds'			),
		('ICON_ATLAS_PHANTA_RONIN_FLAG',		38,			1,				1,				'ICON_UNIT_PHANTA_RONIN_38.dds'			),
		('ICON_ATLAS_PHANTA_RONIN_FLAG',		32,			1,				1,				'ICON_UNIT_PHANTA_RONIN_32.dds'			),
		('ICON_ATLAS_PHANTA_RONIN_FLAG',		22,			1,				1,				'ICON_UNIT_PHANTA_RONIN_22.dds'			);
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,										Atlas,								'Index')
VALUES	('ICON_BUILDING_PHANTA_OSAKA_CASTLE',		'ICON_ATLAS_PHANTA_OSAKA_CASTLE',	0),
		('ICON_BUILDING_PHANTA_OSAKA_CASTLE_FOW',	'ICON_ATLAS_PHANTA_OSAKA_CASTLE',	0),
		('ICON_UNIT_PHANTA_RONIN',					'ICON_ATLAS_PHANTA_RONIN_FLAG',		0),
		('ICON_UNIT_PHANTA_RONIN_PORTRAIT',			'ICON_ATLAS_UNIT_PORTRAITS',		41);

--------------------------------------------------------------