-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_LNGLEAT_HDGE_MAZE',					'MODFEAT_LNGLEAT_HDGE_MAZE_UNLOCK'),

		('BUILDING_LNGLEAT_HDGE_MAZE',					'MODFEAT_LNGLEAT_HDGE_MAZE_APPEAL'),
		('BUILDING_LNGLEAT_HDGE_MAZE',					'MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_WONDER'),
		('BUILDING_LNGLEAT_HDGE_MAZE',					'MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_MAZE'),

		('BUILDING_LNGLEAT_HDGE_MAZE',					'MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT');
		
INSERT OR REPLACE INTO ImprovementModifiers (ImprovementType, ModifierId)
VALUES	('IMPROVEMENT_HDGE_MAZE',						'MODFEAT_HDGE_MAZE_UNIT_MOVEMENT');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	('MODFEAT_LNGLEAT_HDGE_MAZE_UNLOCK',			'MODIFIER_PLAYER_ADJUST_VALID_IMPROVEMENT',	NULL),
		
		('MODFEAT_LNGLEAT_HDGE_MAZE_APPEAL',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',	NULL),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_WONDER',	'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',	NULL),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_MAZE',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',	NULL),
		
		('MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT',		'MODIFIER_ALL_UNITS_ATTACH_MODIFIER',		'VARU_ADJACENT_AT_WAR_REQUIREMENTS'),
		('MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT_M',	'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT',		NULL),
		('MODFEAT_HDGE_MAZE_UNIT_MOVEMENT',				'MODIFIER_ALL_UNITS_ATTACH_MODIFIER',		'VARU_ADJACENT_AT_WAR_REQUIREMENTS'),
		('MODFEAT_HDGE_MAZE_UNIT_MOVEMENT_M',			'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT',		NULL);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_LNGLEAT_HDGE_MAZE_UNLOCK',			'ImprovementType',	'IMPROVEMENT_HDGE_MAZE'),
		
		('MODFEAT_LNGLEAT_HDGE_MAZE_APPEAL',			'Amount',			2),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_WONDER',	'BoostsWonders',	1),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_WONDER',	'ScalingFactor',	200),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_MAZE',		'ImprovementType',	'IMPROVEMENT_HDGE_MAZE'),
		('MODFEAT_LNGLEAT_HDGE_MAZE_TOURISM_MAZE',		'ScalingFactor',	200),

		('MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT',		'ModifierId',		'MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT_M'),
		('MODFEAT_LNGLEAT_HDGE_MAZE_UNIT_MOVEMENT_M',	'Amount',			-2),
		('MODFEAT_HDGE_MAZE_UNIT_MOVEMENT',				'ModifierId',		'MODFEAT_HDGE_MAZE_UNIT_MOVEMENT_M'),
		('MODFEAT_HDGE_MAZE_UNIT_MOVEMENT_M',			'Amount',			-1);