/*
	Core Leader Configuration
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

-----------------------------------------------
-- Players (Base Game / Vanilla)
-----------------------------------------------
--INSERT INTO Players (CivilizationType, CivilizationName, CivilizationIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderType, LeaderName, LeaderIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground)
--VALUES	(	
		-- Civilization
--		'CIVILIZATION_IPG_NILFGAARD', -- CivilizationType
--		'LOC_CIVILIZATION_IPG_NILFGAARD_NAME', -- CivilizationName
--		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationIcon
--		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME', -- CivilizationAbilityName
--		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION', -- CivilizationAbilityDescription
--		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationAbilityIcon
		
		-- Leader
--		'LEADER_IPG_EMHYR', -- LeaderType
--		'LOC_LEADER_IPG_EMHYR_NAME', -- LeaderName
--		'ICON_LEADER_IPG_EMHYR', -- LeaderIcon (Portrait)
--		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_NAME', -- LeaderAbilityName
--		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_DESCRIPTION', -- LeaderAbilityDescription
--		'ICON_LEADER_IPG_EMHYR', -- LeaderAbilityIcon
--		'LEADER_IPG_EMHYR_NEUTRAL',
--		'LEADER_IPG_EMHYR_BACKGROUND'
--		);
-----------------------------------------------
-- Players (Rise & Fall)
-----------------------------------------------
/*
INSERT INTO Players (Domain, CivilizationType, CivilizationName, CivilizationIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderType, LeaderName, LeaderIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground)
VALUES	(	
		-- Civilization
		'Players:Expansion1_Players', -- Domain
		'CIVILIZATION_IPG_NILFGAARD', -- CivilizationType
		'LOC_CIVILIZATION_IPG_NILFGAARD_NAME', -- CivilizationName
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationIcon
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME', -- CivilizationAbilityName
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION', -- CivilizationAbilityDescription
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationAbilityIcon
		
		-- Leader
		'LEADER_IPG_EMHYR', -- LeaderType
		'LOC_LEADER_IPG_EMHYR_NAME', -- LeaderName
		'ICON_LEADER_IPG_EMHYR', -- LeaderIcon (Portrait)
		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_NAME', -- LeaderAbilityName
		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_DESCRIPTION', -- LeaderAbilityDescription
		'ICON_LEADER_IPG_EMHYR', -- LeaderAbilityIcon
		'LEADER_IPG_EMHYR_SELECT_NEUTRAL',
		'LEADER_IPG_EMHYR_BACKGROUND'
		),
		(	
		-- Civilization
		'Players:Expansion1_Players', -- Domain
		'CIVILIZATION_IPG_NILFGAARD', -- CivilizationType
		'LOC_CIVILIZATION_IPG_NILFGAARD_NAME', -- CivilizationName
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationIcon
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME', -- CivilizationAbilityName
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION', -- CivilizationAbilityDescription
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationAbilityIcon
		
		-- Leader
		'LEADER_IPG_CALVEIT', -- LeaderType
		'LOC_LEADER_IPG_CALVEIT_NAME', -- LeaderName
		'ICON_LEADER_IPG_CALVEIT', -- LeaderIcon (Portrait)
		'LOC_TRAIT_LEADER_NAZAIRI_AVENGER_NAME', -- LeaderAbilityName
		'LOC_TRAIT_LEADER_NAZAIRI_AVENGER_DESCRIPTION', -- LeaderAbilityDescription
		'ICON_LEADER_IPG_CALVEIT', -- LeaderAbilityIcon
		'LEADER_IPG_CALVEIT_SELECT_NEUTRAL',
		'LEADER_IPG_CALVEIT_BACKGROUND'
		);
*/
-----------------------------------------------
-- Players (Gathering Storm)
-----------------------------------------------
INSERT INTO Players (Domain, CivilizationType, CivilizationName, CivilizationIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderType, LeaderName, LeaderIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground)
VALUES	(	
		-- Civilization
		'Players:Expansion2_Players', -- Domain
		'CIVILIZATION_IPG_NILFGAARD', -- CivilizationType
		'LOC_CIVILIZATION_IPG_NILFGAARD_NAME', -- CivilizationName
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationIcon
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME', -- CivilizationAbilityName
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION', -- CivilizationAbilityDescription
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationAbilityIcon
		
		-- Leader
		'LEADER_IPG_EMHYR', -- LeaderType
		'LOC_LEADER_IPG_EMHYR_NAME', -- LeaderName
		'ICON_LEADER_IPG_EMHYR', -- LeaderIcon (Portrait)
		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_NAME', -- LeaderAbilityName
		'LOC_TRAIT_LEADER_DEITHWEN_ADDAN_DESCRIPTION', -- LeaderAbilityDescription
		'ICON_LEADER_IPG_EMHYR', -- LeaderAbilityIcon
		'LEADER_IPG_EMHYR_SELECT_NEUTRAL',
		'LEADER_IPG_EMHYR_BACKGROUND'
		),
		(	
		-- Civilization
		'Players:Expansion2_Players', -- Domain
		'CIVILIZATION_IPG_NILFGAARD', -- CivilizationType
		'LOC_CIVILIZATION_IPG_NILFGAARD_NAME', -- CivilizationName
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationIcon
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_NAME', -- CivilizationAbilityName
		'LOC_TRAIT_CIVILIZATION_ADMINISTRATION_PROVINCES_DESCRIPTION', -- CivilizationAbilityDescription
		'ICON_CIVILIZATION_IPG_NILFGAARD', -- CivilizationAbilityIcon
		
		-- Leader
		'LEADER_IPG_CALVEIT', -- LeaderType
		'LOC_LEADER_IPG_CALVEIT_NAME', -- LeaderName
		'ICON_LEADER_IPG_CALVEIT', -- LeaderIcon (Portrait)
		'LOC_TRAIT_LEADER_NAZAIRI_AVENGER_NAME', -- LeaderAbilityName
		'LOC_TRAIT_LEADER_NAZAIRI_AVENGER_DESCRIPTION', -- LeaderAbilityDescription
		'ICON_LEADER_IPG_CALVEIT', -- LeaderAbilityIcon
		'LEADER_IPG_CALVEIT_SELECT_NEUTRAL',
		'LEADER_IPG_CALVEIT_BACKGROUND'
		);
-----------------------------------------------
-- PlayerItems (Base Game / Vanilla)
-----------------------------------------------
--INSERT INTO PlayerItems
--		(CivilizationType, 			LeaderType, 			Type, 						Icon, 							Name, 								Description, 								SortIndex	)
--VALUES	('CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'UNIT_EMHYR_NAUZICAA_BRIGADE',		'ICON_UNIT_EMHYR_NAUZICAA_BRIGADE',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',		10			),
--		('CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'ICON_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',	20			);
-----------------------------------------------
-- PlayerItems (Rise & Fall)
-----------------------------------------------
/*
INSERT INTO PlayerItems
		(Domain, 						CivilizationType, 				LeaderType, 		Type, 									Icon, 										Name, 											Description, 											SortIndex	)
VALUES	('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'UNIT_EMHYR_NAUZICAA_BRIGADE',		'ICON_UNIT_EMHYR_NAUZICAA_BRIGADE',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',		20			),
		('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'UNIT_NILFGAARD_FIRE_SCORPION',			'ICON_UNIT_NILFGAARD_FIRE_SCORPION',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',			10			),
		('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'ICON_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',	30			),
		
		('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'UNIT_EMHYR_NAUZICAA_BRIGADE',		'ICON_UNIT_EMHYR_NAUZICAA_BRIGADE',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',		'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',		20			),
		('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'UNIT_NILFGAARD_FIRE_SCORPION',			'ICON_UNIT_NILFGAARD_FIRE_SCORPION',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',			10			),
		('Players:Expansion1_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'ICON_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',	30			);
*/
-----------------------------------------------
-- PlayerItems (Gathering Storm)
-----------------------------------------------
INSERT INTO PlayerItems
		(Domain, 						CivilizationType, 				LeaderType, 		Type, 									Icon, 										Name, 											Description, 											SortIndex	)
VALUES	('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'UNIT_EMHYR_NAUZICAA_BRIGADE',			'ICON_UNIT_EMHYR_NAUZICAA_BRIGADE',			'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_NAME',			'LOC_UNIT_EMHYR_NAUZICAA_BRIGADE_DESCRIPTION',			20			),
		('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'UNIT_NILFGAARD_FIRE_SCORPION',			'ICON_UNIT_NILFGAARD_FIRE_SCORPION',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',			10			),
		('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_EMHYR',	'DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'ICON_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',	30			),
		
		('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'UNIT_CALVEIT_MAGNE_DIVISION',			'ICON_UNIT_CALVEIT_MAGNE_DIVISION',			'LOC_UNIT_CALVEIT_MAGNE_DIVISION_NAME',			'LOC_UNIT_CALVEIT_MAGNE_DIVISION_DESCRIPTION',			20			),
		('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'UNIT_NILFGAARD_FIRE_SCORPION',			'ICON_UNIT_NILFGAARD_FIRE_SCORPION',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_NAME',		'LOC_UNIT_NILFGAARD_FIRE_SCORPION_DESCRIPTION',			10			),
		('Players:Expansion2_Players',	'CIVILIZATION_IPG_NILFGAARD',	'LEADER_IPG_CALVEIT',	'DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'ICON_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_NAME',	'LOC_DISTRICT_NILFGAARDIAN_IMPERIAL_CAMP_DESCRIPTION',	30			);
-----------------------------------------------
-- City-State
-----------------------------------------------
/*
INSERT INTO CityStates (CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES	('CIVILIZATION_IPG_METINNA_MINOR',	'MILITARISTIC',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_METINNA_MINOR',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION'),
		('CIVILIZATION_IPG_MAECHT_MINOR',		'RELIGIOUS',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',		'ICON_CIVILIZATION_IPG_MAECHT_MINOR',		'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION'),
		('CIVILIZATION_IPG_TOUSSAINT_MINOR',	'CULTURAL',		'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME',	'ICON_CIVILIZATION_IPG_TOUSSAINT_MINOR',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION'),
		('CIVILIZATION_IPG_GEMMERA_MINOR',	'MILITARISTIC',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_GEMMERA_MINOR',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION'),
		('CIVILIZATION_IPG_VICOVARO_MINOR',	'SCIENTIFIC',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',	'ICON_CIVILIZATION_IPG_VICOVARO_MINOR',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION');

INSERT INTO CityStates (Domain, CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES	('Expansion1CityStates',	'CIVILIZATION_IPG_METINNA_MINOR',		'MILITARISTIC',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_METINNA_MINOR',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion1CityStates',	'CIVILIZATION_IPG_MAECHT_MINOR',		'RELIGIOUS',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',		'ICON_CIVILIZATION_IPG_MAECHT_MINOR',		'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION'),
		('Expansion1CityStates',	'CIVILIZATION_IPG_TOUSSAINT_MINOR',	'CULTURAL',		'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME',	'ICON_CIVILIZATION_IPG_TOUSSAINT_MINOR',	'LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION'),
		('Expansion1CityStates',	'CIVILIZATION_IPG_GEMMERA_MINOR',		'MILITARISTIC',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_GEMMERA_MINOR',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion1CityStates',	'CIVILIZATION_IPG_VICOVARO_MINOR',	'SCIENTIFIC',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',	'ICON_CIVILIZATION_IPG_VICOVARO_MINOR',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION');
*/
INSERT INTO CityStates (Domain, CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES	('Expansion2CityStates',	'CIVILIZATION_IPG_METINNA_MINOR',	'MILITARISTIC',	'LOC_CIVILIZATION_IPG_METINNA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_METINNA_MINOR',	'LOC_MINOR_CIV_IPG_METINNA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_MAECHT_MINOR',	'RELIGIOUS',	'LOC_CIVILIZATION_IPG_MAECHT_MINOR_NAME',	'ICON_CIVILIZATION_IPG_MAECHT_MINOR',	'LOC_MINOR_CIV_IPG_MAECHT_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_TOUSSAINT_MINOR',	'CULTURAL',		'LOC_CIVILIZATION_IPG_TOUSSAINT_MINOR_NAME','ICON_CIVILIZATION_IPG_TOUSSAINT_MINOR','LOC_MINOR_CIV_IPG_TOUSSAINT_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_GEMMERA_MINOR',	'MILITARISTIC',	'LOC_CIVILIZATION_IPG_GEMMERA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_GEMMERA_MINOR',	'LOC_MINOR_CIV_IPG_GEMMERA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_VICOVARO_MINOR',	'SCIENTIFIC',	'LOC_CIVILIZATION_IPG_VICOVARO_MINOR_NAME',	'ICON_CIVILIZATION_IPG_VICOVARO_MINOR',	'LOC_MINOR_CIV_IPG_VICOVARO_MINOR_TRAIT_DESCRIPTION');
