/*
	Leader Badge Colours
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

-----------------------------------------------
-- PlayerColors
-----------------------------------------------
INSERT INTO	PlayerColors (Type, Usage, PrimaryColor, SecondaryColor, Alt1PrimaryColor, Alt1SecondaryColor, Alt2PrimaryColor, Alt2SecondaryColor, Alt3PrimaryColor, Alt3SecondaryColor )
VALUES	(
		'LEADER_IPG_EMHYR',
		'Unique',
		'COLOR_STANDARD_WHITE_DK',
		'COLOR_STANDARD_ORANGE_LT',

		'COLOR_STANDARD_WHITE_MD',
		'COLOR_STANDARD_WHITE_LT',

		'COLOR_STANDARD_WHITE_LT',
		'COLOR_STANDARD_WHITE_DK',

		'COLOR_STANDARD_ORANGE_LT',
		'COLOR_STANDARD_WHITE_DK'
		),
		(
		'LEADER_IPG_CALVEIT',
		'Unique',
		'COLOR_STANDARD_ORANGE_MD',
		'COLOR_STANDARD_WHITE_DK',

		'COLOR_STANDARD_WHITE_DK',
		'COLOR_STANDARD_ORANGE_LT',

		'COLOR_STANDARD_WHITE_LT',
		'COLOR_STANDARD_WHITE_DK',

		'COLOR_STANDARD_ORANGE_LT',
		'COLOR_STANDARD_WHITE_DK'
		);

INSERT INTO PlayerColors (Type,	Usage,	PrimaryColor,	SecondaryColor	)
VALUES	(
		'CIVILIZATION_IPG_METINNA_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_MAECHT_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_TOUSSAINT_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_CULTURAL_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_GEMMERA_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'
		),
		
		(
		'CIVILIZATION_IPG_VICOVARO_MINOR',
		'Minor',
		'COLOR_PLAYER_CITY_STATE_PRIMARY',
		'COLOR_PLAYER_CITY_STATE_SCIENCE_SECONDARY'
		);