-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_IGNORE_SHORES'),
		('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_WATER_ROUTE'),
		('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_ROUTE_YIELD'),
		('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_ABILITY1'),
		('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_ABILITY2'),
		('BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_ROUTE_CAPACITY');

INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType, ModifierId)
VALUES	('ABILITY_QUANZHOU_PORT',						'TRADE_ROUTE_PLUNDER_IMMUNITY_SEA');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, Permanent, SubjectRequirementSetId)
VALUES	('MODIFIER_QUANZHOU_IGNORE_SHORES',				'MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_SHORES',				0, 'MEDIC_HEALING_REQUIREMENTS'),
		('MODIFIER_QUANZHOU_WATER_ROUTE',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_WATER_RANGE',			0, NULL),
		('MODIFIER_QUANZHOU_ROUTE_YIELD',				'MODIFIER_QUANZHOU_ADJUST_TRADE_ROUTE_YIELD_PER_PATH_TILE',	0, NULL),
		('MODIFIER_QUANZHOU_ABILITY1',					'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS',		1, NULL),
		('MODIFIER_QUANZHOU_ABILITY2',					'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',						1, 'MEDIC_HEALING_REQUIREMENTS'),
		('MODIFIER_QUANZHOU_ROUTE_CAPACITY',			'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',		0, 'REQSET_QUANZHOU_HAS_MARKET_AND_LIGHTHOUSE');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODIFIER_QUANZHOU_IGNORE_SHORES',				'Ignore',		1),
		('MODIFIER_QUANZHOU_WATER_ROUTE',				'Amount',		30),
		('MODIFIER_QUANZHOU_ROUTE_YIELD',				'YieldType',	'YIELD_GOLD'),
		('MODIFIER_QUANZHOU_ROUTE_YIELD',				'Amount',		0.1),
		('MODIFIER_QUANZHOU_ABILITY1',					'AbilityType',	'ABILITY_QUANZHOU_PORT'),
		('MODIFIER_QUANZHOU_ABILITY2',					'AbilityType',	'ABILITY_QUANZHOU_PORT'),
		('MODIFIER_QUANZHOU_ROUTE_CAPACITY',			'Amount',		1);

INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
SELECT	'BUILDING_QUANZHOU_PORT',						'MODIFIER_QUANZHOU_ROUTE_YIELD_'||BuildingType	FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_QUANZHOU_ROUTE_YIELD_'||BuildingType,	'MODIFIER_QUANZHOU_ADJUST_TRADE_ROUTE_YIELD_PER_PATH_TILE',	'REQSET_QUANZHOU_HAS_'||BuildingType FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT			'MODIFIER_QUANZHOU_ROUTE_YIELD_'||BuildingType,	'YieldType',	'YIELD_GOLD'	FROM Buildings WHERE EnabledByReligion = 1
UNION SELECT	'MODIFIER_QUANZHOU_ROUTE_YIELD_'||BuildingType,	'Amount',		0.1				FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('REQSET_QUANZHOU_HAS_MARKET_AND_LIGHTHOUSE',	'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_QUANZHOU_HAS_MARKET_AND_LIGHTHOUSE',	'REQ_QUANZHOU_HAS_MARKET'),
		('REQSET_QUANZHOU_HAS_MARKET_AND_LIGHTHOUSE',	'REQ_QUANZHOU_HAS_LIGHTHOUSE');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQ_QUANZHOU_HAS_MARKET',						'REQUIREMENT_CITY_HAS_BUILDING'),
		('REQ_QUANZHOU_HAS_LIGHTHOUSE',					'REQUIREMENT_CITY_HAS_BUILDING');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_QUANZHOU_HAS_MARKET',						'BuildingType',	'BUILDING_MARKET'), 
		('REQ_QUANZHOU_HAS_LIGHTHOUSE',					'BuildingType',	'BUILDING_LIGHTHOUSE');

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT	'REQSET_QUANZHOU_HAS_'||BuildingType,			'REQUIREMENTSET_TEST_ALL'			FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'REQSET_QUANZHOU_HAS_'||BuildingType,			'REQ_QUANZHOU_HAS_'||BuildingType	FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
SELECT	'REQ_QUANZHOU_HAS_'||BuildingType,				'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
SELECT	'REQ_QUANZHOU_HAS_'||BuildingType,				'BuildingType',		BuildingType	FROM Buildings WHERE EnabledByReligion = 1;

INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_QUANZHOU_ADJUST_TRADE_ROUTE_YIELD_PER_PATH_TILE',	'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_QUANZHOU_ADJUST_TRADE_ROUTE_YIELD_PER_PATH_TILE',	'COLLECTION_OWNER', 'EFFECT_ADJUST_PLAYER_TRADE_ROUTE_YIELD_PER_PATH_TILE');