-- UC_DIP_Text_CS_Ethiopia
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
UPDATE LocalizedText SET Text = REPLACE(Text, 'Consulate', 'Tier 1 Diplomatic Quarter')
WHERE Tag IN	(
				'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS'
				);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Chancery', 'Tier 2 Diplomatic Quarter')
WHERE Tag IN	(
				'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',
				'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS'
				);
--------------------------------------------------------------