INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		32,			1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_32.dds'),
		('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		38,			1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_38.dds'),
		('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		50,			1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_50.dds'),
		('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		80,			1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_80.dds'),
		('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		128,		1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_128.dds'),
		('ICON_ATLAS_PHANTA_HIMEJI_CASTLE',		256,		1,				1,				'ICON_BUILDING_PHANTA_HIMEJI_CASTLE_256.dds'),

		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		32,			1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_32.dds'),
		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		38,			1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_38.dds'),
		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		50,			1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_50.dds'),
		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		80,			1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_80.dds'),
		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		128,		1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_128.dds'),
		('ICON_ATLAS_PHANTA_SHIKKUI_WALLS',		256,		1,				1,				'ICON_BUILDING_PHANTA_SHIKKUI_WALLS_256.dds');

--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,										Atlas,								'Index')
VALUES	('ICON_BUILDING_PHANTA_HIMEJI_CASTLE',		'ICON_ATLAS_PHANTA_HIMEJI_CASTLE',	0),
		('ICON_BUILDING_PHANTA_HIMEJI_CASTLE_FOW',	'ICON_ATLAS_PHANTA_HIMEJI_CASTLE',	0),

		('ICON_BUILDING_PHANTA_SHIKKUI_WALLS',		'ICON_ATLAS_PHANTA_SHIKKUI_WALLS',	0),
		('ICON_BUILDING_PHANTA_SHIKKUI_WALLS_FOW',	'ICON_ATLAS_PHANTA_SHIKKUI_WALLS',	0);

--------------------------------------------------------------