-- Gov_Tier5_UnlockItems
-- Author: JNR
--------------------------------------------------------------

-- CivicSpecialUnlockables
--------------------------------------------------------------
INSERT OR IGNORE INTO CivicSpecialUnlockables
		(Unlockable,					PrereqCivic,					Description,							Background,	Icon,									Civilopedia)
VALUES	('GOVT_UPGRADE_ANCIENT',		'CIVIC_6T_CONSECRATION',		'LOC_BTT_6T_GOVT_UPGRADE_WILDCARD',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_WILDCARD',		'GOVT_4'),
		('GOVT_UPGRADE_POSTCLASSICAL',	'CIVIC_6T_CITIZENSHIP',			'LOC_BTT_6T_GOVT_UPGRADE_WILDCARD',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_WILDCARD',		'GOVT_4'),
		('GOVT_UPGRADE_RENAISSANCE',	'CIVIC_HUMANISM',				'LOC_BTT_6T_GOVT_UPGRADE_WILDCARD',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_WILDCARD',		'GOVT_4'),
		('GOVT_UPGRADE_MODERN',			'CIVIC_MASS_MEDIA',				'LOC_BTT_6T_GOVT_UPGRADE_WILDCARD',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_WILDCARD',		'GOVT_4'),
		('GOVT_UPGRADE_MILITARY',		'CIVIC_RAPID_DEPLOYMENT',		'LOC_BTT_6T_GOVT_UPGRADE_MILITARY',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_MILITARY',		'GOVT_4'),
		('GOVT_UPGRADE_ECONOMIC',		'CIVIC_GLOBALIZATION',			'LOC_BTT_6T_GOVT_UPGRADE_ECONOMIC',		'GOVT',		'BTT_UNLOCK_POLICY_SLOT_ECONOMIC',		'GOVT_4'),
		('GOVT_UPGRADE_DIPLOMATIC',		'CIVIC_SPACE_RACE',				'LOC_BTT_6T_GOVT_UPGRADE_DIPLOMATIC',	'GOVT',		'BTT_UNLOCK_POLICY_SLOT_DIPLOMATIC',	'GOVT_4');
--------------------------------------------------------------