-- 6T_AGP_Text_Prophet
-- Author: JNR, Phantagonist
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,		Tag,																								Text)
VALUES	('en_US',		'LOC_GREAT_PERSON_INDIVIDUAL_JNR_MOSES_NAME',														'Moses'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MOSES_CHAPTER_HISTORY_PARA_1',				'Moses is considered the most important prophet in Judaism and one of the most important prophets in Christianity, Islam, the Druze faith, the Bahá''í Faith, and other Abrahamic religions. According to both the Bible and the Quran, Moses was the leader of the Israelites and lawgiver to whom the authorship, or "acquisition from heaven", of the Torah (the first five books of the Bible) is attributed.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MOSES_CHAPTER_HISTORY_PARA_2',				'According to the Book of Exodus, Moses was born in a time when his people, the Israelites, an enslaved minority, were increasing in population and, as a result, the Egyptian Pharaoh worried that they might ally themselves with Egypt''s enemies. Moses'' Hebrew mother, Jochebed, secretly hid him when Pharaoh ordered all newborn Hebrew boys to be killed in order to reduce the population of the Israelites. Through Pharaoh''s daughter (identified as Queen Bithia in the Midrash), the child was adopted as a foundling from the Nile and grew up with the Egyptian royal family. After killing an Egyptian slave-master who was beating a Hebrew, Moses fled across the Red Sea to Midian, where he encountered the Angel of the Lord, speaking to him from within a burning bush on Mount Horeb, which he regarded as the Mountain of God.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MOSES_CHAPTER_HISTORY_PARA_3',				'God sent Moses back to Egypt to demand the release of the Israelites from slavery. Moses said that he could not speak eloquently, so God allowed Aaron, his elder brother, to become his spokesperson. After the Ten Plagues, Moses led the Exodus of the Israelites out of Egypt and across the Red Sea, after which they based themselves at Mount Sinai, where Moses received the Ten Commandments. After 40 years of wandering in the desert, Moses died on Mount Nebo at the age of 120, within sight of the Promised Land.'),

		('en_US',		'LOC_GREAT_PERSON_INDIVIDUAL_JNR_GARGI_VACHAKNAVI_NAME',											'Gargi Vachaknavi'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_GARGI_VACHAKNAVI_CHAPTER_HISTORY_PARA_1',	'Gargi Vachaknavi was an ancient Indian sage and philosopher. In Vedic literature, she is honored as a great natural philosopher, renowned expounder of the Vedas, and known as Brahmavadini, a person with knowledge of Brahma Vidya. Gargi was the daughter of sage Vachaknu in the lineage of sage Garga (c. 800-500 BCE) and hence named after her father as Gargi Vachaknavi. Right from a young age, Vachaknavi was very intellectual. She acquired knowledge of the Vedas and scriptures and became renowned for her proficiency in these fields of philosophy. She was as knowledgeable in Vedas and Upanishads as men of the Vedic times and could very well contest the male-philosophers in debates. She was a leading scholar who also made rich contributions to propagate education.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_GARGI_VACHAKNAVI_CHAPTER_HISTORY_PARA_2',	'Gargi was as knowledgeable in Vedas and Upanishads as men of the Vedic times and could very well contest the male-philosophers in debates. In the Sixth and the eighth Brahmana of Brihadaranyaka Upanishad, her name is prominent as she participates in the brahmayajna, a philosophic debate organized by King Janaka of Videha and she challenges the sage Yajnavalkya with perplexing questions on the issue of atman (soul). She is also said to have written many hymns in the Rigveda. She remained a celibate all her life and was held in veneration by the conventional Hindus.');
--------------------------------------------------------------

