-- 6T_AGP_Text_Scientist
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,		Tag,																							Text)
VALUES	('en_US',		'LOC_GREAT_PERSON_INDIVIDUAL_JNR_THALES_MILETUS_NAME',											'Thales of Miletus'),
		('en_US',		'LOC_GREATPERSON_JNR_THALES_1ANCIENTECHBOOST',													'Triggers the [ICON_TechBoosted] Eureka moment for 1 random technology from the Ancient era and the [ICON_CivicBoosted] Inspiration moment for 2 random civics from the Classical era.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_THALES_MILETUS_CHAPTER_HISTORY_PARA_1',	'Thales of Miletus (c. 626/623 - c. 548/545 BC) was an Ancient Greek pre-Socratic philosopher from Miletus in Ionia, Asia Minor. Thales was one of the Seven Sages, founding figures of Ancient Greece, and credited with the saying "know thyself" which was inscribed on the Temple of Apollo at Delphi. Many regard him as the first philosopher in the Greek tradition, breaking from the prior use of mythology to explain the world and instead using natural philosophy. He is thus otherwise credited as the first to have engaged in mathematics, science, and deductive reasoning.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_THALES_MILETUS_CHAPTER_HISTORY_PARA_2',	'The first philosophers followed him in explaining all of nature as based on the existence of a single ultimate substance. Thales theorized that this single substance was water. He thought the Earth floated in water. Thales was said to have calculated the heights of the pyramids and the distance of ships from the shore. In science, he was an astronomer who reportedly predicted the weather and a solar eclipse. He was also credited with discovering the position of the constellation Ursa Major as well as the timings of the solstices and equinoxes. Thales was also an engineer; credited with diverting the Halys River.'),

		('en_US',		'LOC_GREAT_PERSON_INDIVIDUAL_JNR_MAITREYI_NAME',												'Maitreyi'),
		('en_US',		'LOC_GREATPERSON_JNR_MAITREYI_LIBRARY_SCIENCE',													'Grants +1 [ICON_Science] Science, [ICON_Culture] Culture, and [ICON_Faith] Faith to Campus district buildings in this city.'),
		('en_US',		'LOC_GREATPERSON_JNR_MAITREYI_CITIZEN_SCIENCE',													'Grants +0.2 [ICON_Science] Science, [ICON_Culture] Culture, and [ICON_Faith] Faith per Citizen in this city.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MAITREYI_CHAPTER_HISTORY_PARA_1',		'Maitreyi ("Wise one") was an Indian philosopher who lived during the later Vedic period in ancient India. She is mentioned in the Brihadaranyaka Upanishad as one of two wives of the Vedic sage Yajnavalkya; she is estimated to have lived around the 8th century BCE. In the Hindu epic Mahabharata and the Gṛhyasūtras, however, Maitreyi is described as an Advaita philosopher who never married. In ancient Sanskrit literature, she is known as a brahmavadini (an expounder of the Veda). She is iregarded as one of the most learned and virtuous women of ancient India and symbolizes intellectual women in India.'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MAITREYI_CHAPTER_HISTORY_PARA_2',		'In the Rigveda about ten hymns are attributed to Maitreyi. She explores the Hindu concept of Atman (soul or self) in a dialogue contained in the Brihadaranyaka Upanishad. The dialogue, also called the Maitreyi-Yajnavalkya dialogue, states that love is driven by a person''s soul, and it discusses the nature of Atman and Brahman and their unity, the core of Advaita philosophy. Maitreyi refuses wealth, wishing to share her husband''s spiritual knowledge, and in the four known versions of the Upanishadic story she challenges Yajnavalkya''s theory of Atman. Yajnavalkya acknowledges her motivations, and that her questions are evidence she is a seeker of ultimate knowledge and a lover of the Atman. The Maitreyi-Yajnavalkya dialogue includes a discussion of love and the essence of whom one loves, suggesting that love is a connection of the soul and the universal self (related to an individual).');
--------------------------------------------------------------

