/*
	Civilization Text Entries zh_Hans_CN
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

INSERT OR REPLACE INTO LocalizedText
			(Language, Tag, Text)
VALUES
-----------------------------------------------
-- City State
-----------------------------------------------
	-- DAERLAN
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_NAME',			'达尔兰'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_DAERLAN_MINOR',					'达尔兰'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_DESCRIPTION',	'达尔兰城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_ADJECTIVE',		'达尔兰的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_DAERLAN_MINOR_TRAIT_NAME',		'达尔兰宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_DAERLAN_MINOR_TRAIT_DESCRIPTION',	'轻骑兵和重骑兵单位每次击杀获得3 [ICON_GreatGeneral] 大将军点数。'),

	('zh_Hans_CN',	'LOC_ABILITY_DAERLAN_CAVALRY_GREAT_GENERAL_DESCRIPTION',	'每次击杀获得 [ICON_GreatGeneral] 大将军点数（达尔兰）。'	),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_1',
	'达尔兰是尼弗迦德帝国的一个地区或行政单位，以其军事而闻名。 它在托雷斯.瓦.恩瑞斯统治之前就被征服了。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_2',
	'纵观其作为帝国土地的历史，达尔兰至少组建了七个骑兵旅。 北方战争期间，达尔兰军队是尼弗迦德军队的中坚力量：达尔兰第七骑兵旅无疑是最值得关注的。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_3',
	'然而，很少有人听说过达尔兰步兵，这个不受欢迎的同伴步兵单位被轻蔑地称为“第七的私生子”。 在只尊重马蹄铁的环境中依赖靴子皮革，这些人仍然尽其所能，一次一个步骤。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_4',
	'除了传统的尼弗迦德黑色外，达尔兰军队还穿着绿色和棕色。达尔兰的士兵认为在敌人的水井里下毒是不光彩的。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_5',
	'小记'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_6',
	'在波兰语版中，名字达尔兰出现在妖名Daerlańczyk和形容词daerlański的一部分，因此该地区的波兰语名称是达尔兰还是达尔尔尚不清楚。有可能这两个名称都是正确的，例如 Daerl 代表首都，Daerlan 代表国家。'),
	
	-- MAGNE
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_NAME',			'马格尼'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_MAGNE_MINOR',					'马格尼'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_DESCRIPTION',	'马格尼城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_ADJECTIVE',		'马格尼人'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAGNE_MINOR_TRAIT_NAME',		'马格尼宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAGNE_MINOR_TRAIT_DESCRIPTION',	'所有侦察单位+1视野，且不受区域控制影响。'),

	('zh_Hans_CN',	'LOC_ABILITY_MAGNE_RECON_DESCRIPTION',	'无视区域控制，+1视野(马格尼).'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_1',
	'马格尼是尼弗迦德帝国内的一块假定土地，马格尼师来自那里。詹.卡尔维特在成为皇帝之前曾在这里任职。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_2',
	'马格尼在托雷斯.瓦.恩瑞斯统治之前成立。 作为帝国的一部分，马格尼师的士兵经常被派往科拉斯沙漠巡逻。 在一次这样的巡逻中，整个部队遭到一群游牧民的伏击，唯一逃脱的士兵是后来成为皇帝的年轻的扬卡尔维特。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_3',
	'马格尼位于帝国的东部边界，沿着提尔.托夏和科拉兹。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_4',
	'马格尼人似乎主要是金发。 众所周知，男人留着短胡子，而那些在军队服役的人则穿着混合橙色和黑白切凯色的制服。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_5',
	'小记'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_6',
	'马格尼作为一块土地的存在在小说中并不清楚。 并不是每个省（基本上没有一个普法尔茨省）都被提到名字，而雅鲁加和阿尔巴之间以英里为单位的距离留下了巨大的空间真空。CDPR的巫师系列地图实际上是第一个在一张地图上描绘尼弗迦德和北方王国的地图——但只是通过拉伸在当代维基上有文章的省份（因此缺少像罗万或温尼堡这样的文章），这已经扰乱了 描述了亚梅尔省的距离。马格尼是这些失踪的帝国地区的可能名称之一，因为其他几支尼弗迦德部队以地名或神话人物命名。 由于昆特牌：巫师纸牌游戏的信息，上面的文章是假设马格尼 确实作为一个省存在。 然而，也有可能在小说中马格纳只是该省的一个未被提及的小地方。'),
	
	-- ETOLIA
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_NAME',			'爱托里亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_ETOLIA_MINOR',					'爱托里亚'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_DESCRIPTION',	'爱托里亚城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_ADJECTIVE',		'爱托里亚的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_ETOLIA_MINOR_TRAIT_NAME',		'爱托里亚宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_ETOLIA_MINOR_TRAIT_DESCRIPTION',	'[ICON_CivicBoosted] 鼓舞额外提供市政研究花费的10%文化 [ICON_Culture]'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_1',
	'爱托里亚是尼弗迦德帝国的一个海滨省份。 虽然它被认为是更肥沃的地区之一，但入侵和随后的尼弗迦德化对爱托里亚人造成了毁灭性的影响。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_2',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_3',
	'爱托里亚文明源远流长——甚至有人说，它在历史的早期就影响了下阿尔巴部落，在未来的尼弗迦德文化中播下了埃托利亚思想的种子。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_4',
	'到 12 世纪，埃托利亚是一个生活水平很高的富裕王国。 不幸的是，它的公民与尼弗迦德接壤，尼弗迦德最近被托雷斯皇帝改造成专制帝国。 1216 年，皇帝费格斯.恩瑞斯决定以埃托利亚作为未来等待帝国所有敌人的例子。 尼弗迦德军队进攻并压倒了埃托利亚，摧毁了它的权力结构并摧毁了定义埃托利亚生活的价值观。 埃托利亚人的精神崩溃了。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_5',
	'尼弗迦德建立了一个新的省级政府，被其臣民称为“霸主政府”。 然而，对帝国的恐惧依然强烈，在随后的四十年里，没有发生有组织的民众起义。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_6',
	'第二次北方战争期间，埃托利亚政府派遣了身穿甲壳的老兵盾卫团与来自维科瓦罗的盾卫兵并肩作战。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_7',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_8',
	'爱托里亚离梅契特很远。 作为帝国最肥沃的地方之一，它有时被称为它的粮仓。 春季和夏季，乡村到处都是郁郁葱葱的草地和金色的麦田，清澈的河流冲刷着周围繁荣的居民点。 然而，当冬天来临时，大地变成了荒芜的荒地，狂风时常袭来。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_9',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_10',
	'在征服之前，埃托利亚人专注于贸易、农业、渔业和手工刺绣。 后来，经济主要转向小麦种植。 然而，其中一个例外是养殖 5-7 公斤的淡水白腹鱼。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_11',
	'琐事'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_12',
	'埃托利亚是希腊的一个真实地区，现在是埃托利亚-阿卡纳尼亚双省的一部分。 在古代，这个地方以几个强大的城邦而闻名，这些城邦曾一度联合在埃托利亚同盟中。'),
	
	-- GESO
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GESO_MINOR_NAME',			'吉索'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_GESO_MINOR',					'吉索'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GESO_MINOR_DESCRIPTION',	'吉索城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_GESO_MINOR_ADJECTIVE',		'吉索的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_GESO_MINOR_TRAIT_NAME',		'吉索宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_GESO_MINOR_TRAIT_DESCRIPTION',	'第一次征服一座城市获得 100 [ICON_Faith] 信仰值，研究殖民主义市政后提升到300 [ICON_Faith] 信仰值（标准速度下）。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_1',
	'吉索是位于维尔达上游的尼弗迦德帝国的一个省份。 这条河还形成了格索与梅契特以及可能与麦提那的天然边界。 此外，该省与提尔.托夏地块和东部的科拉兹沙漠接壤。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_2',
	'该省分为行政区，由行政长官代表皇帝管理，他们利用驻扎在这里的许多尼弗迦德军队驻军维持秩序。 当地贵族在尼弗迦德文化的影响下卷入了家族纷争。 事实上，像格莱斯文这样的定居点完全由来自南方的定居者居住，吉索中使用的货币是弗洛伦。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_3',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_4',
	'在帝国征服期间，吉索的统治者向尼弗迦德投降，并允许前来占领的小部队进入他的领土。 然后，他试图向军队发号施令，这导致了严厉的镇压，有效地将盖索变成了另一个省份。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_5',
	'1260 年代，吉索领主的军队与来自艾宾和梅契特的叛乱分子联手，他们共同建立了一个联盟，旨在重新获得主权。 不久之后，领主的军队被帝国的军队击败，导致许多逃亡者和逃兵加入了肆虐这片土地，尤其是边境地区的强盗团伙。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_6',
	'在格索被尼弗迦德完全征服后，许多帝国贵族如斯维尔家族和瓦恩哈根家族移居到新的省份，新的尼弗迦德定居者也重新定居于村庄和城市。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_7',
	'尽管国内局势有些混乱，但在 1267 年第二次北方战争爆发时，格索还是派遣了雇佣兵团对抗北方王国。除了土匪数量不断增加外，上维尔达的土地并没有真正受到冲突的影响。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_8',
	'地理'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_9',
	'吉索是一个多山的国家，溪流纵横交错，到处都是峡谷、洞穴和灌木丛，但也有绿色的山谷和高高的、被太阳灼伤的草地。 肥沃的土地不多，但适合放牧的地方却很多。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_10',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_11',
	'吉索出口由山区溪流驱动的机械织布工制造的羊毛制成的布。 在 土匪小径的定居点，商人经常从维尔达上游地区的强盗和小偷那里购买商品。'),
	
	-- MAG TURGA
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_NAME',			'马格.图加'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_MAG_TURGA_MINOR',					'马格.图加'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_DESCRIPTION',		'马格.图加城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_ADJECTIVE',		'马格.图加的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAG_TURGA_MINOR_TRAIT_NAME',			'马格.图加宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_MAG_TURGA_MINOR_TRAIT_DESCRIPTION',	'森林为工业区提供少量相邻加成 (每相邻2格森林+1 [ICON_Production] 生产力).'),

	('zh_Hans_CN',	'LOC_MAG_TURGA_INDUSTRIAL_ZONE_ADJACENCY',			'+{1_Amount} [ICON_Production] 生产力，来自相邻森林单元格。 (马格.图加)'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_1',
	'马格.图加是尼弗迦德帝国的一个高地地区，与阿梅尔山脉和提尔.托夏接壤。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_2',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_3',
	'在首次登陆之前，马格.图加居住着沃兹格人。 他们曾经穿着皮衣，留着胡须，向莉莉特献上人祭。 当第一批国王征服该地区时，几乎所有人都被杀或逃往东部地区，而遗骸可能与北方人和麦提那人定居者混在一起。 然而，他们的墓地很少能至少存活到 13 世纪。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_4',
	'虽然它在 1240 年代或 1250 年代的某个时候被帝国和平吸收，但马格.图加的人民并没有非常愿意跟随尼弗迦德帝国。 他们与其他几个国家一起参加了泛阿梅尔叛乱，但最终在恩希尔·瓦·恩瑞斯皇帝和希里拉女王结婚后投降，新的特赦显然已获准。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_5',
	'根据最近的谣言，一些矮人开始在马格.图加山的根部进行挖掘。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_6',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_7',
	'马格.图加位于毗邻两个山口的山丘上，阿梅尔和提尔.托夏。 它崎岖不平，森林茂密，有危险的怪物和摇摇欲坠的悬崖。 更受欢迎的是西奥杜拉地区，它受益于温暖的小气候，类似于陶森特，但土壤贫瘠得多。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_8',
	'社会'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_9',
	'马格.图加的居民是宗派性的，对外来者很慢热。 他们通常被描述为拥有比尼弗迦德人更红的头发和更浅的康乃馨色。马格.图加高地人酿造黑啤酒并享用新鲜屠宰的烤肉。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_10',
	'经济'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_11',
	'由于森林数量众多，贝尔哈文的矿石就是在这里冶炼的。 泰尔加诺市尤其以其华丽的剑而闻名。 这片土地也从西奥杜拉山谷的贸易路线中获利。'),
	
	-- EBBING
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_NAME',			'艾宾'),
	('zh_Hans_CN',	'LOC_CITY_NAME_IPG_EBBING_MINOR',					'艾宾'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_DESCRIPTION',	'艾宾城邦'),
	('zh_Hans_CN',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_ADJECTIVE',		'艾宾的'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_EBBING_MINOR_TRAIT_NAME',		'艾宾宗主国加成'),
	('zh_Hans_CN',	'LOC_MINOR_CIV_IPG_EBBING_MINOR_TRAIT_DESCRIPTION',	'任何相邻河流的改良设施+1 [ICON_Gold] 金币。'),

	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_1',
	'艾宾是依附于尼弗迦德帝国的最大国家之一，尽管正式作为一个自治和自治的王国运作。 它位于河流的交汇处，毗邻大海，以其沼泽和沼泽而闻名。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_2',
	'古往今来，大多数诺德林制图师都认为厄宾是大陆的最南端，声称杰梅拉和更南边的土地属于另一个大陆。 尼弗迦德人反过来将其视为“北方”的开始，因此以吞并艾宾开始的一系列与北方人的冲突在帝国史学中被称为“北方战争”。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_3',
	'历史'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_4',
	'维尔达三角洲是现代艾宾的主要地标之一，已知最早的居民是马尔基 人。 他们是坚强的骑手和酿酒师，但在历史的某个时刻他们搬到了麦提纳。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_5',
	'第一次登陆后的一段时间，诺德林人（可能还有史凯利格人）开始在这片土地上定居。 他们中的大多数人选择了沿海和河流并从事渔业，而其他人则在维嫩达尔建立了盐矿。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_6',
	'1230年代，艾宾王国陷入了继承危机。 利用无休止的谈判，篡位者于1239年派遣军队到此。 艾宾的军队，基于社会地位而不是能力，遭受了可怕的损失，尽管主要是出身低微的贵族逃离了战场。 厌倦了政治混乱，他们适应了帝国的统治。 艾宾四胞胎的诞生远在北边的布雷默伍德都在谈论。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_7',
	'在北方人赢得索登山战役后，艾宾与吉索和梅契特一起叛乱，但叛乱被帝国军队的下级指挥官残酷镇压。 埃宾保留了其形式上的独立性，但真正的权力掌握在皇帝手中，多米尼克·邦巴斯图斯·胡维纳格尔被授予维能达和内维根的统治权就证明了这一点。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_8',
	'地理和气候'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_9',
	'它位于多尔.安哥拉之外，西临大海，北临麦提那，叙尔特河作为天然边界，东临梅契特。 该王国还毗邻萨尔姆，正式成为一个主权公国，实际上依赖于艾宾。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_10',
	'它的大部分领土以维尔达、莱特和艾瑞特三大河流为特征，它们在名为 佩雷拉特的广阔湿地土地上纵横交错，被认为是怪物和疾病的孵化场。 然而，从沼泽中开垦出来的土地肥沃肥沃的土地吸引着定居者。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_11',
	'沼泽地外有山链，被认为不太肥沃，但蕴藏着维能达尔盐和卢弗腾的宝石等矿藏。'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_12',
	'社会'),
	('zh_Hans_CN',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_13',
	'大多数人居住在靠近海边的城镇和村庄以及从沼泽地开垦出来的土地上。 腐败很普遍，某些精英成员似乎以相当不道德的方式寻找乐趣。');