/*
	Civilization Text Entries en_US
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/

INSERT OR REPLACE INTO LocalizedText
			(Language, Tag, Text)
VALUES
-----------------------------------------------
-- City State
-----------------------------------------------
	-- DAERLAN
	('en_US',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_NAME',			'Daerlan'),
	('en_US',	'LOC_CITY_NAME_IPG_DAERLAN_MINOR',					'Daerlan'),
	('en_US',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_DESCRIPTION',	'Daerlan city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_ADJECTIVE',		'Daerlanian'),
	('en_US',	'LOC_MINOR_CIV_IPG_DAERLAN_MINOR_TRAIT_NAME',		'Daerlan Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_DAERLAN_MINOR_TRAIT_DESCRIPTION',	'Light and Heavy cavalry units generate 3 [ICON_GreatGeneral] Great General points from kills.'),

	('en_US',	'LOC_ABILITY_DAERLAN_CAVALRY_GREAT_GENERAL_DESCRIPTION',	'Generates [ICON_GreatGeneral] Great General points with each kill (Daerlan).'	),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_1',
	'Daerlan is a region or an administrative unit in the Nilfgaardian Empire notable for its military. It was conquered before the reign of Torres var Emreis.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_2',
	'Throughout its history as an imperial land, Daerlan formed at least seven cavalry brigades. During the Northern Wars, the Daerlanian forces represented the backbone of the Nilfgaardian Army: the 7th Daerlanian Cavalry Brigade was without a doubt the most noteworthy.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_3',
	'Few, however, heard of the Daerlan Foot Soldiers, the unloved companion infantry unit contemptuously referred to as "the Seventh''s bastards." Reliant on boot leather in a milieu that honored only horseshoes, these men nevertheless served as best they could, one step at a time.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_4',
	'Apart from the traditional Nilfgaardian black, Daerlanian troops wore also green and brown. Soldiers from Daerlan perceived the prospect of poisoning the enemy''s wells as dishonourable.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_5',
	'NOTES'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_DAERLAN_MINOR_CHAPTER_HISTORY_PARA_6',
	'In Polish edition, name Daerlan appears as a part of demonym Daerlańczyk and adjective daerlański, therefore it is unclear whether the region''s name in Polish is Daerlan or Daerl. It is possible that both names are correct though, for example Daerl for a capital city and Daerlan for a land.'),
	
	-- MAGNE
	('en_US',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_NAME',			'Magne'),
	('en_US',	'LOC_CITY_NAME_IPG_MAGNE_MINOR',					'Magne'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_DESCRIPTION',	'Magne city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAGNE_MINOR_ADJECTIVE',		'Magnese'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAGNE_MINOR_TRAIT_NAME',		'Magne Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAGNE_MINOR_TRAIT_DESCRIPTION',	'All Recon units receive +1 sight and ignore Zones of control.'),

	('en_US',	'LOC_ABILITY_MAGNE_RECON_DESCRIPTION',	'Ignores Zones of control and receives +1 Sight (Magne).'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_1',
	'Magne is an assumed land within the Nilfgaardian Empire where the Magne Division hails from. Jan Calveit had served here before he became the emperor.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_2',
	'Magne was incorporated before the reign of Torres var Emreis. As a part of the Empire, soldiers of the Magne division were often sent to patrol the Korath desert. During one such patrol the whole unit was ambushed by a group of nomads and the sole soldier to escape was young Jan Calveit who would later become the emperor.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_3',
	'Magne is located on the eastern border of the Empire, along Tir Tochair and Korath.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_4',
	'Magnese seem to be mostly blond-haired. Men are known to grow short beards and those who serve in the army wear uniforms mixing orange with black and white chequy.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_5',
	'NOTES'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAGNE_MINOR_CHAPTER_HISTORY_PARA_6',
	'The existence of Magne as a land is unclear in the novels. Not every Province (and basically none Palatinate) is mentioned by name, while the distance in miles between Yaruga and Alba leaves a vast vacuum of space. The map for CD PROJEKT RED''s The Witcher franchise was actually the first to depict Nilfgaard and Northern Realms on one map – but only by stretching provinces having articles on the contemporary wiki (thus lacking ones like Rowan or Winneburg), which disturbed already described distances of sub-Amell provinces. Magne is one of the possible names of these missing Imperial regions due to several other Nilfgaardian forces bearing names either after places or mythological beings. The article above is written assuming that Magne does exist as a province, due to Gwent: The Witcher Card Game informations. However, it is possible as well that in the novels Magne is only a minor place lying in the province not yet mentioned by name.'),
	
	-- ETOLIA
	('en_US',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_NAME',			'Etolia'),
	('en_US',	'LOC_CITY_NAME_IPG_ETOLIA_MINOR',					'Etolia'),
	('en_US',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_DESCRIPTION',	'Etolia city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_ADJECTIVE',		'Etolian'),
	('en_US',	'LOC_MINOR_CIV_IPG_ETOLIA_MINOR_TRAIT_NAME',		'Etolia Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_ETOLIA_MINOR_TRAIT_DESCRIPTION',	'[ICON_CivicBoosted] Inspirations provide an extra 10% of the [ICON_Culture] Culture cost for researching civics.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_1',
	'Etolia is a seaside province in Nilfgaardian Empire. While it is considered as one of the more fertile regions, the invasion and subsequent Nilfgaardization made a devastating impact upon Etolian people.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_2',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_3',
	'Etolian civilization reaches ancient times – it is even said that it influenced Lower Alban tribes at early point of their history, seeding Etolian ideas in the future Nilfgaardian culture.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_4',
	'By the 12th century Etolia was a wealthy kingdom of high living standards. Unfortunately for its citizens, it bordered Nilfgaard, recently reformed into an absolutist empire by Emperor Torres. In 1216, Emperor Fergus var Emreis decided to use Etolia as an example of the future that awaits all enemies of the Empire. Nilfgaardian Army attacked and overwhelmed Etolia, annihilated its power structures and decimated the values defining Etolian life. The spirit of Etolian people was broken.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_5',
	'Nilfgaard installed a new provincial government referred to by its subjects as "the government of an overlord". The fear of the Empire remained strong however and in the subsequent four decades there was no organized popular uprising.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_6',
	'During the Second Northern War, Etolian government dispatched regiments of veteran shieldbearers armored like crabs who marched alongside shieldbearers from Vicovaro.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_7',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_8',
	'Etolia is located quite far from Maecht. As one of the more fertile places in the Empire, it is at times referred to as its granary. In spring and summer, the countryside is full of lush meadows and golden wheat fields washed by clear rivers around which thriving settlements lie. However, when winter comes the land turns into barren waste with violent gales breaking ever so often.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_9',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_10',
	'Before the conquest, Etolians focused on trade, farming, fishing, and hand embroidery. Later, the economy shifted primarily towards wheat cultivation. One of the exceptions, however, was the farming of 5-7 kilogram freshwater white belly fish.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_11',
	'TRIVIA'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_ETOLIA_MINOR_CHAPTER_HISTORY_PARA_12',
	'Aetolia is a real region in Greece and nowadays part of the dual province of Aetolia-Acarnania. During ancient era, the place was known for several powerful city-states which were at one point united in Aetolian League.'),
	
	-- GESO
	('en_US',	'LOC_CIVILIZATION_IPG_GESO_MINOR_NAME',			'Geso'),
	('en_US',	'LOC_CITY_NAME_IPG_GESO_MINOR',					'Geso'),
	('en_US',	'LOC_CIVILIZATION_IPG_GESO_MINOR_DESCRIPTION',	'Geso city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_GESO_MINOR_ADJECTIVE',		'Geson'),
	('en_US',	'LOC_MINOR_CIV_IPG_GESO_MINOR_TRAIT_NAME',		'Geso Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_GESO_MINOR_TRAIT_DESCRIPTION',	'Gain 100 [ICON_Faith] Faith after conquering a city for the first time, increasing to 300 [ICON_Faith] Faith with the Colonialism civic (on Standard speed).'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_1',
	'Geso or Gheso is a province of the Nilfgaardian Empire located on the upper Velda. The river also forms Geso''s natural border with Maecht and possibly Metinna as well. Furthermore the province borders with Tir Tochair massif and Korath desert to its east.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_2',
	'The province, divided into prefectures, is managed by prefects on behalf of the Imperator who utilize the many Nilfgaardian Army garrisons stationed here to upkeep order. Local nobility is engaged in family feuds and very much under the influence of Nilfgaardian culture. There are in fact settlements like Glyswen completely populated by settlers from the south and the currency used in Geso is floren.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_3',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_4',
	'During the Empire''s conquest, the ruler of Geso surrendered to Nilfgaard and allowed the small force that arrived for the occupation to enter his dominion. He then tried to dictate terms to the army which resulted in severe repressions, effectively turning Geso into yet another province.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_5',
	'In the 1260s, the army of the lord of Geso joined forces with insurgents from Ebbing and Maecht and together they created a confederation with an aim to gain sovereignty again. Lord''s army was defeated by the forces of the Empire not long after which resulted in many of its fugitives and deserters joining the bandit gangs that plagued the land, especially the Borderland region.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_6',
	'After Geso was completely conquered by Nilfgaard, many Imperial noble families such as the Sweers and the Varnhagens moved in the new province, as well as new Nilfgaardian settlers who repopulated the villages and the cities.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_7',
	'Despite a somewhat chaotic internal situation, Geso sent regiments of mercenaries against Northern Kingdoms when the Second Northern War broke out in 1267. Apart from the rising number of bandits, the lands on upper Velda weren''t really afflicted by the conflict.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_8',
	'GEOGRAPHY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_9',
	'Geso is a rather mountainous country, abundantly cut by streams, full of ravines, caves, and thickets, but also boasting green valleys as well as high, sun-burnt grasses. There is not much fertile land, but there are plenty of areas suitable for pasture.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_10',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_GESO_MINOR_CHAPTER_HISTORY_PARA_11',
	'Geso exports cloth made of sheep''s wool manufactured with the help of mechanical weavers driven by mountain streams. In the settlements on the Bandits'' Trail, merchants often buy goods from brigands and thieves from the area above the upper Velda.'),
	
	-- MAG TURGA
	('en_US',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_NAME',			'Mag Turga'),
	('en_US',	'LOC_CITY_NAME_IPG_MAG_TURGA_MINOR',					'Mag Turga'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_DESCRIPTION',		'Mag Turga city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_ADJECTIVE',		'Mag Turgan'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAG_TURGA_MINOR_TRAIT_NAME',			'Mag Turga Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_MAG_TURGA_MINOR_TRAIT_DESCRIPTION',	'Woods provide a minor adjacency bonus for Industrial Zone districts (+1 [ICON_Production] Production for each 2 Woods tiles).'),

	('en_US',	'LOC_MAG_TURGA_INDUSTRIAL_ZONE_ADJACENCY',			'+{1_Amount} [ICON_Production] Production from the adjacent Woods tiles. (Mag Turga)'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_1',
	'Mag Turga is a highland region in the Nilfgaardian Empire which borders on both the Amell Mountains and Tir Tochair.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_2',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_3',
	'Before the First Landing Mag Turga was inhabited by the Wozgor people. They used to wear leather clothes, grow beards and offer human sacrifices to Lilit. Almost all of them were either killed or escaped to Eastern Lands when the first kings counquered the region and the remains probably mixed with Nordling and Metinnese settlers. Few of their necropolies however survived to at least the 13th century.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_4',
	'Although it was absorbed by the Empire peacefully at some point during 1240s or 1250s, the people of Mag Turga did not follow the Pax Nilfgaardiana much willingly. They participated in the pan-Amell rebellion along with several other countries, but eventually surrendered after the marriage between Emperor Emhyr var Emreis and Queen Cirilla when the new amnesty was apparently granted.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_5',
	'According to recent rumors, some dwarves started digging at the roots of Mag Turga hills.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_6',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_7',
	'Mag Turga is located on the hills bordering two mountain passes, Amell and Tir Tochair. It is rugged and thickly forested, with dangerous monsters and crumbling cliffs. More welcoming is the the Sudduth region, which benefits from a warm microclimate, similar to that of Toussaint but with much poorer soil.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_8',
	'SOCIETY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_9',
	'Inhabitants of Mag Turga are clannish and slow to warm to outsiders. They are often described to have red hair and lighter shade of carnation than the Nilfgaardians. Mag Turgan highlanders brew stout and enjoy freshly butchered roasts.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_10',
	'ECONOMY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_MAG_TURGA_MINOR_CHAPTER_HISTORY_PARA_11',
	'Due to a considerable number of forests, it is here where the ore from Belhaven is used to be smelted. The city of Tergano in particular is known for its magnificent swords. The land profits as well from trade routes in the Sudduth valley.'),
	
	-- EBBING
	('en_US',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_NAME',			'Ebbing'),
	('en_US',	'LOC_CITY_NAME_IPG_EBBING_MINOR',					'Ebbing'),
	('en_US',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_DESCRIPTION',	'Ebbing city-state'),
	('en_US',	'LOC_CIVILIZATION_IPG_EBBING_MINOR_ADJECTIVE',		'Ebbinger'),
	('en_US',	'LOC_MINOR_CIV_IPG_EBBING_MINOR_TRAIT_NAME',		'Ebbing Suzerain Bonus'),
	('en_US',	'LOC_MINOR_CIV_IPG_EBBING_MINOR_TRAIT_DESCRIPTION',	'+1 [ICON_Gold] Gold to any Improvement adjacent to a river.'),

	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_1',
	'Ebbing is one of the largest states dependent on the Nilfgaardian Empire, though officially operates as an autonomous and self-governing kingdom. Situated at the junction of rivers and bordering the Great Sea, it is known for its marshes and swamps.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_2',
	'Throughout the ages, most of the Nordling cartographers considered Ebbing as the southernmost part of the Continent, claiming that Gemmera and lands further south belong to another landmass. The Nilfgaardians in turn perceived it to be the beginning of the "north", hence the series of conflicts against the Nordlings which began with the annexation of Ebbing were dubbed the "Northern Wars" in Imperial historiography.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_3',
	'HISTORY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_4',
	'The earliest known inhabitants of the Velda delta, one of the major landmarks of the modern-day Ebbing, were the Markee people. They were tough horsemen and winemakers, but at some point of the history they moved to Metinna.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_5',
	'Some time after the First Landing, Nordlings (and possibly Skelligers) began to settle the land. Most of them chose the sea coast and rivers and occupied with the fishery, while others established salt mines in Venendal.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_6',
	'In the 1230s, the Kingdom of Ebbing was stuck in succession crisis. Taking advantage of the endless negotiations, in 1239 the Usurper sent here the army. Ebbing''s military, based on the social status rather than on competence took horrible loses, though mostly the lowborn - the nobles fled the field. Tired of the political chaos, they adapted to Imperial dominance. The birth of the Ebbing quadruplets was talked as far north as Bremervoord.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_7',
	'After the Battle of Sodden Hill, won by the Nordlings, Ebbing rebelled alongside Geso and Maecht, but the rebellion was brutally suppressed by the junior commanders of the Imperial army. Ebbing retained its formal independence, but the real power was held by the emperor, as proved when Dominik Bombastus Houvenaghel was given lordship over Venendal and Neveugen.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_8',
	'GEOGRAPHY AND CLIMATE'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_9',
	'Located beyond Dol Angra, it borders the Great Sea to the west, Metinna to the north with the river Sylte acting as a natural border and Maecht to the east. The kingdom also neighbors Salm, officially a sovereign principality that is de facto dependent on Ebbing.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_10',
	'Most of its territory is characterized by three rivers Velda, Lete, and Arete which crisscross in the land of vast wetlands named Pereplut considered as a hatchery of monsters and diseases. However, the land reclaimed from the swamps is rich and fertile soil attracting the settlers.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_11',
	'Outside the marshes there are hill chains, considered less fertile but containing mineral deposits such as Venendalian salt and Luverten''s gems.'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_12',
	'SOCIETY'),
	('en_US',	'LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_IPG_EBBING_MINOR_CHAPTER_HISTORY_PARA_13',
	'Most of the people live in towns and villages near the sea and in the lands reclaimed from the swamps. The corruption is common and certain members of the elites seem to find pleasures in rather immoral manners.');