-- Legitimacy_Text
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO EnglishText
		(Tag,											Text)
VALUES	('LOC_GOVERNMENT_CORPORATE_NOSTALGOCRACY_NAME',	'Corporate Nostalgocracy'),
		('LOC_GOVERNMENT_PARASOCIAL_DEMOCRACY_NAME',	'Parasocial Democracy');

UPDATE LocalizedText SET Text = REPLACE(Text, 'Economic', 'Rational-Legal') WHERE Tag IN (
		'LOC_ECONOMIC',
		'LOC_SLOT_ECONOMIC_NAME',
		'LOC_EMPTY_SLOT_ECONOMIC',
		'LOC_GOVT_POLICY_TYPE_ECONOMIC',
		'LOC_GOVT_NO_ECONOMIC_SLOTS',
		'LOC_GOVT_FILTER_ECONOMIC',
		'LOC_GREATPERSON_ECONOMIC_POLICY_SLOT',
		'LOC_BUILDING_BIG_BEN_DESCRIPTION',
		'LOC_BUILDING_BIG_BEN_EXPANSION2_DESCRIPTION',
		'LOC_TRAIT_LEADER_KUBLAI_DESCRIPTION',
		'LOC_GOVERNOR_PROMOTION_OWLS_OF_MINERVA_1_DESCRIPTION',
		'LOC_PEDIA_GOVERNMENTS_PAGEGROUP_ECONOMIC_POLICES_NAME',
		'LOC_PEDIA_LEADERS_PAGE_LEADER_KUBLAI_KHAN_CHINA_CHAPTER_DETAILED_BODY',
		'LOC_PEDIA_LEADERS_PAGE_LEADER_KUBLAI_KHAN_MONGOLIA_CHAPTER_DETAILED_BODY'
);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Diplomatic', 'Charismatic') WHERE Tag IN (
		'LOC_DIPLOMATIC',
		'LOC_SLOT_DIPLOMATIC_NAME',
		'LOC_EMPTY_SLOT_DIPLOMATIC',
		'LOC_GOVT_POLICY_TYPE_DIPLOMATIC',
		'LOC_GOVT_FILTER_DIPLOMATIC',
		'LOC_BUILDING_POTALA_PALACE_DESCRIPTION',
		'LOC_BUILDING_POTALA_PALACE_EXPANSION2_DESCRIPTION',
		'LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION1_DESCRIPTION',
		'LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION',
		'LOC_PEDIA_GOVERNMENTS_PAGEGROUP_DIPLOMATIC_POLICIES_NAME',
		'LOC_PEDIA_LEADERS_PAGE_LEADER_T_ROOSEVELT_CHAPTER_DETAILED_BODY'
);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Diplomacy', 'Charismatic') WHERE Tag IN (
		'LOC_GOVT_NO_DIPLOMACY_SLOTS'
);

UPDATE LocalizedText SET Text = REPLACE(Text, 'Military', 'Traditional') WHERE Tag IN (
		'LOC_MILITARY',
		'LOC_SLOT_MILITARY_NAME',
		'LOC_EMPTY_SLOT_MILITARY',
		'LOC_GOVT_POLICY_TYPE_MILITARY',
		'LOC_GOVT_NO_MILITARY_SLOTS',
		'LOC_GOVT_FILTER_MILITARY',
		'LOC_BUILDING_ALHAMBRA_DESCRIPTION',
		'LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION',
		'LOC_TRAIT_LEADER_HOLY_ROMAN_EMPEROR_DESCRIPTION',
		'LOC_TRAIT_LEADER_THERMOPYLAE_DESCRIPTION',
		'LOC_ABILITY_GORGO_POLICY_SLOT_COMBAT_BONUS_DESCRIPTION',
		'LOC_COMBAT_PREVIEW_NUMBER_MILITARY_POLICIES_BONUS_DESC',
		'LOC_PEDIA_GOVERNMENTS_PAGEGROUP_MILITARY_POLICIES_NAME',
		'LOC_PEDIA_LEADERS_PAGE_LEADER_JADWIGA_CHAPTER_DETAILED_BODY'
);
--------------------------------------------------------------