-- Yang_Yumen
-- Author: Ithildin
-- DateCreated: 7/7/2024 3:58:53 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType, ModifierId)
VALUES	('ABILITY_YANG_TRADE_ROUTE_PLUNDER_IMMUNITY',	'MODFEAT_YANG_TRADE_ROUTE_PLUNDER_IMMUNITY');

INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_YANG_PASS',							'MODFEAT_YANG_TRADE_PLUNDER_IMMUNITY_ABILITY'),
		('BUILDING_YANG_PASS',							'MODFEAT_YANG_TRADE_PRODUCTION'),
		('BUILDING_YANG_PASS',							'MODFEAT_YANG_TRADE_CULTURE2');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	('MODFEAT_YANG_TRADE_ROUTE_PLUNDER_IMMUNITY',	'MODIFIER_PLAYER_UNIT_ADJUST_TRADE_ROUTE_PLUNDER_IMMUNITY',									'REQSET_YANG_ADJACENT_DESERT_MOUNTAIN'),
		('MODFEAT_YANG_TRADE_PLUNDER_IMMUNITY_ABILITY',	'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',														'REQSET_YANG_PLAYER_HAS_YUMEN'),
		('MODFEAT_YANG_TRADE_PRODUCTION',				'MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL',	'REQSET_YANG_PLAYER_HAS_YUMEN'),
		('MODFEAT_YANG_TRADE_CULTURE2',					'MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL',	'REQSET_YANG_PLAYER_HAS_YUMEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_YANG_TRADE_ROUTE_PLUNDER_IMMUNITY',	'DomainType',	'DOMAIN_LAND'),
		('MODFEAT_YANG_TRADE_PLUNDER_IMMUNITY_ABILITY',	'AbilityType',	'ABILITY_YANG_TRADE_ROUTE_PLUNDER_IMMUNITY'),
		('MODFEAT_YANG_TRADE_PRODUCTION',				'Amount',		1), 
		('MODFEAT_YANG_TRADE_PRODUCTION',				'YieldType',	'YIELD_PRODUCTION'),
		('MODFEAT_YANG_TRADE_CULTURE2',					'Amount',		1), 
		('MODFEAT_YANG_TRADE_CULTURE2',					'YieldType',	'YIELD_CULTURE');

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('REQSET_YANG_ADJACENT_DESERT_MOUNTAIN',		'REQUIREMENTSET_TEST_ALL'),
		('REQSET_YANG_PLAYER_HAS_YUMEN',				'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_YANG_ADJACENT_DESERT_MOUNTAIN',		'REQ_YANG_ADJACENT_DESERT_MOUNTAIN'),
		('REQSET_YANG_PLAYER_HAS_YUMEN',				'REQ_YANG_PLAYER_HAS_YUMEN');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQ_YANG_ADJACENT_DESERT_MOUNTAIN',			'REQUIREMENT_PLOT_ADJACENT_TERRAIN_TYPE_MATCHES'),
		('REQ_YANG_PLAYER_HAS_YUMEN',					'REQUIREMENT_PLAYER_HAS_BUILDING');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_YANG_ADJACENT_DESERT_MOUNTAIN',			'TerrainType',	'TERRAIN_DESERT_MOUNTAIN'),
		('REQ_YANG_PLAYER_HAS_YUMEN',					'BuildingType',	'BUILDING_YUMEN_PASS');