-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_YANG_PASS',				'MODFEAT_YANG_TRADE_PRODUCTION'),
		('BUILDING_YANG_PASS',				'MODFEAT_YANG_TRADE_CULTURE'),
		('BUILDING_YANG_PASS',				'MODFEAT_YANG_FREE_SILK');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('MODFEAT_YANG_TRADE_PRODUCTION',	'MODIFIER_YANG_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_STRATEGIC_FOR_INTERNATIONAL'),
		('MODFEAT_YANG_TRADE_CULTURE',		'MODIFIER_YANG_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_STRATEGIC_FOR_INTERNATIONAL'),
		('MODFEAT_YANG_FREE_SILK',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_YANG_TRADE_PRODUCTION',	'Amount',		1), 
		('MODFEAT_YANG_TRADE_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
		('MODFEAT_YANG_TRADE_CULTURE',		'Amount',		1), 
		('MODFEAT_YANG_TRADE_CULTURE',		'YieldType',	'YIELD_CULTURE'),
		('MODFEAT_YANG_FREE_SILK',			'Amount',		1), 
		('MODFEAT_YANG_FREE_SILK',			'ResourceType',	'RESOURCE_SILK');

INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_YANG_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_STRATEGIC_FOR_INTERNATIONAL', 'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_YANG_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_STRATEGIC_FOR_INTERNATIONAL', 'COLLECTION_OWNER', 'EFFECT_ADJUST_CITY_TRADE_ROUTE_YIELD_PER_DESTINATION_STRATEGIC_RESOURCE_FOR_INTERNATIONAL');
