INSERT INTO IconTextureAtlases
		(Name,												IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_SANXINGDUI',			32,			1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_32.dds'),
		('ICON_ATLAS_PHANTA_SANXINGDUI',			38,			1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_38.dds'),
		('ICON_ATLAS_PHANTA_SANXINGDUI',			50,			1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_50.dds'),
		('ICON_ATLAS_PHANTA_SANXINGDUI',			80,			1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_80.dds'),
		('ICON_ATLAS_PHANTA_SANXINGDUI',			128,		1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_128.dds'),
		('ICON_ATLAS_PHANTA_SANXINGDUI',			256,		1,				1,				'ICON_BUILDING_PHANTA_SANXINGDUI_256.dds');
		

--------------------------------------------------------------
-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,									Atlas,									'Index')
VALUES	('ICON_BUILDING_PHANTA_SANXINGDUI',		'ICON_ATLAS_PHANTA_SANXINGDUI',			0),
		('ICON_BUILDING_PHANTA_SANXINGDUI_FOW',	'ICON_ATLAS_PHANTA_SANXINGDUI',			0),
		('ICON_BUILDING_PHANTA_SANXINGDUI_1',	'ICON_ATLAS_PHANTA_SANXINGDUI',			0),
		('ICON_BUILDING_PHANTA_SANXINGDUI_1_FOW',	'ICON_ATLAS_PHANTA_SANXINGDUI',			0),
		('ICON_BUILDING_PHANTA_SANXINGDUI_2',	'ICON_ATLAS_PHANTA_SANXINGDUI',			0),
		('ICON_BUILDING_PHANTA_SANXINGDUI_2_FOW',	'ICON_ATLAS_PHANTA_SANXINGDUI',			0);
--------------------------------------------------------------