-- PP_Environment_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconAliases
--------------------------------------------------------------	
INSERT INTO IconAliases	
		(Name,									OtherName)
VALUES 	('ICON_POLICY_JNR_HYDROGEN_ENGINES',	'ICON_POLICY_MILITARY'),
		('ICON_POLICY_JNR_BIODIVERSITY',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_ENERGIEWENDE',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_FEED_IN_TARIFFS',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_FISHING_QUOTAS',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_GREEN_BUILDING',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_ORGANIC_FARMING',		'ICON_POLICY_ECONOMIC'),
		('ICON_POLICY_JNR_CARBON_CERTIFICATES',	'ICON_POLICY_DIPLOMATIC'),
		('ICON_POLICY_JNR_ECOTOURISM',			'ICON_POLICY_DIPLOMATIC'),
		('ICON_POLICY_JNR_VSR_ZONES',			'ICON_POLICY_DIPLOMATIC'),
		('ICON_POLICY_JNR_CONTROLLED_BURNS',	'ICON_POLICY_WILDCARD'),
		('ICON_POLICY_JNR_SMOG_FILTERS',		'ICON_POLICY_ECONOMIC');
--------------------------------------------------------------