--- COLORS
INSERT OR REPLACE INTO Colors 
			(Type,											Color)
VALUES		('COLOR_SC_DARK_GREECE_BLUE',					'22,88,147,255'),
			('COLOR_SC_LIGHT_GREECE_BLUE',					'168,202,233,255'),
			('COLOR_SC_DARK_LILAC',							'137,71,137,255'),
			('COLOR_SC_GREECE_BLUE',						'79,135,185,255'),
			('COLOR_SC_DARK_BURGUNDY',						'144,0,32,255');


INSERT OR REPLACE INTO PlayerColors
		(Type,	Usage,		PrimaryColor,	SecondaryColor,	Alt1PrimaryColor,	Alt1SecondaryColor,	Alt2PrimaryColor,	Alt2SecondaryColor,	Alt3PrimaryColor,	Alt3SecondaryColor)
VALUES	('LEADER_SC_EURYDICE',
		'Unique',
		'COLOR_SC_DARK_GREECE_BLUE',
		'COLOR_SC_LIGHT_GREECE_BLUE',
		'COLOR_SC_DARK_LILAC',
		'COLOR_STANDARD_PURPLE_DK',
		'COLOR_SC_GREECE_BLUE',
		'COLOR_SC_DARK_BURGUNDY',
		'COLOR_STANDARD_MAGENTA_LT',
		'COLOR_STANDARD_BLUE_DK');