-- UC_UPB_Text_Anthology
-- Author: JNR
--------------------------------------------------------------

-- EnglishText
--------------------------------------------------------------
INSERT OR IGNORE INTO EnglishText
		(Tag, Text)
VALUES	('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_TITLE',
		'District-Themed Recruiting'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_1',
		'Unique [ICON_District] districts provide a +20% [ICON_Production] Production bonus to a particular [ICON_Unit] unit type in the city. Each district boosts the production of one or two unique types. This gives your districts more flavor and provides incentives beyond standard build orders to specialize cities in unique ways.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_2',
		'[ICON_DISTRICT_CITY_CENTER] City Center: Naval Melee units (only in coastal City Center!).'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_3',
		'[ICON_DISTRICT_AERODROME] Aerodrome: Aircraft Carrier units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_4',
		'[ICON_DISTRICT_ENCAMPMENT] Encampment: Melee units and Anti-Cavalry units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_5',
		'[ICON_DISTRICT_INDUSTRIAL_ZONE] Industrial Zone: Siege units.'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_6',
		'[ICON_DISTRICT_WATER_ENTERTAINMENT_COMPLEX] Water Park: Naval Raider units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_7',
		'[ICON_DISTRICT_ENTERTAINMENT] Entertainment Complex: Heavy Cavalry units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_8',
		'[ICON_DISTRICT_COMMERCIAL_HUB] Commercial Hub: Light Cavalry units.'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_9',
		'[ICON_DISTRICT_PRESERVE] Preserve: Recon units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_10',
		'[ICON_DISTRICT_AQUEDUCT] Aqueduct: Builders.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_11',
		'[ICON_DISTRICT_HARBOR] Harbor: Naval Ranged units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_12',
		'[ICON_DISTRICT_CAMPUS] Campus: Support units.'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_13',
		'[ICON_DISTRICT_SPACEPORT] Spaceport: Air units and Giant Death Robots (GDR).'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_14',
		'[ICON_DISTRICT_HOLYSITE] Holy Site: Settlers.'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_15',
		'[ICON_DISTRICT_THEATER] Theater Square: Ranged units.'),

		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_16',
		'[ICON_DISTRICT_GOVERNMENT] Government Plaza: Spies.'),
		
		('LOC_PEDIA_CONCEPTS_PAGE_JNR_UC_DISTRICT_UNIT_PRODUCTION_CHAPTER_JNRUPBBASE_PARA_17',
		'[ICON_DISTRICT_DIPLOMATIC_QUARTER] Diplomatic Quarter: Traders.');
--------------------------------------------------------------