-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_GREAT_FIREWALL',			'MODFEAT_GFW_CITY_ANTI_SPY_BONUS'),
		('BUILDING_GREAT_FIREWALL',			'MODFEAT_GFW_PLAYER_SPY_DEFENSE'),
		('BUILDING_GREAT_FIREWALL',			'MODFEAT_GFW_PLAYER_SPY_OFFENSE'),
		('BUILDING_GREAT_FIREWALL',			'MODFEAT_GFW_TOURISM_REDUCTION');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('MODFEAT_GFW_CITY_ANTI_SPY_BONUS',	'MODIFIER_CITY_ADJUST_SPY_BONUS'),
		('MODFEAT_GFW_PLAYER_SPY_DEFENSE',	'MODIFIER_PLAYER_ADJUST_SPY_BONUS'),
		('MODFEAT_GFW_PLAYER_SPY_OFFENSE',	'MODIFIER_PLAYER_ADJUST_SPY_BONUS'),
		('MODFEAT_GFW_TOURISM_REDUCTION',	'MODIFIER_PLAYER_ADJUST_OVERALL_TOURISM_REDUCTION');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_GFW_CITY_ANTI_SPY_BONUS',	'Amount',	2),
		('MODFEAT_GFW_PLAYER_SPY_DEFENSE',	'Amount',	2),
		('MODFEAT_GFW_PLAYER_SPY_DEFENSE',	'Offense',	0),
		('MODFEAT_GFW_PLAYER_SPY_OFFENSE',	'Amount',	1),
		('MODFEAT_GFW_PLAYER_SPY_OFFENSE',	'Offense',	1),
		('MODFEAT_GFW_TOURISM_REDUCTION',	'Amount',	33);