--- COLORS
INSERT OR REPLACE INTO Colors 
			(Type,											Color)
VALUES		('COLOR_SC_LIGHT_PINK',							'255,199,214,255'),
			('COLOR_SC_LIGHT_GREECE_BLUE',					'168,202,233,255'),
			('COLOR_SC_DARK_RED_VIOLET',					'166,0,104,255'),
			('COLOR_SC_DARK_CYAN',							'0,126,162,255'),
			('COLOR_SC_BRIGHT_YELLOW',						'254,249,0,255');


INSERT OR REPLACE INTO PlayerColors
		(Type,	Usage,		PrimaryColor,	SecondaryColor,	Alt1PrimaryColor,	Alt1SecondaryColor,	Alt2PrimaryColor,	Alt2SecondaryColor,	Alt3PrimaryColor,	Alt3SecondaryColor)
VALUES	('LEADER_SC_TELESILLA',
		'Unique',
		'COLOR_SC_LIGHT_PINK',
		'COLOR_SC_DARK_RED_VIOLET',
		'COLOR_SC_DARK_CYAN',
		'COLOR_SC_LIGHT_PINK',
		'COLOR_SC_BRIGHT_YELLOW',
		'COLOR_STANDARD_GREEN_DK',
		'COLOR_STANDARD_PURPLE_DK',
		'COLOR_SC_LIGHT_GREECE_BLUE');