
-------------
-- Religious Inculturation (Enhancer Belief)
-- Trade Routes from the founder's civilization exert +50% Religious Pressure to the city of Destination.
-- Traders passing through cities exert +10 Religious Pressure.
-------------
INSERT INTO Types
		(Type,									Kind)
VALUES	('BELIEF_LEU_INCULTURATION',			'KIND_BELIEF');

INSERT INTO Beliefs
		(BeliefType,						Name,										Description,								BeliefClassType)
VALUES	('BELIEF_LEU_INCULTURATION',		'LOC_BELIEF_LEU_INCULTURATION_NAME',		'LOC_BELIEF_LEU_INCULTURATION_DESCRIPTION',		'BELIEF_CLASS_ENHANCER');

INSERT INTO BeliefModifiers
		(BeliefType,						ModifierID)
VALUES	('BELIEF_LEU_INCULTURATION',		'LEU_RELIGIOUS_INCULTURATION'),
		('BELIEF_LEU_INCULTURATION',		'LEU_RELIGIOUS_INCULTURATION_TRADE_PASS');

INSERT INTO Modifiers
		(ModifierId,										ModifierType,												SubjectRequirementSetId)
VALUES	('LEU_RELIGIOUS_INCULTURATION',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
		('LEU_RELIGIOUS_INCULTURATION_MODIFIER',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_RELIGIOUS_PRESSURE',	null),
		-- Origin (0), Destination (1), Amount (50)	
		('LEU_RELIGIOUS_INCULTURATION_TRADE_PASS',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
		('LEU_RELIGIOUS_INCULTURATION_TRADE_PASS_PROPERTY',	'MODIFIER_PLAYER_ADJUST_PROPERTY',							null);
		

INSERT INTO ModifierArguments
		(ModifierId,										Name,				Value)
VALUES	('LEU_RELIGIOUS_INCULTURATION',						'ModifierId',		'LEU_RELIGIOUS_INCULTURATION_MODIFIER'),
		('LEU_RELIGIOUS_INCULTURATION_MODIFIER',			'Origin',			0),
		('LEU_RELIGIOUS_INCULTURATION_MODIFIER',			'Destination',		1),
		('LEU_RELIGIOUS_INCULTURATION_MODIFIER',			'Amount',			500),
		--
		('LEU_RELIGIOUS_INCULTURATION_TRADE_PASS',			'ModifierId',		'LEU_RELIGIOUS_INCULTURATION_TRADE_PASS_PROPERTY'),
		('LEU_RELIGIOUS_INCULTURATION_TRADE_PASS_PROPERTY',	'Key',				'LEU_RELIGIOUS_TRADER_PASS_BOOST'),
		('LEU_RELIGIOUS_INCULTURATION_TRADE_PASS_PROPERTY',	'Amount',			1);
