-- 6TUE_Naval_Icons_Portraits
-- Author: JNR
--------------------------------------------------------------

-- IconTextureAtlases
--------------------------------------------------------------
INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	38,			3,				2,				'6TUE_Naval_UnitPortraits38'),
		('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	50,			3,				2,				'6TUE_Naval_UnitPortraits50'),
		('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	70,			3,				2,				'6TUE_Naval_UnitPortraits70'),
		('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	95,			3,				2,				'6TUE_Naval_UnitPortraits95'),
		('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	200,		3,				2,				'6TUE_Naval_UnitPortraits200'),
		('ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	256,		3,				2,				'6TUE_Naval_UnitPortraits256');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,															Atlas,									'Index')
VALUES	('ICON_UNIT_JNR_COG_PORTRAIT',									'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	0),
		('ICON_UNIT_JNR_CORVETTE_PORTRAIT',								'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	1),
		('ICON_UNIT_IRONCLAD_PORTRAIT',									'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	2),
		('ICON_UNIT_JNR_STEALTH_DESTROYER_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	3),
		('ICON_UNIT_JNR_HULK_PORTRAIT',									'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	4),
		('ICON_UNIT_JNR_STEAMSHIP_PORTRAIT',							'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	5),
		('ICON_UNIT_JNR_MONITOR_PORTRAIT',								'ICON_ATLAS_UNIT_PORTRAITS_2',			0),

		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_COG_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	0),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_CORVETTE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	1),
		('ICON_ETHNICITY_AFRICAN_UNIT_IRONCLAD_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	2),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_STEALTH_DESTROYER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	3),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_HULK_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	4),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_STEAMSHIP_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_MONITOR_PORTRAIT',			'ICON_ATLAS_UNIT_PORTRAITS_2',			0),

		('ICON_ETHNICITY_ASIAN_UNIT_JNR_COG_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	0),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_CORVETTE_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	1),
		('ICON_ETHNICITY_ASIAN_UNIT_IRONCLAD_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	2),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_STEALTH_DESTROYER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	3),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_HULK_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	4),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_STEAMSHIP_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	5),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_MONITOR_PORTRAIT',				'ICON_ATLAS_ASIAN_UNIT_PORTRAITS_2',	0),

		('ICON_ETHNICITY_MEDIT_UNIT_JNR_COG_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	0),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_CORVETTE_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	1),
		('ICON_ETHNICITY_MEDIT_UNIT_IRONCLAD_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	2),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_STEALTH_DESTROYER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	3),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_HULK_PORTRAIT',					'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	4),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_STEAMSHIP_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	5),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_MONITOR_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS_2',			0),

		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_COG_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	0),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_CORVETTE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	1),
		('ICON_ETHNICITY_SOUTHAM_UNIT_IRONCLAD_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	2),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_STEALTH_DESTROYER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	3),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_HULK_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	4),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_STEAMSHIP_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_NAVAL_PORTRAITS',	5),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_MONITOR_PORTRAIT',			'ICON_ATLAS_UNIT_PORTRAITS_2',			0);
--------------------------------------------------------------