--------------------
-- Basics
--------------------

INSERT INTO Types
		(Type,									Kind)
VALUES	('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'KIND_BUILDING');

INSERT INTO Buildings
		(BuildingType,
		Name,
		Description,
		PrereqTech,
		Cost,
		AdvisorType,
		MaxWorldInstances,
		IsWonder,
		RequiresPlacement,
		AdjacentDistrict,
		Quote)
VALUES	('BUILDING_PHANTA_WORLD_TRADE_CENTER',
		'LOC_BUILDING_PHANTA_WORLD_TRADE_CENTER_NAME',
		'LOC_BUILDING_PHANTA_WORLD_TRADE_CENTER_DESCRIPTION',
		'TECH_COMPUTERS',
		1240,
		'ADVISOR_GENERIC',
		1,
		1,
		1,
		'DISTRICT_COMMERCIAL_HUB',
		'LOC_BUILDING_PHANTA_WORLD_TRADE_CENTER_QUOTE');


INSERT INTO Building_YieldChanges 
		(BuildingType,							YieldType,			YieldChange)
VALUES	('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'YIELD_GOLD',		15);

INSERT INTO BuildingPrereqs
		(Building,							PrereqBuilding)
VALUES	('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'BUILDING_STOCK_EXCHANGE');

INSERT INTO Building_ValidTerrains
		(BuildingType,							TerrainType)
VALUES	('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'TERRAIN_GRASS'),
		('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'TERRAIN_PLAINS'),
		('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'TERRAIN_DESERT'),
		('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'TERRAIN_TUNDRA'),
		('BUILDING_PHANTA_WORLD_TRADE_CENTER',	'TERRAIN_SNOW');

--------------------
-- Bonuses
--------------------

--==== 1.1 Trade Route yield

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES 
('BUILDING_PHANTA_WORLD_TRADE_CENTER', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD', 'MODTYPE_PHANTA_WORLD_TRADE_CENTER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD', 'Amount', '25, 25, 25, 25, 25, 25'), 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD', 'YieldType', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH');

-- Custom ModifierType

INSERT INTO Types (Type, Kind) VALUES 
('MODTYPE_PHANTA_WORLD_TRADE_CENTER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODTYPE_PHANTA_WORLD_TRADE_CENTER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ADJUST_PLAYER_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER');

--==== 1.2 Trade Route Tourism

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES 
('BUILDING_PHANTA_WORLD_TRADE_CENTER', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_TOURISM_MODIFIER', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM', 'Amount', '25');

--==== 2.0 Reqset

-- RequirementSets

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_PHANTA_WORLD_TRADE_CENTER_ALLY', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_PHANTA_WORLD_TRADE_CENTER_ALLY', 'REQ_PHANTA_WORLD_TRADE_CENTER_PLAYER'), 
('REQSET_PHANTA_WORLD_TRADE_CENTER_ALLY', 'REQUIRES_PLAYER_ALLY');

-- Requirements

INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_PHANTA_WORLD_TRADE_CENTER_PLAYER', 'REQUIREMENT_PLAYER_HAS_BUILDING');

INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_PHANTA_WORLD_TRADE_CENTER_PLAYER', 'BuildingType', 'BUILDING_PHANTA_WORLD_TRADE_CENTER');

--==== 2.1 Ally Attach Trade Route yield

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MAJOR_CIV', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD_ATTACH');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD_ATTACH', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'REQSET_PHANTA_WORLD_TRADE_CENTER_ALLY');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD_ATTACH', 'ModifierId', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_YIELD');


--==== 2.2 Ally Attach Trait Route tourism


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MAJOR_CIV', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM_ATTACH');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM_ATTACH', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'REQSET_PHANTA_WORLD_TRADE_CENTER_ALLY');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM_ATTACH', 'ModifierId', 'MODFEAT_PHANTA_WORLD_TRADE_CENTER_TRADE_ROUTE_TOURISM');
