-- MC_Sappers_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR IGNORE INTO IconDefinitions
		(Name,																		Atlas,													'Index')
VALUES	('ICON_UNIT_JNR_MILITARY_SAPPER',											'ICON_ATLAS_UNITS',										51),
		('ICON_UNIT_JNR_MILITARY_SAPPER_FOW',										'ICON_ATLAS_UNITS_FOW',									51),
		('ICON_UNIT_JNR_MILITARY_SAPPER_PORTRAIT',									'ICON_ATLAS_UNIT_PORTRAITS',							49),
		('ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT',					'ICON_ATLAS_ASIAN_UNIT_PORTRAITS',						49),
		('ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT',					'ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS',				49),
		('ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT',					'ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS',				49),
		('ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT',					'ICON_ATLAS_AFRICAN_UNIT_PORTRAITS',					49),
		('ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INDUSTRIAL',						'ICON_ATLAS_UNIT_PORTRAITS_2',							59),
		('ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN',							'ICON_ATLAS_UNIT_PORTRAITS_2',							60),
		('ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INDUSTRIAL',	'ICON_ATLAS_AFRICAN_UNIT_PORTRAITS_2',					59),
		('ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN',		'ICON_ATLAS_UNIT_PORTRAITS',							60),
		('ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INDUSTRIAL',		'ICON_ATLAS_ASIAN_UNIT_PORTRAITS_2',					59),
		('ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_ASIAN_UNIT_PORTRAITS_2',					60),
		('ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INDUSTRIAL',	'ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS_2',			59),
		('ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN',		'ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS_2',			60),
		('ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INDUSTRIAL',		'ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS_2',			59),
		('ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN',			'ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS_2',			60);
--------------------------------------------------------------

-- IconAliases
--------------------------------------------------------------
INSERT OR IGNORE INTO IconAliases
		(Name,																		OtherName)
VALUES	('ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_ATOMIC',							'ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INFORMATION',					'ICON_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_ATOMIC',		'ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INFORMATION',	'ICON_ETHNICITY_AFRICAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_ATOMIC',		'ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INFORMATION',	'ICON_ETHNICITY_SOUTHAM_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_ATOMIC',			'ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INFORMATION',	'ICON_ETHNICITY_ASIAN_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_ATOMIC',			'ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN'),
		('ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_INFORMATION',	'ICON_ETHNICITY_MEDIT_UNIT_MILITARY_ENGINEER_PORTRAIT_ERA_MODERN');
--------------------------------------------------------------

