/*
	Core Leader Configuration
	Author: iPlayGamesITA
	Original template by: MC
	Thanks to everyone in the Civ VI Modding Helpline Discord Server!
*/
-----------------------------------------------
-- City-State
-----------------------------------------------
INSERT INTO CityStates
		(Domain,					CivilizationType,						CityStateCategory,	Name,											Icon,										Bonus)
VALUES	('Expansion2CityStates',	'CIVILIZATION_IPG_DAERLAN_MINOR',		'MILITARISTIC',		'LOC_CIVILIZATION_IPG_DAERLAN_MINOR_NAME',		'ICON_CIVILIZATION_IPG_DAERLAN_MINOR',		'LOC_MINOR_CIV_IPG_DAERLAN_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_MAGNE_MINOR',			'SCIENTIFIC',		'LOC_CIVILIZATION_IPG_MAGNE_MINOR_NAME',		'ICON_CIVILIZATION_IPG_MAGNE_MINOR',		'LOC_MINOR_CIV_IPG_MAGNE_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_ETOLIA_MINOR',		'CULTURAL',			'LOC_CIVILIZATION_IPG_ETOLIA_MINOR_NAME',		'ICON_CIVILIZATION_IPG_ETOLIA_MINOR',		'LOC_MINOR_CIV_IPG_ETOLIA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_GESO_MINOR',			'RELIGIOUS',		'LOC_CIVILIZATION_IPG_GESO_MINOR_NAME',			'ICON_CIVILIZATION_IPG_GESO_MINOR',			'LOC_MINOR_CIV_IPG_GESO_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_MAG_TURGA_MINOR',		'INDUSTRIAL',		'LOC_CIVILIZATION_IPG_MAG_TURGA_MINOR_NAME',	'ICON_CIVILIZATION_IPG_MAG_TURGA_MINOR',	'LOC_MINOR_CIV_IPG_MAG_TURGA_MINOR_TRAIT_DESCRIPTION'),
		('Expansion2CityStates',	'CIVILIZATION_IPG_EBBING_MINOR',		'TRADE',			'LOC_CIVILIZATION_IPG_EBBING_MINOR_NAME',		'ICON_CIVILIZATION_IPG_EBBING_MINOR',		'LOC_MINOR_CIV_IPG_EBBING_MINOR_TRAIT_DESCRIPTION');
