-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_THE_PENTAGON',					'MODFEAT_PENTAGON_UNITUPGRADEDISCOUNT'),
		('BUILDING_THE_PENTAGON',					'MODFEAT_PENTAGON_RESOURCE_DISCOUNT'),
		('BUILDING_THE_PENTAGON',					'MODFEAT_PENTAGON_FREE_PROMOTIONS');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('MODFEAT_PENTAGON_UNITUPGRADEDISCOUNT',	'MODIFIER_PLAYER_ADJUST_UNIT_UPGRADE_DISCOUNT_PERCENT'),
		('MODFEAT_PENTAGON_RESOURCE_DISCOUNT',		'MODIFIER_PLAYER_ADJUST_UNIT_UPGRADE_RESOURCE_COST_MODIFIER'),
		('MODFEAT_PENTAGON_FREE_PROMOTIONS',		'MODIFIER_PENTAGON_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_PENTAGON_UNITUPGRADEDISCOUNT',	'Amount',	50),
		('MODFEAT_PENTAGON_RESOURCE_DISCOUNT',		'Amount',	50),
		('MODFEAT_PENTAGON_FREE_PROMOTIONS',		'Amount',	-1);

INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_PENTAGON_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', 'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_PENTAGON_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', 'COLLECTION_PLAYER_TRAINED_UNITS', 'EFFECT_ADJUST_UNIT_GRANT_EXPERIENCE');

