-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_YUMEN_PASS',				'MODFEAT_YUMEN_TRADE_GOLD'),
		('BUILDING_YUMEN_PASS',				'MODFEAT_YUMEN_TRADE_CULTURE'),
		('BUILDING_YUMEN_PASS',				'MODFEAT_YUMEN_FREE_JADE');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('MODFEAT_YUMEN_TRADE_GOLD',		'MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL'),
		('MODFEAT_YUMEN_TRADE_CULTURE',		'MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL'),
		('MODFEAT_YUMEN_FREE_JADE',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_YUMEN_TRADE_GOLD',		'Amount',		2), 
		('MODFEAT_YUMEN_TRADE_GOLD',		'YieldType',	'YIELD_GOLD'),
		('MODFEAT_YUMEN_TRADE_CULTURE',		'Amount',		1), 
		('MODFEAT_YUMEN_TRADE_CULTURE',		'YieldType',	'YIELD_CULTURE'),
		('MODFEAT_YUMEN_FREE_JADE',			'Amount',		1), 
		('MODFEAT_YUMEN_FREE_JADE',			'ResourceType',	'RESOURCE_JADE');

INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL', 'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_YUMEN_CITIY_ADJUST_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_FOR_INTERNATIONAL', 'COLLECTION_OWNER', 'EFFECT_ADJUST_CITY_TRADE_ROUTE_YIELD_PER_DESTINATION_LUXURY_RESOURCE_FOR_INTERNATIONAL');
