-- UC_CSB_Text
-- Author: JNR
--------------------------------------------------------------

-- Delete Old Text
--------------------------------------------------------------
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS';
DELETE FROM LocalizedText WHERE Tag='LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS';
--------------------------------------------------------------

-- EnglishText
--------------------------------------------------------------
INSERT OR REPLACE INTO EnglishText
		(Tag,														Text)
VALUES	('LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Science] Science in the [ICON_Capital] Capital and in every Library building.'),
		('LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Science] Science in every University building.'),
		('LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Science] Science in every Research Lab building.'),
		('LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Faith] Faith in the [ICON_Capital] Capital and in every Shrine building.'),
		('LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Faith] Faith in every Temple building.'),
		('LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Faith] Faith in every worship building.'),
		('LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 [ICON_Gold] Gold in the [ICON_Capital] Capital and in every Market or Lighthouse building.'),
		('LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Gold] Gold in every Bank and Shipyard building.'),
		('LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 [ICON_Gold] Gold in every Stock Exchange and Seaport building.'),
		('LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Culture] Culture in the [ICON_Capital] Capital and in every Amphitheater building.'),
		('LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Culture] Culture in every Art Museum and Archeological Museum building.'),
		('LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Culture] Culture in every Broadcast Center building.'),
		('LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Production] Production in the [ICON_Capital] Capital and in every city with a Barracks or Stable when producing units.'),
		('LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Production in every city with an Armory building when producing units.'),
		('LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Production] Production in every city with a Military Academy building when producing units.'),
		('LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Production] Production in the [ICON_Capital] Capital and in every city with a Workshop building when producing wonders, buildings, and districts.'),
		('LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Production in every city with a Factory building when producing wonders, buildings, and districts.'),
		('LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Production] Production in every city with a Power Plant building when producing wonders, buildings, and districts.');
--------------------------------------------------------------

-- LocalizedText
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Language,		Tag,														Text)
VALUES	('pt_BR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 de [ICON_Science] ciência na [ICON_Capital] capital e em cada edificação de Biblioteca.'),
		('pt_BR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 de [ICON_Science] ciência em cada edificação de Universidade.'),
		('pt_BR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 de [ICON_Science] ciência em cada edificação de Laboratório de Pesquisa.'),
		('pt_BR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 de [ICON_Faith] fé na [ICON_Capital] capital e em cada edificação de Santuário.'),
		('pt_BR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 de [ICON_Faith] fé em cada edificação de Templo.'),
		('pt_BR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 de [ICON_Faith] fé em cada edificação de adoração.'),
		('pt_BR',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 de [ICON_Gold] ouro na [ICON_Capital] capital e em cada edificação de Mercado ou Farol.'),
		('pt_BR',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 de [ICON_Gold] ouro em cada edificação de Banco e Estaleiro.'),
		('pt_BR',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 de [ICON_Gold] ouro em cada edificação de Bolsa de Valores e Porto Marítimo.'),
		('pt_BR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 de [ICON_Culture] cultura na [ICON_Capital] capital e em cada edificação de Anfiteatro.'),
		('pt_BR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 de [ICON_Culture] cultura em cada edificação de Museu de Arte e Museu Arqueológico.'),
		('pt_BR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 de [ICON_Culture] cultura em cada edificação de Centro de Transmissão.'),
		('pt_BR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 de [ICON_Production] produção na [ICON_Capital] capital em cada cidade com uma Caserna ou Estábulo quando produzir unidades.'),
		('pt_BR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 de [ICON_Production] produção em cada cidade com uma edificação de Arsenal quando produzir unidades.'),
		('pt_BR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 de [ICON_Production] produção em cada cidade com uma edificação de Academia Militar quando produzir unidades..'),
		('pt_BR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 de [ICON_Production] produção na [ICON_Capital] capital e em cada cidade com uma edificação de Oficina quando produzir maravilhas, edificações e distritos.'),
		('pt_BR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 de [ICON_Production] produção em cada cidade com uma edificação de Fábrica quando produzir maravilhas, edificações e distritos.'),
		('pt_BR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 de [ICON_Production] produção em cada cidade com uma edificação de Usina de Energia quando produzir maravilhas, edificações e distritos.'),

		('fr_FR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Science] Science +1 dans la [ICON_Capital] capitale et pour chaque bibliothèque construite.'),
		('fr_FR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'[ICON_Science] Science +2 pour chaque université construite.'),
		('fr_FR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'[ICON_Science] Science +3 pour chaque laboratoire de recherche construit.'),
		('fr_FR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Faith] Foi +1 dans la [ICON_Capital] capitale et pour chaque autel construit.'),
		('fr_FR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'[ICON_Faith] Foi +2 pour chaque temple construit.'),
		('fr_FR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'[ICON_Faith] Foi +3 pour chaque lieu de culte construit.'),
		('fr_FR',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'[ICON_Gold] Or +1 dans la [ICON_Capital] capitale pour chaque marché et phare construits.'),
		('fr_FR',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'[ICON_Gold] Or +2 pour chaque banque et chantier naval construits.'),
		('fr_FR',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'[ICON_Gold] Or +3 pour chaque bourse et complexe portuaire construits.'),
		('fr_FR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Culture] Culture +1 dans la [ICON_Capital] capitale et pour chaque amphithéâtre construit.'),
		('fr_FR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'[ICON_Culture] Culture +2 pour chaque musée d''art et musée d''archéologie construits.'),
		('fr_FR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'[ICON_Culture] Culture +3 pour chaque centre de diffusion construite.'),
		('fr_FR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'[ICON_Production] Production +1 dans la [ICON_Capital] capitale et dans chaque ville possédant une caserne ou une écurie lors de la formation d''unités.'),
		('fr_FR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'[ICON_Production] Production +2 dans chaque ville possédant une armurerie lors de la formation d''unités.'),
		('fr_FR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'[ICON_Production] Production +3 dans chaque ville possédant une école militaire lors de la formation d''unités.'),
		('fr_FR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Production] Production +1 lors de la production de merveilles, de bâtiments et de quartiers dans la [ICON_Capital] capitale et dans chaque ville possédant un atelier.'),
		('fr_FR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'[ICON_Production] Production +2 dans chaque ville possédant une usine lors de la production de merveilles, de bâtiments et de quartiers.'),
		('fr_FR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'[ICON_Production] Production +3 dans chaque ville possédant une centrale lors de la production de merveilles, de bâtiments et de quartiers.'),

		('de_DE',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Science] Wissenschaft in der [ICON_Capital] Hauptstadt und in jeder Bibliothek.'),
		('de_DE',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Science] Wissenschaft in jeder Universität.'),
		('de_DE',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Science] Wissenschaft in jedem Forschungslabor.'),
		('de_DE',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Faith] Glauben in der [ICON_Capital] Hauptstadt und in jedem Schrein.'),
		('de_DE',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Faith] Glauben in jedem Tempel.'),
		('de_DE',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Faith] Glauben in jedem Kultgebäude.'),
		('de_DE',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 [ICON_Gold] Gold in der [ICON_Capital] Hauptstadt und in jedem Markt oder Leuchtturm.'),
		('de_DE',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 [ICON_Gold] Gold in jeder Bank und Werft.'),
		('de_DE',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 [ICON_Gold] Gold in jeder Börse und jedem Seehafen.'),
		('de_DE',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Culture] Kultur in der [ICON_Capital] Hauptstadt und jedem Amphitheater.'),
		('de_DE',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Culture] Kultur in jedem Kunstmuseum und archäologischen Museum.'),
		('de_DE',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Culture] Kultur in jedem Sendezentrum.'),
		('de_DE',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Production] Produktion in der [ICON_Capital] Hauptstadt und in jeder Stadt mit einer Kaserne oder Stallungen beim Bau von Einheiten.'),
		('de_DE',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Produktion in jeder Stadt mit einer Waffenkammer beim Bau von Einheiten.'),
		('de_DE',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Production] Produktion in jeder Stadt mit einer Militärakademie beim Bau von Einheiten.'),
		('de_DE',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Production] Produktion in der [ICON_Capital] Hauptstadt und in jeder Stadt mit einer Werkstatt beim Bau von Wundern, Gebäuden und Bezirken.'),
		('de_DE',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Produktion in jeder Stadt mit einer Fabrik beim Bau von Wundern, Gebäuden und Bezirken.'),
		('de_DE',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Production] Produktion in jeder Stadt mit einem Kraftwerk beim Bau von Wundern, Gebäuden und Bezirken.'),

		('it_IT',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Science] Scienza nella [ICON_Capital] capitale e da ogni edificio Biblioteca.'),
		('it_IT',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Science] Scienza da ogni edificio Università.'),
		('it_IT',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Science] Scienza da ogni edificio Laboratorio di ricerca.'),
		('it_IT',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Faith] Fede nella [ICON_Capital] capitale e da ogni Santuario.'),
		('it_IT',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Faith] Fede da ogni edificio Tempio.'),
		('it_IT',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Faith] Fede da ogni edificio di culto.'),
		('it_IT',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 [ICON_Gold] Oro nella [ICON_Capital] capitale e da ogni edificio Mercato e Faro.'),
		('it_IT',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 [ICON_Gold] Oro da ogni edificio Banca e Cantiere.'),
		('it_IT',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 [ICON_Gold] Oro da ogni edificio Borsa e Porto internazionale.'),
		('it_IT',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Culture] Cultura nella [ICON_Capital] capitale e da ogni edificio Anfiteatro.'),
		('it_IT',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Culture] Cultura da ogni edificio Museo d''arte e Museo archeologico.'),
		('it_IT',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Culture] Cultura da ogni edificio Centro di radiodiffusione.'),
		('it_IT',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Production] Produzione nella [ICON_Capital] capitale e in ogni città che ha una Caserma o una Scuderia quando costruisce unità.'),
		('it_IT',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Produzione in ogni città che ha un''Armeria quando costruisce unità.'),
		('it_IT',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Production] Produzione in ogni città che ha un''Accademia militare quando costruisce unità.'),
		('it_IT',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Production] Produzione nella [ICON_Capital] capitale e in ogni città che ha una Bottega quando costruisce Meraviglie, edifici o distretti.'),
		('it_IT',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] Produzione in ogni città che ha una Fabbrica quando costruisce Meraviglie, edifici o distretti.'),
		('it_IT',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Production] Produzione in ogni città che ha una Centrale elettrica quando costruisce Meraviglie, edifici o distretti.'),

		('ja_JP',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'すべての図書館と [ICON_Capital] 首都の [ICON_Science] 科学力+1。'),
		('ja_JP',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'すべての大学の [ICON_Science] 科学力+2。'),
		('ja_JP',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'すべての研究所の [ICON_Science] 科学力+3。'),
		('ja_JP',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'すべての社と [ICON_Capital] 首都の [ICON_Faith] 信仰力+1。'),
		('ja_JP',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'すべての神殿の [ICON_Faith] 信仰力+2。'),
		('ja_JP',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'すべての礼拝所の [ICON_Faith] 信仰力+3。'),
		('ja_JP',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'すべての市場または灯台と [ICON_Capital] 首都の [ICON_GOLD] ゴールド+1。'),
		('ja_JP',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'すべての銀行または造船所の [ICON_GOLD] ゴールド+2。'),
		('ja_JP',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'すべての証券取引所または港湾の [ICON_GOLD] ゴールド+3。'),
		('ja_JP',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'すべての円形闘技場と [ICON_Capital] 首都の [ICON_CULTURE] 文化力+1。'),
		('ja_JP',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'すべての美術館または考古博物館の [ICON_CULTURE] 文化力+2。'),
		('ja_JP',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'すべての放送センターの [ICON_CULTURE] 文化力+3。'),
		('ja_JP',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'ユニットの生産時、兵舎か厩舎がある都市の数に応じて、それぞれ [ICON_Capital] 首都の [ICON_Production] 生産力+1。'),
		('ja_JP',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'ユニットの生産時、武器庫がある都市の [ICON_Production] 生産力+2。'),
		('ja_JP',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'ユニットの生産時、士官学校がある都市の [ICON_Production] 生産力+3。'),
		('ja_JP',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'遺産、建造物、区域の生産時、 [ICON_Capital] 首都と工房がある各都市の [ICON_Production] 生産力+1。'),
		('ja_JP',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'遺産、建造物、区域の生産時、工場がある都市の [ICON_Production] 生産力+2。'),
		('ja_JP',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'遺産、建造物、区域の生産時、発電所がある都市の [ICON_Production] 生産力+3。'),

		('ko_KR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 수도 및 모든 도서관 건물에서 [ICON_Science] 과학 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'모든 대학 건물에서 [ICON_Science] 과학 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'모든 연구소 건물에서 [ICON_Science] 과학 +3.'),
		('ko_KR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 수도 및 모든 성소 건물에서 [ICON_Faith] 문화 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'모든 사원 건물에서 [ICON_Faith] 신앙 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'모든 예배 건물에서 [ICON_Faith] 신앙 +3.'),
		('ko_KR',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'[ICON_Capital] 수도 및 모든 시장 또는 등대 건물에서 [ICON_Gold] 금 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'모든 은행 및 조선소 건물에서 [ICON_Gold] 금 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'모든 증권 거래소 및 항구 건물에서 [ICON_Gold] 금 +3.'),
		('ko_KR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 수도 및 모든 원형 극장 건물에서 [ICON_Culture] 문화 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'모든 미술관 및 고고학 박물관 건물에서 [ICON_Culture] 문화 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'모든 방송 센터 건물에서 [ICON_Culture] 문화 +3.'),
		('ko_KR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'유닛 생산 시 병영이나 마구간이 있는 [ICON_Capital] 수도 및 모든 도시에 [ICON_Production] 생산력 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'유닛 생산 시, 무기고 건물이 있는 모든 도시에 [ICON_Production] 생산력 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'유닛 생산 시, 사관 학교 건물이 있는 모든 도시에 [ICON_Production] 생산력 +3.'),
		('ko_KR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'불가사의, 건물 및 특수지구 건설 시, 작업장 건물이 있는 [ICON_Capital] 수도 및 모든 도시에 [ICON_Production] 생산력 +1.'),
		('ko_KR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'불가사의, 건물 및 특수지구 건설 시, 공장 건물이 있는 모든 도시에 [ICON_Production] 생산력 +2.'),
		('ko_KR',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'불가사의, 건물 및 특수지구 건설 시, 발전소 건물이 있는 모든 도시에 [ICON_Production] 생산력 +3.'),

		('pl_PL',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 do [ICON_Science] nauki w [ICON_Capital] stolicy i w każdej bibliotece.'),
		('pl_PL',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 do [ICON_Science] nauki w każdym uniwersytecie.'),
		('pl_PL',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 do [ICON_Science] nauki w każdym laboratorium badawczym.'),
		('pl_PL',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 do [ICON_Faith] wiary w [ICON_Capital] stolicy i w każdej kaplicy.'),
		('pl_PL',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 do [ICON_Faith] wiary w każdej świątyni.'),
		('pl_PL',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 do [ICON_Faith] wiary w każdej budowli kultu.'),
		('pl_PL',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 [ICON_Gold] złota w [ICON_Capital] stolicy oraz w każdym targowisku i latarni.'),
		('pl_PL',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 [ICON_Gold] złota w każdym banku i stoczni.'),
		('pl_PL',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 [ICON_Gold] złota w każdej giełdzie i porcie morskim.'),
		('pl_PL',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 do [ICON_CULTURE] kultury w [ICON_Capital] stolicy i w każdym amfiteatrze.'),
		('pl_PL',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 do [ICON_CULTURE] kultury w każdym muzeum sztuki i muzeum archeologicznym.'),
		('pl_PL',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 do [ICON_CULTURE] kultury w każdym centrum nadawczym.'),
		('pl_PL',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 do [ICON_Production] produkcji w [ICON_Capital] stolicy i w każdym mieście z koszarami lub stajnią przy produkcji jednostek.'),
		('pl_PL',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 do [ICON_Production] produkcji w każdym mieście ze zbrojownią przy produkcji jednostek.'),
		('pl_PL',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 do [ICON_Production] produkcji w każdym mieście z akademią wojskową przy produkcji jednostek.'),
		('pl_PL',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 do [ICON_Production] produkcji w [ICON_Capital] stolicy i w każdym mieście z warsztatem przy produkcji cudów, budowli i dzielnic.'),
		('pl_PL',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 do [ICON_Production] produkcji w każdym mieście z fabryką przy produkcji cudów, budowli i dzielnic.'),
		('pl_PL',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 do [ICON_Production] produkcji w każdym mieście z elektrownią przy produkcji cudów, budowli i dzielnic.'),

		('ru_RU',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Science] науки для столицы [ICON_Capital] и каждой библиотеки.'),
		('ru_RU',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Science] науки в каждом университете.'),
		('ru_RU',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Science] науки в каждой лаборатории.'),
		('ru_RU',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Faith] веры для столицы [ICON_Capital] и каждого святилища.'),
		('ru_RU',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Faith] веры в каждом храме.'),
		('ru_RU',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Faith] веры в каждом религиозном здании.'),
		('ru_RU',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 [ICON_Gold] золота в [ICON_Capital] столице и от каждого рынка и маяка.'),
		('ru_RU',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 [ICON_Gold] золота в каждом банке и в каждой верфи.'),
		('ru_RU',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 [ICON_Gold] золота на каждой бирже, и в каждом морском порту.'),
		('ru_RU',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Culture] культуры для столицы [ICON_Capital] и для каждого амфитеатра.'),
		('ru_RU',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 [ICON_Culture] культуры для каждого художественного и археологического музея.'),
		('ru_RU',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Culture] культуры в каждом центре вещания.'),
		('ru_RU',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 [ICON_Production] производства в столице [ICON_Capital], в каждом городе с казармами или конюшней при создании юнитов.'),
		('ru_RU',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] производства в каждом городе с оружейной при создании юнитов.'),
		('ru_RU',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 [ICON_Production] производства в каждом городе с военной академией при создании юнитов.'),
		('ru_RU',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 [ICON_Production] производства в столице [ICON_Capital], в каждом городе с мастерской при строительстве чудес света, зданий и районов.'),
		('ru_RU',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 [ICON_Production] производства в каждом городе с фабрикой при строительстве чудес света, зданий и районов.'),
		('ru_RU',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 [ICON_Production] производства в каждом городе с электростанцией при строительстве чудес света, зданий и районов.'),

		('zh_Hans_CN',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都和每座图书馆+1 [ICON_Science] 科技值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'每座大学+2 [ICON_Science] 科技值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'每座研究实验室+3 [ICON_Science] 科技值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都和每座神社+1 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'每座寺庙+2 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'每座祭祀建筑+3 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'[ICON_Capital] 首都和每座市场/灯塔+1 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'每座银行/造船厂+2 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'每座证券交易所/码头+3 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都和每座古罗马剧场+1 [ICON_Culture] 文化值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'每座美术馆/考古博物馆+2 [ICON_Culture] 文化值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'每座广播中心+3 [ICON_Culture] 文化值。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'生产单位时，[ICON_Capital] 首都和拥有兵营/马厩的城市+1 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'在拥有兵工厂的城市中生产单位时+2 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'在拥有军事学院的城市中生产单位时+3 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'建造奇观、建筑和区域时，[ICON_Capital] 首都和拥有工作坊的城市+1 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'在拥有工厂的城市中建造奇观、建筑和区域时+2 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'在拥有发电厂的城市中建造奇观、建筑和区域时+3 [ICON_Production] 生产力。'),

		('es_ES',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 a Ciencia [ICON_Science] en la Capital [ICON_Capital] y en todas las Bibliotecas.'),
		('es_ES',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 a Ciencia [ICON_Science] en todas las Universidades.'),
		('es_ES',		'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 a Ciencia [ICON_Science] en todos los Laboratorios de investigación.'),
		('es_ES',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 a la Fe [ICON_Faith] en la Capital [ICON_Capital] y en todos los Santuarios.'),
		('es_ES',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 a Fe [ICON_Faith] en todos los Templos.'),
		('es_ES',		'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 a Fe [ICON_Faith] en todos los edificios de culto.'),
		('es_ES',		'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'+1 al Oro [ICON_Gold] en la Capital [ICON_Capital] y en todos los Mercados y Faros.'),
		('es_ES',		'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'+2 de Oro [ICON_Gold] en todos los Bancos y Astilleros.'),
		('es_ES',		'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'+3 de Oro [ICON_Gold] en todas las Bolsas y los Puertos marítimos.'),
		('es_ES',		'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 a Cultura [ICON_Culture] en la Capital [ICON_Capital] y en todos los Anfiteatros.'),
		('es_ES',		'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'+2 a Cultura [ICON_Culture] en todos los Museos de arte y Museos arqueológicos.'),
		('es_ES',		'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 a Cultura [ICON_Culture] en todos los Centros de transmisión.'),
		('es_ES',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'+1 a la Producción [ICON_Production] en la Capital [ICON_Capital] y en todas las ciudades con un Cuartel o un Establo al producir unidades.'),
		('es_ES',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 a la Producción [ICON_Production] en cada ciudad con un Arsenal al producir unidades.'),
		('es_ES',		'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'+3 a la Producción [ICON_Production] en cada ciudad con una Academia militar al producir unidades.'),
		('es_ES',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'+1 a la Producción [ICON_Production] en la Capital [ICON_Capital] y en cada ciudad con un Taller al producir maravillas, edificios y distritos.'),
		('es_ES',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'+2 a la Producción [ICON_Production] en cada ciudad con una Fábrica al producir maravillas, edificios y distritos.'),
		('es_ES',		'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'+3 a la Producción [ICON_Production] en cada ciudad con una Planta eléctrica al producir maravillas, edificios y distritos.'),
		
		('zh_Hant_HK',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都與每座圖書館+1 [ICON_Science] 科技值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'每座大學+2 [ICON_Science] 科技值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS',		'每座研究實驗室+3 [ICON_Science] 科技值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都與每座神社+1 [ICON_Faith] 信仰值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS',		'每座寺廟+2 [ICON_Faith] 信仰值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS',		'每座祭祀建築+3 [ICON_Faith] 信仰值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_TRADE_TRAIT_SMALL_INFLUENCE_BONUS',			'[ICON_Capital] 首都與每座市場/燈塔+1 [ICON_Gold] 金幣。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS',			'每間銀行/造船廠+2 [ICON_Gold] 金幣。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_TRADE_TRAIT_LARGE_INFLUENCE_BONUS',			'每間證券交易所/碼頭+3 [ICON_Gold] 金幣。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS',		'[ICON_Capital] 首都與每座古羅馬劇場+1 [ICON_Culture] 文化值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS',		'每座美術館/考古博物館+2 [ICON_Culture] 文化值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS',		'每座廣播中心+3 [ICON_Culture] 文化值。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS',	'生產單位時，[ICON_Capital] 首都與擁有兵營/馬廄的城市+1 [ICON_Production] 生產力。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS',	'生產單位時，擁有兵工廠的城市+2 [ICON_Production] 生產力。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS',	'生產單位時，擁有軍事學院的城市+3 [ICON_Production] 生產力。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS',		'建造奇觀、建築和區域時，[ICON_Capital] 首都與擁有工作坊的城市+1 [ICON_Production] 生產力。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS',	'建造奇觀、建築及區域時，擁有工廠的城市+2 [ICON_Production] 生產力。'),
		('zh_Hant_HK',	'LOC_MINOR_CIV_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS',		'建造奇觀、建築及區域時，擁有發電廠的城市+3 [ICON_Production] 生產力。');