--- Players

INSERT INTO Players
			(CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'LOC_CIVILIZATION_MACEDON_NAME',	'ICON_CIVILIZATION_MACEDON',	'LOC_LEADER_SC_EURYDICE_NAME',	'ICON_LEADER_SC_EURYDICE',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_NAME',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_DESCRIPTION',	'ICON_CIVILIZATION_MACEDON',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_NAME',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_DESCRIPTION',	'ICON_LEADER_SC_EURYDICE',	'LEADER_SC_EURYDICE_NEUTRAL', 'LEADER_HOJO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'UNIT_MACEDONIAN_HYPASPIST',	'LOC_UNIT_MACEDONIAN_HYPASPIST_NAME',	'LOC_UNIT_MACEDONIAN_HYPASPIST_DESCRIPTION',	'ICON_UNIT_MACEDONIAN_HYPASPIST',	10),
			('CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'BUILDING_BASILIKOI_PAIDES',		'LOC_BUILDING_BASILIKOI_PAIDES_NAME',	'LOC_BUILDING_BASILIKOI_PAIDES_DESCRIPTION',		'ICON_BUILDING_BASILIKOI_PAIDES',	20);

--- Players

INSERT INTO Players
			(Domain,						CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('Players:Expansion1_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'LOC_CIVILIZATION_MACEDON_NAME',	'ICON_CIVILIZATION_MACEDON',	'LOC_LEADER_SC_EURYDICE_NAME',	'ICON_LEADER_SC_EURYDICE',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_NAME',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_DESCRIPTION',	'ICON_CIVILIZATION_MACEDON',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_NAME',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_DESCRIPTION',	'ICON_LEADER_SC_EURYDICE',	'LEADER_SC_EURYDICE_NEUTRAL', 'LEADER_HOJO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(Domain,						CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('Players:Expansion1_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'UNIT_MACEDONIAN_HYPASPIST',	'LOC_UNIT_MACEDONIAN_HYPASPIST_NAME',	'LOC_UNIT_MACEDONIAN_HYPASPIST_DESCRIPTION',	'ICON_UNIT_MACEDONIAN_HYPASPIST',	10),
			('Players:Expansion1_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'BUILDING_BASILIKOI_PAIDES',		'LOC_BUILDING_BASILIKOI_PAIDES_NAME',	'LOC_BUILDING_BASILIKOI_PAIDES_DESCRIPTION',		'ICON_BUILDING_BASILIKOI_PAIDES',	20);

--- Players

INSERT INTO Players
			(Domain,						CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('Players:Expansion2_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'LOC_CIVILIZATION_MACEDON_NAME',	'ICON_CIVILIZATION_MACEDON',	'LOC_LEADER_SC_EURYDICE_NAME',	'ICON_LEADER_SC_EURYDICE',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_NAME',	'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_DESCRIPTION',	'ICON_CIVILIZATION_MACEDON',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_NAME',	'LOC_TRAIT_LEADER_SC_BROAD_JUSTICE_DESCRIPTION',	'ICON_LEADER_SC_EURYDICE',	'LEADER_SC_EURYDICE_NEUTRAL', 'LEADER_HOJO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(Domain,						CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('Players:Expansion2_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'UNIT_MACEDONIAN_HYPASPIST',	'LOC_UNIT_MACEDONIAN_HYPASPIST_NAME',	'LOC_UNIT_MACEDONIAN_HYPASPIST_DESCRIPTION',	'ICON_UNIT_MACEDONIAN_HYPASPIST',	10),
			('Players:Expansion2_Players',	'CIVILIZATION_MACEDON',	'LEADER_SC_EURYDICE',	'BUILDING_BASILIKOI_PAIDES',		'LOC_BUILDING_BASILIKOI_PAIDES_NAME',	'LOC_BUILDING_BASILIKOI_PAIDES_DESCRIPTION',		'ICON_BUILDING_BASILIKOI_PAIDES',	20);