-- Policies need icons for the pedia, who'd have thunk
-- ECONOMIC: 0
-- MILITARY: 1
-- DIPLOMATIC: 2
-- WILDCARD: 3
INSERT INTO IconDefinitions
		(Name,									Atlas,							'Index')
VALUES	('ICON_POLICY_LEU_RELIGIOUS_TOLERANCE',		'ICON_ATLAS_POLICIES',			2),		
		('ICON_POLICY_LEU_VOTIVE_OFFERINGS',		'ICON_ATLAS_POLICIES',			2),		
		('ICON_POLICY_LEU_CATECHESIS',				'ICON_ATLAS_POLICIES',			2),
		('ICON_POLICY_LEU_TELEVANGELISM',			'ICON_ATLAS_POLICIES',			2);