-- LHM_Modifier
-- Author: Ithildin
-- DateCreated: 2/24/2024 12:38:34 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_HUAQUNG_POOL',					'MODFEAT_HUAQUNG_DIPLOMATIC_SLOT'),
		('BUILDING_HUAQUNG_POOL',					'MODFEAT_HUAQUNG_TOURISM');

INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
SELECT	'BUILDING_HUAQUNG_POOL',					'MODFEAT_HUAQUNG_HEAL'			FROM Leaders WHERE LeaderType = 'LEADER_PHANTA_YANG_YUHUAN'
UNION SELECT	'BUILDING_HUAQUNG_POOL',			'MODFEAT_HUAQUNG_TRADE_GOLD'	FROM Leaders WHERE LeaderType = 'LEADER_PHANTA_LI_LONGJI'
UNION SELECT	'BUILDING_HUAQUNG_POOL',			'MODFEAT_HUAQUNG_TRADE_CULTURE'	FROM Leaders WHERE LeaderType = 'LEADER_PHANTA_LI_LONGJI';
		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	('MODFEAT_HUAQUNG_DIPLOMATIC_SLOT',			'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',			NULL),
		('MODFEAT_HUAQUNG_TOURISM',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_TOURISM_CHANGE',					'REQSET_HUAQUNG_CITY_CENTER_IN_6_PLOT'),
		('MODFEAT_HUAQUNG_HEAL',					'MODIFIER_SINGLE_CITY_RELIGIOUS_HEAL',								NULL),
		('MODFEAT_HUAQUNG_TRADE_GOLD',				'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL),
		('MODFEAT_HUAQUNG_TRADE_CULTURE',			'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_HUAQUNG_DIPLOMATIC_SLOT',			'GovernmentSlotType',	'SLOT_DIPLOMATIC'),
		('MODFEAT_HUAQUNG_TOURISM',					'Amount',				2),
		('MODFEAT_HUAQUNG_HEAL',					'Amount',				100),
		('MODFEAT_HUAQUNG_TRADE_GOLD',				'YieldType',			'YIELD_GOLD'),
		('MODFEAT_HUAQUNG_TRADE_GOLD',				'Amount',				2),
		('MODFEAT_HUAQUNG_TRADE_CULTURE',			'YieldType',			'YIELD_CULTURE'),
		('MODFEAT_HUAQUNG_TRADE_CULTURE',			'Amount',				1);

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('REQSET_HUAQUNG_CITY_CENTER_IN_6_PLOT',	'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_HUAQUNG_CITY_CENTER_IN_6_PLOT',	'REQ_HUAQUNG_IN_6_PLOT'), 
		('REQSET_HUAQUNG_CITY_CENTER_IN_6_PLOT',	'REQ_HUAQUNG_CITY_CENTER');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQ_HUAQUNG_IN_6_PLOT',					'REQUIREMENT_PLOT_ADJACENT_TO_OWNER'), 
		('REQ_HUAQUNG_CITY_CENTER',					'REQUIREMENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_HUAQUNG_IN_6_PLOT',					'MaxDistance',	6), 
		('REQ_HUAQUNG_CITY_CENTER',					'DistrictType',	'DISTRICT_CITY_CENTER');