INSERT INTO IconTextureAtlases
		(Name,													IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					32,			1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_32.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					38,			1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_38.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					50,			1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_50.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					80,			1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_80.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					128,		1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_128.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET',					256,		1,				1,				'ICON_BUILDING_PHANTA_MALWIYA_MINARET_256.dds'),

		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		256,	 	1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_256.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		80,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_80.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		70,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_70.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		50,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_50.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		38,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_38.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		32,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_32.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		30,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST_30.dds'	),
		
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	256,	 	1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_256.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	80,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_80.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	70,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_70.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	50,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_50.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	38,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_38.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	32,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_32.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',	30,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND_30.dds'	),

		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		256,	 	1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_256.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		80,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_80.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		70,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_70.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		50,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_50.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		38,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_38.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		32,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_32.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		30,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD_30.dds'	),

		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	256,	 	1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_256.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	80,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_80.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	70,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_70.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	50,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_50.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	38,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_38.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	32,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_32.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',	30,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH_30.dds'	),

		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	256,	 	1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_256.dds'),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	80,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_80.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	70,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_70.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	50,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_50.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	38,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_38.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	32,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_32.dds'	),
		('ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',	30,	 		1,				1,				'ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT_30.dds'	);

--------------------------------------------------------------
-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,							Atlas,							'Index')
VALUES	('ICON_BUILDING_PHANTA_MALWIYA_MINARET',		'ICON_ATLAS_PHANTA_MALWIYA_MINARET',					0),
		('ICON_BUILDING_PHANTA_MALWIYA_MINARET_FOW',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET',					0),
		('ICON_PROJECT_PHANTA_MALWIYA_MINARET_FIRST',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET_FIRST_PROJECT',		0),
		('ICON_PROJECT_PHANTA_MALWIYA_MINARET_SECOND',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET_SECOND_PROJECT',		0),
		('ICON_PROJECT_PHANTA_MALWIYA_MINARET_THIRD',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET_THIRD_PROJECT',		0),
		('ICON_PROJECT_PHANTA_MALWIYA_MINARET_FOURTH',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET_FOURTH_PROJECT',		0),
		('ICON_PROJECT_PHANTA_MALWIYA_MINARET_REPEAT',	'ICON_ATLAS_PHANTA_MALWIYA_MINARET_REPEAT_PROJECT',		0);
		
--------------------------------------------------------------