-- 6T_GE_Text_Civilopedia
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,		Tag,																									Text)
VALUES	('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_IBN_BATTUTA_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_TOPA_INCA_YUPANQUI_CHAPTER_HISTORY_PARA_1',		'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_VASCO_DA_GAMA_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_HOTU_MATA_CHAPTER_HISTORY_PARA_1',				'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_BUNGAREE_CHAPTER_HISTORY_PARA_1',				'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_CARL_LINNAEUS_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_JOHN_KIZELL_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_SACAGAWEA_CHAPTER_HISTORY_PARA_1',				'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ALEXANDER_VON_HUMBOLDT_CHAPTER_HISTORY_PARA_1',	'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ISABELLA_BIRD_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_PYOTR_KROPOTKIN_CHAPTER_HISTORY_PARA_1',		'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_CANDIDO_RONDON_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_FRIDTJOF_NANSEN_CHAPTER_HISTORY_PARA_1',		'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_NELLIE_BLY_CHAPTER_HISTORY_PARA_1',				'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ROALD_AMUNDSEN_CHAPTER_HISTORY_PARA_1',			'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ALFRED_WEGENER_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_EVA_DICKSON_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_VAINO_AUER_CHAPTER_HISTORY_PARA_1',				'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_THOR_HEYERDAHL_CHAPTER_HISTORY_PARA_1',			'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_JACQUES_YVES_COUSTEAU_CHAPTER_HISTORY_PARA_1',	'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MARIA_KLENOVA_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_TENZING_NORGAY_CHAPTER_HISTORY_PARA_1',			'Biography'),
		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_RACHEL_CARSON_CHAPTER_HISTORY_PARA_1',			'Biography'),

		('en_US',		'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MARIE_CURIE_CHAPTER_HISTORY_PARA_1',			'Biography');
--------------------------------------------------------------
