-- 6TUE_Infantry_Icons_Portraits
-- Author: JNR
--------------------------------------------------------------

-- IconTextureAtlases
--------------------------------------------------------------
INSERT INTO IconTextureAtlases
		(Name,										IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	38,			4,				2,				'6TUE_Infantry_UnitPortraits38.dds'),
		('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	50,			4,				2,				'6TUE_Infantry_UnitPortraits50.dds'),
		('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	70,			4,				2,				'6TUE_Infantry_UnitPortraits70.dds'),
		('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	95,			4,				2,				'6TUE_Infantry_UnitPortraits95.dds'),
		('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	200,		4,				2,				'6TUE_Infantry_UnitPortraits200.dds'),
		('ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	256,		4,				2,				'6TUE_Infantry_UnitPortraits256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,															Atlas,										'Index')
VALUES	('ICON_UNIT_JNR_HEAVY_SPEARMAN_PORTRAIT',						'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	0),
		('ICON_UNIT_JNR_RIFLELINE_PORTRAIT',							'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	1),
		('ICON_UNIT_SWORDSMAN_PORTRAIT',								'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	2),
		('ICON_UNIT_JNR_LONGSWORDSMAN_PORTRAIT',						'ICON_ATLAS_UNIT_PORTRAITS',				32),
		('ICON_UNIT_LINE_INFANTRY_PORTRAIT',							'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	3),
		('ICON_UNIT_JNR_COMPOSITE_ARCHER_PORTRAIT',						'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	4),
		('ICON_UNIT_JNR_ARQUEBUSIER_PORTRAIT',							'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	5),
		('ICON_UNIT_JNR_GATLING_GUN_PORTRAIT',							'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	6),
		('ICON_UNIT_JNR_MORTAR_PORTRAIT',								'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	7),		

		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_HEAVY_SPEARMAN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	0),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_RIFLELINE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	1),
		('ICON_ETHNICITY_AFRICAN_UNIT_SWORDSMAN_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	2),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_LONGSWORDSMAN_PORTRAIT',		'ICON_ATLAS_AFRICAN_UNIT_PORTRAITS',		32),
		('ICON_ETHNICITY_AFRICAN_UNIT_LINE_INFANTRY_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	3),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_COMPOSITE_ARCHER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	4),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_ARQUEBUSIER_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	5),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_GATLING_GUN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	6),
		('ICON_ETHNICITY_AFRICAN_UNIT_JNR_MORTAR_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	7),

		('ICON_ETHNICITY_ASIAN_UNIT_JNR_HEAVY_SPEARMAN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	0),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_RIFLELINE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	1),
		('ICON_ETHNICITY_ASIAN_UNIT_SWORDSMAN_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	2),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_LONGSWORDSMAN_PORTRAIT',		'ICON_ATLAS_ASIAN_UNIT_PORTRAITS',			32),
		('ICON_ETHNICITY_ASIAN_UNIT_LINE_INFANTRY_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	3),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_COMPOSITE_ARCHER_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	4),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_ARQUEBUSIER_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	5),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_GATLING_GUN_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	6),
		('ICON_ETHNICITY_ASIAN_UNIT_JNR_MORTAR_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	7),

		('ICON_ETHNICITY_MEDIT_UNIT_JNR_HEAVY_SPEARMAN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	0),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_RIFLELINE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	1),
		('ICON_ETHNICITY_MEDIT_UNIT_SWORDSMAN_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	2),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_LONGSWORDSMAN_PORTRAIT',		'ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS',	32),
		('ICON_ETHNICITY_MEDIT_UNIT_LINE_INFANTRY_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	3),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_COMPOSITE_ARCHER_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	4),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_ARQUEBUSIER_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	5),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_GATLING_GUN_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	6),
		('ICON_ETHNICITY_MEDIT_UNIT_JNR_MORTAR_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	7),

		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_HEAVY_SPEARMAN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	0),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_RIFLELINE_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	1),
		('ICON_ETHNICITY_SOUTHAM_UNIT_SWORDSMAN_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	2),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_LONGSWORDSMAN_PORTRAIT',		'ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS',	32),
		('ICON_ETHNICITY_SOUTHAM_UNIT_LINE_INFANTRY_PORTRAIT',			'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	3),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_COMPOSITE_ARCHER_PORTRAIT',	'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	4),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_ARQUEBUSIER_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	5),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_GATLING_GUN_PORTRAIT',		'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	6),
		('ICON_ETHNICITY_SOUTHAM_UNIT_JNR_MORTAR_PORTRAIT',				'ICON_ATLAS_JNR_6TUE_INFANTRY_PORTRAITS',	7);
--------------------------------------------------------------