INSERT INTO IconTextureAtlases
		(Name,											IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		32,			1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_32.dds'),
		('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		38,			1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_38.dds'),
		('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		50,			1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_50.dds'),
		('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		80,			1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_80.dds'),
		('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		128,		1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_128.dds'),
		('ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',		256,		1,				1,				'ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,										Atlas,								'Index')
VALUES	('ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY',		'ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',	0),
		('ICON_BUILDING_PHANTA_DENGFENG_OBSERVATORY_FOW',	'ICON_ATLAS_PHANTA_DENGFENG_OBSERVATORY',	0);
--------------------------------------------------------------