-- LondonBridge
-- Author: Ithildin
-- DateCreated: 12/12/2023 8:50:36 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_OLD_LONDON_BRIDGE',				'MODFEAT_LONGONBRIDGE_ROUTE'),
		('BUILDING_OLD_LONDON_BRIDGE',				'MODFEAT_LONGONBRIDGE_FAITH_FROM_TRADE');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('MODFEAT_LONGONBRIDGE_ROUTE',				'MODIFIER_GRANT_ROUTE_IN_RADIUS'),
		('MODFEAT_LONGONBRIDGE_FAITH_FROM_TRADE',	'MODIFIER_CITY_ADJUST_YIELD_FROM_FOREIGN_TRADE_ROUTES_PASSING_THROUGH');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_LONGONBRIDGE_ROUTE',				'Radius',		1), 
		('MODFEAT_LONGONBRIDGE_ROUTE',				'RouteType',	'ROUTE_MEDIEVAL_ROAD'),
		('MODFEAT_LONGONBRIDGE_FAITH_FROM_TRADE',	'Amount',		3),
		('MODFEAT_LONGONBRIDGE_FAITH_FROM_TRADE',	'YieldType',	'YIELD_FAITH');
