-- Wonder_bn
-- Author: Lazire
-- DateCreated: 2/12/2024 1:17:01 PM
--------------------------------------------------------------
INSERT INTO Types
(Type,								Kind)
VALUES
('BUILDING_OPH_PANTHEON_DE_PARIS',	'KIND_BUILDING');

INSERT INTO Buildings
(BuildingType,						Name,										Description,										Quote,								 			AdjacentDistrict,				PrereqCivic,					Cost,	AdvisorType,		MaxWorldInstances, 	IsWonder,			RequiresPlacement)
VALUES
('BUILDING_OPH_PANTHEON_DE_PARIS',	'LOC_BUILDING_OPH_PANTHEON_DE_PARIS_NAME',	'LOC_BUILDING_OPH_PANTHEON_DE_PARIS_DESC',			'LOC_BUILDING_OPH_PANTHEON_DE_PARIS_QUOTE',	 	'DISTRICT_GOVERNMENT',			'CIVIC_THE_ENLIGHTENMENT',		1020,	'ADVISOR_GENERIC',	1,					1,					1);	

INSERT INTO Building_YieldChanges 
(BuildingType,						YieldType,			YieldChange)
VALUES	
('BUILDING_OPH_PANTHEON_DE_PARIS',	'YIELD_CULTURE',	4),
('BUILDING_OPH_PANTHEON_DE_PARIS',	'YIELD_FAITH',		4);

INSERT INTO Building_GreatWorks
(BuildingType,						GreatWorkSlotType,			NumSlots,		NonUniquePersonYield,		NonUniquePersonTourism)
VALUES
('BUILDING_OPH_PANTHEON_DE_PARIS',	'GREATWORKSLOT_CATHEDRAL',	3,				1,							1);

INSERT INTO Building_ValidTerrains
(BuildingType,						TerrainType)
VALUES
('BUILDING_OPH_PANTHEON_DE_PARIS',	'TERRAIN_GRASS'),
('BUILDING_OPH_PANTHEON_DE_PARIS',	'TERRAIN_PLAINS'),
('BUILDING_OPH_PANTHEON_DE_PARIS',	'TERRAIN_DESERT'),
('BUILDING_OPH_PANTHEON_DE_PARIS',	'TERRAIN_TUNDRA'),
('BUILDING_OPH_PANTHEON_DE_PARIS',	'TERRAIN_SNOW');

INSERT INTO BuildingModifiers
(BuildingType,						ModifierId)
VALUES
('BUILDING_OPH_PANTHEON_DE_PARIS',	'MODFEAT_PANTHEON_DE_PARIS_ADJUST_GPP_REFUND');

INSERT INTO Modifiers
(ModifierId,										ModifierType)
VALUES
('MODFEAT_PANTHEON_DE_PARIS_ADJUST_GPP_REFUND',		'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_REFUND_PERCENT');

INSERT INTO ModifierArguments
(ModifierId,										Name,			Value)
VALUES
('MODFEAT_PANTHEON_DE_PARIS_ADJUST_GPP_REFUND',		'Amount',		10);

-- ==========================
-- ///THESE ARE FOR SCRIPT///
-- ==========================
INSERT INTO Modifiers
(ModifierId,								ModifierType)
VALUES
('MODFEAT_PANTHEON_DE_PARIS_SCIENCE',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
('MODFEAT_PANTHEON_DE_PARIS_CULTURE',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
('MODFEAT_PANTHEON_DE_PARIS_PRODUCTION',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
('MODFEAT_PANTHEON_DE_PARIS_FOOD',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
('MODFEAT_PANTHEON_DE_PARIS_FAITH',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
('MODFEAT_PANTHEON_DE_PARIS_GOLD',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');

INSERT INTO ModifierArguments
(ModifierId,								Name,			Value)
VALUES
('MODFEAT_PANTHEON_DE_PARIS_SCIENCE',		'YieldType',	'YIELD_SCIENCE'),
('MODFEAT_PANTHEON_DE_PARIS_SCIENCE',		'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_SCIENCE',		'Amount',		3),

('MODFEAT_PANTHEON_DE_PARIS_CULTURE',		'YieldType',	'YIELD_CULTURE'),
('MODFEAT_PANTHEON_DE_PARIS_CULTURE',		'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_CULTURE',		'Amount',		3),

('MODFEAT_PANTHEON_DE_PARIS_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
('MODFEAT_PANTHEON_DE_PARIS_PRODUCTION',	'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_PRODUCTION',	'Amount',		3),

('MODFEAT_PANTHEON_DE_PARIS_FOOD',			'YieldType',	'YIELD_FOOD'),
('MODFEAT_PANTHEON_DE_PARIS_FOOD',			'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_FOOD',			'Amount',		3),

('MODFEAT_PANTHEON_DE_PARIS_FAITH',			'YieldType',	'YIELD_FAITH'),
('MODFEAT_PANTHEON_DE_PARIS_FAITH',			'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_FAITH',			'Amount',		3),

('MODFEAT_PANTHEON_DE_PARIS_GOLD',			'YieldType',	'YIELD_GOLD'),
('MODFEAT_PANTHEON_DE_PARIS_GOLD',			'BuildingType',	'BUILDING_OPH_PANTHEON_DE_PARIS'),
('MODFEAT_PANTHEON_DE_PARIS_GOLD',			'Amount',		3);

















